### PR TITLE
[Statistics / Behavioural Statistics] fix 500 error

### LINKED ISSUE #6573: [Statistics / Behavioural Statistics] query by project not working.
**Describe the bug**
In `Reports-> Statistics -> Behavioural Statistics`, query by project seems not to by working.

**To Reproduce**
1. Go to `Reports-> Statistics -> Behavioural Statistics`
2. Choose a project on the project's comboBox.
3. Click on Submit Query
4. **Issue:** The results table is not updated except for "All projects" or "DCP" choices

**What did you expect to happen?**
The results table updated accordingly.

**Browser Environment (please complete the following information):**
- OS: Windows
- Browser: Firefox
- Version: 76

### PR DESCRIPTION
**Pull request by racostas**
## Brief summary of changes

This PR address the issues related to the error found in  #6573 but without including the project and site restrictions in #6649 that need to be improved.

#### Testing instructions (if applicable)

1. Go to `Reports->Statistics->Behavioural Statistics`
2. Select different projects on the `Projects ComboBox `and click on `Submit Query`
3. The 500 error should be solved (the user should be able to query for any project without issue).

#### Link(s) to related issue(s)

* Resolves #6573
* Same solution that provided on #6649 but without including the project and site restrictions in that one.

### CODE REVIEW

**Comment by ridz1208** [comment]
@racostas I would rather wait for the full solution in #6573 instead. we can proceed with the release without this

**Comment by driusan** [comment]
I agree

**Comment by driusan** [comment]
Blocked pending resolution of #6649

**Comment by driusan** [comment]
#6649 was merged instead of this. This is no longer required.

**Pull request closed without merging**
