### PR TITLE
[DO NOT LOOK]Test to see how spectacularly things will fail

### PR DESCRIPTION
**Pull request by AnyhowStep**
GO AWAY

### CODE REVIEW

**Comment by AnyhowStep** [comment]
`dbunit` is at, like, 3, now.

**Comment by AnyhowStep** [comment]
Wait... Travis is still on 4.3?

**Comment by AnyhowStep** [comment]
Ah, `composer.lock` should be committed. Gdi. TIL.

**Comment by AnyhowStep** [comment]
`phpunit 5.7` looks safe enough to use. Going to try and learn how to write fancy unit tests now.

**Comment by AnyhowStep** [comment]
Ah.
Class names have to end with `*Test`

**Comment by driusan** [comment]
Please do this on your personal fork and don't send a pull request unless it's intended to be merged.

(You can set Travis to run on commits to your fork through travis-ci.org if you need to)

**Comment by AnyhowStep** [comment]
Killjoy =/

**Pull request closed without merging**
