### PR TITLE
[UI] Improve navigation bar + support mobile/tablet

### PR DESCRIPTION
**Pull request by zaliqarosli**
## Brief summary of changes

This PR is primarily to address issue https://github.com/aces/Loris/issues/6235. However, while fixing that, I found a number of related UI/UX bugs that I also address in this PR. The scope of this PR is only the navigation bar.

#### Testing instructions

Test the following steps on 23.0-release first to see current ui/ux, and then on this PR branch to see the changes.

1. Test on mobile and small screen desktop, noticing the ui/ux:

- click/unclick 'LORIS', '?', and the downturned chevron
- with the menu items showing, click on each menu item
- with the dropdown showing, click on any submenu item

2. Test on full screen desktop, noticing the ui/ux

- hover over every item on the navigation bar
- click/unclick on every item on the nav bar
- with one of the dropdowns showing, click on a submenu item

#### Link(s) to related issue(s)

* Resolves https://github.com/aces/Loris/issues/6235
* Resolves https://github.com/aces/Loris/issues/6278

### CODE REVIEW

**Comment by maltheism** [comment]
@zaliqarosli I love the changes! Great work. 😃

There is still an issue when the width of the browser is 1221px to 992px. Maybe 991px in your code should be changed to 1221px or handle 1221px to 992px differently. Like make class="page-content" get extra top padding (during 1221px to 992px) and to handle the menubar height being now 104px from the usual 52px height.

**Comment by driusan** [comment]
Are there screenshots?

**Comment by zaliqarosli** [comment]
@driusan there's no way to show all the changes with one screenshot because you can only see them through clicking on different elements, and once you click on one element, the visual  feedback of clicking on the previous element disappears

**Comment by zaliqarosli** [comment]
hey @maltheism thanks for checking this out. could you send me a screenshot of what your comment refers to?

**Comment by ridz1208** [comment]
I gave it a try. I'ts alot better but i'll only be able to test it fully once it's on the test VM because i cant set up port forwarding from my tablet.

I do have one tiny comment. When you click on a menu item and click again to close it, it's still highlighted in white with rounded top but squar bottom highlight... i think the highlighting should just be removed...

clicked:
Screenshot from 2020-04-09 11-14-55

unclicked:

Screenshot from 2020-04-09 11-15-07

**Comment by maltheism** [comment]
Hi @zaliqarosli, see the first two screenshots look great for the menubar.



These two screen shots have the menubar hiding content and are between the width `1221px to 992px` as of the previous comment I wrote.



Last screenshot is greater than `1221px` width and looks great.

**Comment by zaliqarosli** [comment]
@ridz1208 my last commit fixes your issue

**Comment by zaliqarosli** [comment]
@maltheism i figured out a pretty nice solution! check out my last commit. a changed functionality as a result of it is that on mobile, the navbar pushes the content down, instead of hovering over it which I think is a fine consequence 

Screenshot 2020-04-09 13 19 32

as opposed to 

Screenshot 2020-04-09 13 23 54

**Comment by maltheism** [comment]
@zaliqarosli awesome!

**Pull request merged**
