### PR TITLE
data_dictionary_builder.php unique constraint fix

### PR DESCRIPTION
**Pull request by laemtl**
Fix the data_dictionary_builder.php script 
~~by enforcing the unique key constraint Name + SourceFrom.~~
by reducing the scope of the main query to instruments. Instruments have unique parameter names, and the script is intended to  build a dictionary for instruments. 

Error below was encountered with EEG/MRI parameter_file fields.

Error seen when 2 parameter_type entries share the same Name:
```
lorisadmin@smathew-dev:/var/www/loris/project/tools/exporters$ php data_dictionary_builder.php
Could not execute Select Name, ParameterTypeID from parameter_type. Stack trace#0 /var/www/loris/project/tools/exporters/data_dictionary_builder.php(60): Database->pselectColWithIndexKey()
#1 {main}
PHP Fatal error:  Uncaught DatabaseException: The uniqueKey supplied to pselectColWithIndexKey() does not 
                    appear to be unique or is nullable. This function expects the 
                    key to be both UNIQUE and NOT NULL. in /var/www/loris/php/libraries/Database.class.inc:971
Stack trace:
#0 /var/www/loris/project/tools/exporters/data_dictionary_builder.php(60): Database->pselectColWithIndexKey()
```

### CODE REVIEW

**Review by sruthymathew123 — APPROVED** [review]
Tesed and looks good

**Comment by ridz1208** [comment]
@laemtl what is the usecase here? In my DB, the Name parameter includes the "sourceFrom" basically on my end Name = sourcefrom+sourcefield

**Comment by ridz1208** [comment]
@driusan I think the better fix here would be to make sure this script is looking at instrument fields in parameter_type. What do you think?

**Comment by driusan** [comment]
I still don't understand. There are 2 issues:

1. What do EEG/MRI pipelines have to do with this script? This script parses and generates parameter_type entries for the `Instruments` category and pipelines shouldn't be categorized as Instruments.
2. I don't see why the the constraint is (SourceFrom, Name) in the parameter_type schema. That change appears to have been introduced without explanation in PR#7503 (which only talks about the same parameter being duplicated across different IDs, not different IDs having the same name.) "SourceFrom" is just a table name for the "SourceField" which is a field name database field name. They have nothing to do with the name (other than the name sometimes being derived from the table/field name for instruments.) SourceFrom is **not** a pipeline name which it seems like is being incorrectly assumed here.

**Comment by cmadjar** [comment]
@driusan also, sourcefrom is linking to `parameter_file` in the case of MRI and `physiological_parameter_file` tables in the case of EEG. So there are no pipeline names specified in this field but tables used by the imaging pipelines. Maybe the phrasing caused some confusion.

**Comment by laemtl** [comment]
@cmadjar We can join the table parameter_type_category to filter the instruments.

**Comment by laemtl** [comment]
@driusan 
```
What do EEG/MRI pipelines have to do with this script? This script parses and generates parameter_type entries for the Instruments category and pipelines shouldn't be categorized as Instruments.
```
Current script implementation do not distinguish instrument vs other parameters, so the first select in the script is failing. That as far as EEG/MRI is involved.

**Review by ridz1208 — APPROVED** [review]

**Pull request merged**
