### PR TITLE
[survey_accounts] Clean up after Email col removed

### PR DESCRIPTION
**Pull request by zaliqarosli**
## Brief summary of changes

- [ ] Have you updated related documentation?

The `Email` column of the participant_accounts table was removed in https://github.com/aces/Loris/pull/7248.
This PR cleans up the remaining references to that column, and removes from the schema/raisinbread

#### Testing instructions (if applicable)

1.

#### Link(s) to related issue(s)

* Resolves #  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by driusan** [comment]
Seems to be missing an `SQL/Cleanup_patches/` patch (I doubled checked and I don't see one already there either.)

**Comment by zaliqarosli** [comment]
@driusan its been archived https://github.com/aces/Loris/blob/main/SQL/Archive/21.0/Cleanup/2020-12-18-Remove_survey_emails.sql

**Comment by driusan** [comment]
@ridz1208 are we supposed to archive cleanup patches? I thought the point of them were that they're run at your discretion outside of the release cycle.

**Comment by ridz1208** [comment]
@driusan I think we are archiving them so they dont grow into a eternal list, basically to know which patches were added for which release but they are optional yes

**Comment by zaliqarosli** [comment]
@driusan @ridz1208 it is true though that the patch was never added to Cleanup_patches for the releases it was added to, the patch went straight to archive. would it need to be added there?
https://github.com/aces/Loris/tree/v21.0.7/SQL/Cleanup_patches and https://github.com/aces/Loris/tree/v22.0.4/SQL/Cleanup_patches

**Pull request merged**
