### PR TITLE
reactify breadcrumbs

### PR DESCRIPTION
**Pull request by jstirling91**

### CODE REVIEW

**Comment by jstirling91** [comment]
Failing travis because the Candidate Parameters page and subpages are not loading properly. They all get the error ```Could not select Candidate data from the database (DCCID: )``` when loaded. This causes the javascript to crash and the react breadcrumbs do not load. We should fix the test cases to configure the database so the module properly loads.

**Comment by driusan** [comment]
Why is that failing on this but not other pull requests?

**Comment by jstirling91** [comment]
It fails because the breadcrumbs don't load. The Candidate Parameters javascript file causes an error because the page isn't properly loaded, which leads to the react breadcrumb file not being executed. All are load test cases check to see if the module name is present in the breadcrumb. When it was rendered using smarty they always loaded if the backend didn't return a 500 error. Now that I've switched the breadcrumbs to render in the front end, they won't load if there is an error present in the modules base javascript file.

**Comment by driusan** [comment]
This needs to be rebased

**Comment by stronnics** [comment]
Great job Jordan. Would it be possible to split this PR to make it easier to code review? All the SQL, CSS, small stuff seems perfect to me, should be merged. The JS part would need another PR and code-review if possible.

**Pull request merged**
