### PR TITLE
[Core] Update React to 15.4.1

### PR DESCRIPTION
**Pull request by alisterdev**
**Done**
- [x] Update dependencies
- [x] Replace all React.render with ReactDOM.render
- [x] Fix all fatal errors and warnings in the core JSX codebase
- [x] Remove all calls to getDOMNode() as this function does not exist anymore

**Todo**
- [x] Go over every module to fix errors if any

>**Note 1** 
The PR is nicely broken down by commit for an easier review process

>**Note 2**
All help in testing and bug fixes is highly appreciated 👍

### CODE REVIEW

**Comment by alisterdev** [comment]
@driusan @jstirling91 @xlecours @jacobpenny You are welcome to take a look/test

**Comment by alisterdev** [comment]
@driusan Would be nice to merge this ASAP, so I won't have to rebase every time somebody gets his changes merged + we'll have more time to test and find bugs if any

**Comment by driusan** [comment]
This is failing Travis now.

**Comment by alisterdev** [comment]
@driusan Fixed

**Pull request merged**
