### PR TITLE
[Timepoint List] Fixing bad logic in Timepoint List Control Panel

### PR DESCRIPTION
**Pull request by Jkat**
### Brief summary of changes

Unnecessary extra data_entry permission check...

### To test this change...

- [x] refresh the timepoint list page

### CODE REVIEW

**Comment by driusan** [comment]
@Jkat can you send this to minor? It's not a bug fix, it's just cleanup.

**Comment by johnsaigle** [comment]
Adding Needs Rebase as there is a conflict now that 21 has been merged into `minor`.

**Comment by johnsaigle** [comment]
@Jkat You'll need to rebase this again cause there was an issue with Travis.

**Comment by driusan** [comment]
Doesn't seem to need rebase, there aren't any conflicts

**Comment by Jkat** [comment]
FYI I restarted travis and it seemed to build fine without rebasing 🤷‍♂️

**Pull request merged**
