### PR TITLE
[instrument list] BVL QC Status bug for MYSQL 5.7

### PR DESCRIPTION
**Pull request by kongtiaowang**
https://redmine.cbrain.mcgill.ca/issues/12801
Adding Utility::nullifyEmpty into function

### CODE REVIEW

**Comment by driusan** [comment]
This is weird, I don't see how this got to the last column on the code review project (I don't see anything in the history of it being added to any column in the code review project at all).. but I agree with @xlecours

**Comment by kongtiaowang** [comment]
@xlecours could u review again?

**Comment by ridz1208** [comment]
@davidblader if you have a mysql 5.7 please test this

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

the BVL QC Status saves now, but BVL QC type does not save if you try to set it to 'Not Done' (for the exact reason as the fix you did in this pull request). I think it makes sense to update your pull request to fix this other bug as well?

**Comment by ridz1208** [comment]
@kongtiaowang is this ready ?

**Comment by kongtiaowang** [comment]
@MounaSafiHarab  Could u test it?

**Comment by kongtiaowang** [comment]
@ridz1208 it is ready to test

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

works now for both BVL QC Status and BVL QC Type if you were to select the option 'Not Done'!

I was just confused why the logic change in BVL QC Type code section is more elaborate than that in the BVL QC Status part (I thought the change would be identical). But this is irrelevant to manual testing.

**Pull request merged**
