### PR TITLE
[dqt] Saved queries show fields for private but not for public queries

### LINKED ISSUE #7684: [Data Query Tool (Beta)] Saved queries show fields for private but not for public queries
**Describe the bug**
Saved queries are displayed differently if saved privately or publicly. Private queries show all fields selected, whereas public queries do not.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'Data Query Tool (Beta)' module
2. Click on 'Load Existing Query' and compare 'User' and 'Shared' saved queries.

**What did you expect to happen?**
'User' and 'Shared' saved queries should be displayed in the same way.

**Browser Environment (please complete the following information):**
- Browser: Chrome

**Server Environment (if known):**
- LORIS Version: v24.0 testing

Screen Shot 2021-10-04 at 7 56 11 PM

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Solves issue: https://github.com/aces/Loris/issues/7684

#### Testing instructions (if applicable)

1. Go to 'Data Query Tool (Beta)' module
2. Click on 'Load Existing Query' and compare 'User' and 'Shared' saved queries.

#### Link(s) to related issue(s)

* Resolves #7684

### CODE REVIEW

**Comment by maltheism** [comment]
@driusan this PR should be merged soon because the "fixes" commit corrects things that are broken on main.

**Review by xlecours — APPROVED** [review]
There are a lot of changes that have nothing to do with the new expected behaviour. Nevertheless, all the saved queries are displayed the same now.

**Comment by xlecours** [comment]
Why is arrayIntersect,js added?
Why is jstat library removed?

**Comment by maltheism** [comment]
@xlecours they're copied from other PR to prevent rebasing. They're from the dataquery directory and jstat wasn't removed but just moved to node_modules by package.json.

**Pull request merged**
