### PR TITLE
[Dashboard] Restricting users to see statistics only from sites they have access to.

### PR DESCRIPTION
**Pull request by racostas**
## Brief summary of changes

Rebase #5917 into main. Code refactoring.

#### Testing instructions

Now each user should be able to see the dashboard statistics only for the sites it belong/have access to.

#### Link(s) to related issue(s)

* Rebase and refactors #5917

### CODE REVIEW

**Comment by spell00** [comment]
It is not working for me, I can still see the statistics from all 3 sites on the dashboard of my regular user account that has site affiliations with only 2 sites. I was expecting to see the curves of `study progression` for only the 2 sites it is affiliated with. In `Recruitement` , I am still seeing recruitments per site of 3 sites, but I was expecting to see data for 2 sites only.

**Comment by racostas** [comment]
> It is not working for me, I can still see the statistics from all 3 sites on the dashboard of my regular user account that has site affiliations with only 2 sites. I was expecting to see the curves of `study progression` for only the 2 sites it is affiliated with. In `Recruitement` , I am still seeing recruitments per site of 3 sites, but I was expecting to see data for 2 sites only.

Hi @spell00 , I wasn't able to reproduce the issue. Could you please specify the steps you're taking and maybe put some screenshots? I should be missing something.

I tested with a user having two sites and after haven three of them. 
image
image

**Comment by ridz1208** [comment]
@spell00 can you make sure you dont have the accrooss_all_sites permission or the admin permission when testing ?

**Comment by spell00** [comment]
@ridz1208 I did not have these permissions when testing. Not selecting anything in the permissions of the user, I saw nothing, like this:
image

Only selecting the permission for `data_entry` and 2 sites, I had this:
image

**Comment by spell00** [comment]
@racostas I am having another problem now though. 
I just refreshed raisinbread, because I was having an issue to access the module `user_accounts` (#6893), which solved that problem, but now I get a `HTTP ERROR 500` on the login page. I don't have this problem on `aces/main`, but I did have the same problem with another of my PRs and rebasing it solved the problem. 

Here is the apache error log:
```
[Tue Aug 11 13:54:06.024180 2020] [php7:notice] [pid 17035] [client 192.168.122.1:53362] PHP Fatal error:  Uncaught LorisNoSuchModuleException: No such module: dqt in /var/www/loris/php/libraries/Module.class.inc:118\nStack trace:\n#0 /var/www/loris/src/LorisInstance.php(79): Module::factory()\n#1 /var/www/loris/src/LorisInstance.php(111): LORIS\\LorisInstance->getActiveModules()\n#2 /var/www/loris/src/Router/BaseRouter.php(97): LORIS\\LorisInstance->hasModule()\n#3 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#4 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#5 /var/www/loris/htdocs/index.php(48): LORIS\\Middleware\\ContentLength->process()\n#6 {main}\n  thrown in /var/www/loris/php/libraries/Module.class.inc on line 118
[Tue Aug 11 13:54:15.981120 2020] [php7:notice] [pid 17036] [client 192.168.122.1:53366] PHP Fatal error:  Uncaught LorisNoSuchModuleException: No such module: dqt in /var/www/loris/php/libraries/Module.class.inc:118\nStack trace:\n#0 /var/www/loris/src/LorisInstance.php(79): Module::factory()\n#1 /var/www/loris/src/LorisInstance.php(111): LORIS\\LorisInstance->getActiveModules()\n#2 /var/www/loris/src/Router/BaseRouter.php(97): LORIS\\LorisInstance->hasModule()\n#3 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#4 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#5 /var/www/loris/htdocs/index.php(48): LORIS\\Middleware\\ContentLength->process()\n#6 {main}\n  thrown in /var/www/loris/php/libraries/Module.class.inc on line 118
```

**Comment by driusan** [comment]
Disable the "dqt" module in the module manager if you're on a branch that doesn't include it.

**Review by ridz1208 — DISMISSED** [review]
please add content to the CHANGELOG file

**Comment by spell00** [comment]
It is working as expected for total recruitment per site and recruitement per site in Study Progression:

racostas_dashboard

But I can't see the curves for Scan sessions per site (I haven't have this problem with any other branches). I'm also wondering if it is the intention to let the user see the Overall Recruitment of all sites, not just the ones the user is affiliated with?

racostas_dashboard2

here is the error_log:

`[Mon Aug 17 19:14:37.159918 2020] [php7:notice] [pid 19577] [client 192.168.122.1:46252] Could not execute SELECT s.CenterID,\n                CONCAT(MONTH(pf.Value), '-', YEAR(pf.Value)) as datelabel,\n                COUNT(distinct s.ID) as count\n            FROM files f\n            LEFT JOIN parameter_file pf USING (FileID)\n            LEFT JOIN session s ON (s.ID=f.SessionID)\n            JOIN parameter_type pt USING (ParameterTypeID)\n            WHERE pt.Name='acquisition_date'\n            GROUP BY MONTH(pf.Value), YEAR(pf.Value), s.CenterID\n            ORDER BY YEAR(pf.Value), MONTH(pf.Value), s.CenterID. Stack trace#0 /var/www/loris/php/libraries/Database.class.inc(747): Database->execute(Object(PDOStatement), Array)\n#1 /var/www/loris/modules/statistics/php/charts.class.inc(210): Database->pselect('SELECT s.Center...', Array)\n#2 /var/www/loris/modules/statistics/php/charts.class.inc(93): LORIS\\statistics\\Charts->_handleScansByMonth()\n#3 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(233): LORIS\\statistics\\Charts->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#4 /var/www/loris/src/Middleware/PageDecorationMiddleware.php(56): LORIS\\Middleware\\UserPageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Charts))\n#5 /var/www/loris/php/libraries/NDB_Page.class.inc(696): LORIS\\Middleware\\PageDecorationMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Charts))\n#6 /var/www/loris/modules/statistics/php/charts.class.inc(60): NDB_Page->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Charts))\n#7 /var/www/loris/php/libraries/Module.class.inc(412): LORIS\\statistics\\Charts->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Charts))\n#8 /var/www/loris/src/Middleware/ResponseGenerator.php(50): Module->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#9 /var/www/loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Module))\n#10 /var/www/loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\statistics\\Module))\n#11 /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php(34): LORIS\\Router\\ModuleRouter->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#12 /var/www/loris/src/Router/BaseRouter.php(112): LORIS\\Middleware\\ExceptionHandlingMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\ModuleRouter))\n#13 /var/www/loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#14 /var/www/loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#15 /var/www/loris/htdocs/index.php(48): LORIS\\Middleware\\ContentLength->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter))\n#16 {main}, referer: https://spelletier-dev.loris.ca/?logout=true
`

**Comment by racostas** [comment]
Hi @spell00  , glad to see you were able to test it. The `Study Progression -> Scan sessions per site` seems to be working fine on my end. If you could please make sure if any kind of merge was done the proper changes were keep?

Regarding the `Overall Recruitment` right now this target is globally defined in the configuration module is not yet conceived by sites basis. This could be a future feature (possible requiring some discussion due to possible implications for already in production systems). I would said you should create an issue for this one and possible bring it to discussion in a LORIS meeting to some getfeed back from the whole team. If you could please create an issue also for the` Recruitment -> Per Project view` which could be per project permissions restricted as well? Thanks.

**Comment by spell00** [comment]
My study progression -> scan sessions per site is now also displaying only the curves from the 2 sites my user has access to :)

**Comment by spell00** [comment]
My study progression -> scan sessions per site is now also displaying only the curves from the 2 sites my user has access to :)

**Comment by pierre-p-s** [comment]
When I have the DCC site affiliation, I cannot see the breakdown of the site. I need to have the permission "Across all sites access candidate profiles".

Screen Shot 2020-11-26 at 4 30 11 PM
Screen Shot 2020-11-26 at 4 22 07 PM

Also when Having the permission "Across all sites access candidate profiles", I can only see the sites I have an affiliation with. Shouldn't we be able to see all users thus all sites when we have this permission? If not please disregard this comment but I think it's worth discussing.

**Comment by ridz1208** [comment]
@pierre-p-s @racostas can you make sure to bring this up next loris meeting ?

**Pull request closed without merging**
