### PR TITLE
[JSX] Removed redundant hasError prop from SelectElement in Form.js

### PR DESCRIPTION
**Pull request by HenriRabalais**
Since the SelectElement has an `errorMessage` prop, this makes the `hasError` prop redundant. If an error message is passed to the SelectElement, this implies that the SelectElement has an error, therefore displaying the `errorMessage`.

Refer to the TextboxElement for a similar paradigm: #3419

### CODE REVIEW

**Comment by driusan** [comment]
I understand for issues, but what does "Beginner Friendly" mean for a PR?

**Comment by HenriRabalais** [comment]
@driusan I can't seem to find documentation for the new label, but I interpreted it as easy to review and test.

@davidblader makes sense, will do.

**Comment by johnsaigle** [comment]
@driusan I agree that at first I was confused but I think it makes sense to invite the world into our review/test process if they want to join. Since this PR is just a few lines it seems easy to review and test so I think we could maybe use the `Beginner Friendly` label that way 😄

**Comment by HenriRabalais** [comment]
This PR `needs work` before being reviewed and tested.

**Comment by HenriRabalais** [comment]
Deprecated reactified modules need major refactoring before being able to implement this change.

**Pull request closed without merging**
