### PR TITLE
[GenomicBrowser] Readme missing sections added 

### LINKED ISSUE #6389: [Genomic Browser]  README has incomplete sections
The README also has incomplete sections that need to be fleshed out since #5827 was merged

_Originally posted by @driusan in https://github.com/aces/Loris/issues/4753#issuecomment-571168909_

### PR DESCRIPTION
**Pull request by christinerogers**
Resolves #6389 

This PR adds content for the Scope and Intended users section, which have been empty since added in #5827

### CODE REVIEW

**Comment by christinerogers** [comment]
requesting @johnsaigle review  - see last item under Configuration-  the spaces in markdown paths seem to make these unstable for github linking.  See any solutions?

**Comment by johnsaigle** [comment]
@christinerogers Yeah internal GitHub linking seems to conflict with ReadTheDocs linking. One needs spaces and the other needs URL-encoded spaces (`%20`) to work. We should probably just remove the spaces from the file names at some point. It will be a fairly quick clean up when we do do it.

**Comment by christinerogers** [comment]
Thanks for clarifying @johnsaigle  -- i'll add a ticket.

**Comment by christinerogers** [comment]
@johnsaigle Hmmm... if all headers within a document are handled similarly, this may get awkward.

**Pull request merged**
