### PR TITLE
[instrument_builder] add missing Blank Line format into linst

### PR DESCRIPTION
**Pull request by kongtiaowang**
to solve:#4604
to test: insert a blank line in a linst file, and load it.

### CODE REVIEW

**Comment by ridz1208** [comment]
@kongtiaowang did you mean to send this to the 21.0-release branch

**Comment by driusan** [comment]
@ridz1208 no. He had sent another PR to the release branch and I said it shouldn't go into the release branch at this point since it's changing the linst spec, not a bug. (I don't have the PR # handy..)

**Comment by ridz1208** [comment]
@driusan okai thx ill remove the flags

**Comment by driusan** [comment]
Oh, the other PR is the one autolinked above.. #4703

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/5616 duplicate

**Pull request closed without merging**
