### PR TITLE
[User accounts] Fix edit user layout

### LINKED ISSUE #7187: [user_accounts] Generate New Password checkbox on edit_user page incorrectly placed
On the user accounts edit user page, the password checkbox looks like this for me on the main branch:

Screen Shot 2563-12-11 at 09 33 56

Firefox 83.0 on MacOS, window size 1029x667. I can't verify the release branch since it doesn't support PHP8, but this is *not* happening on demo or CCNA, so it's a recent bug.

### PR DESCRIPTION
**Pull request by laemtl**
* Resolves #7187

### CODE REVIEW

**Comment by maltheism** [comment]
@laemtl your phpstorm likely is reformatting the code when saving. That's a useful feature but makes reviewing more difficult. I personally don't mind but some people do.

You can turn that feature off if you want [(see here)](https://stackoverflow.com/questions/2977324/disable-reformatting-code-when-saving-files). There's still the option to reformat the code by menu Code->Reformat Code.

**Review by maltheism — APPROVED** [review]

**Comment by laemtl** [comment]
@maltheism Thanks for the tip!

**Review by driusan — CHANGES_REQUESTED** [review]
Can you please remove all the unrelated whitespace changes in main.css?

**Comment by laemtl** [comment]
The css file was a mess, so I passed it to a beautifier. I can migrate the change to another PR, but I'm scared it would be a lot of conflicts/rebase.

**Comment by laemtl** [comment]
@driusan Ready.

**Comment by driusan** [comment]
@maltheism Can you re-test?

**Comment by laemtl** [comment]
@maltheism Do you have time to review?

**Comment by maltheism** [comment]
Hi @laemtl @driusan, passed manual testing on firefox and chrome.

**Pull request merged**
