### PR TITLE
[Installer] can't save db admin user into confilg.xml

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes
save db admin user into confilg.xml.

#### Link(s) to related issue(s)

https://github.com/aces/Loris/issues/7096

### CODE REVIEW

**Comment by kongtiaowang** [comment]
restart git actions

**Comment by driusan** [comment]
Shouldn't this be going to the 23.0-release branch if it's tagged 23.0-testing?

**Comment by driusan** [comment]
The template `smarty/templates/install.tpl` needs to be changed if we save this value. The install process explicitly says that it will not save the admin username/password.

**Review by driusan — CHANGES_REQUESTED** [review]
see previous comment

**Comment by kongtiaowang** [comment]
as @driusan said, The install process explicitly says that it will not save the admin username/password. We can manually save the admin user in the config file. I will close this PR.

**Pull request closed without merging**
