### PR TITLE
[instrument_builder] Loading existing instrument corrupts Date element

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

When loading an existing instrument and resaving the linst into a new file, the Date element's status field is lost and "undefined" is concatenated to the end of the date element line. This PR fixes the foregoing problem.

#### Testing instructions (if applicable)

1. Go to 'Instrument Builder module', Build tab and build an instrument with date elements
2. Click on 'Save' tab and save the instrument.
3. Read the linst file and see the output.
4. Refresh the instrument builder, and go to the 'Load' tab. Load the instrument linst file that you just created.
5. You can add extra fields to the build if you like, but without editing the date fields, resave the instrument.
6. Read the linst file and notice no changes made to the otherwise untouched file.

#### Link(s) to related issue(s)

* Resolves #6805

### CODE REVIEW

**Comment by driusan** [comment]
This should be going to 23.0-release

**Comment by maltheism** [comment]
@driusan @ridz1208 see https://github.com/aces/Loris/pull/6863

**Comment by zaliqarosli** [comment]
@maltheism @driusan @ridz1208 why are there 2 PRs that are the same? which one should be closed / the one I should be reviewing and testing?

**Comment by ridz1208** [comment]
Closing in favour of #6863

**Pull request closed without merging**
