### PR TITLE
Remove PHPMD and test php8

### PR DESCRIPTION
**Pull request by driusan**
This removes phpmd from the `make checkstatic` target and
no longer uses it in LORIS. It crashes with PHP8, preventing
us from testing/developing with the latest version of PHP over
a month after its release.

This removes it from the checkstatic pipeline and adds php8
to our continuous integration. It should have no effect on LORIS
itself.

### CODE REVIEW

**Comment by driusan** [comment]
@ridz1208 can you review once it passes Travis?

**Comment by driusan** [comment]
not sure what's going on with GitHub Actions.. I'm getting the proper error message with php8 when I test a bad username/password locally.

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/7273
This PR may solve this issue.

**Comment by driusan** [comment]
@ridz1208 @kongtiaowang  I went back to 7.3 and 7.4 for this PR to remove phpmd so at least I can run locally. We can add 8 to our CI in a different PR.

**Review by kongtiaowang — APPROVED** [review]
LGTM

**Pull request merged**
