### PR TITLE
[Document Repository] Fixing bug in pathing

### PR DESCRIPTION
**Pull request by Jkat**
### Brief summary of changes

Got rid of `$fullPath` usage. Code was checking for a directory named by the file, creating a directory named by the file, and uploading the file inside this new directory. 

### This resolves issue...

Fixes uploading and downloading files in Document Repository

### To test this change...

- [ ] upload and download a file

### CODE REVIEW

**Comment by driusan** [comment]
Is this supposed to fix #4462?

**Comment by Jkat** [comment]
@driusan I think my PR covers a bit more but yes it should fix #4462 completely and we can close the issue after merging

**Comment by zaliqarosli** [comment]
will approve after rebase

**Comment by johnsaigle** [comment]
Tagging this with the 21 release because the fix is basically complete and this problem shouldn't be carried forward into v21.

**Comment by zaliqarosli** [comment]
@johnsaigle is there a github issue reported from 21.0.0 testing relating to this? i'm going to rebase and change this branch

**Comment by ridz1208** [comment]
Blocked to not conflict with the reactification of the module

**Comment by driusan** [comment]
The document repo was almost entirely rewritten in #3971 (which unsurprisingly is causing conflicts).. is this still an issue? If so this PR needs to be rebased (or probably more easily just redone on the latest branch.)

**Comment by zaliqarosli** [comment]
i will fix this PR!

**Comment by zaliqarosli** [comment]
@johnsaigle please have a look at this guy if you have time!

**Comment by johnsaigle** [comment]
Looks fine and passed manual tests for uploading; the back-end now properly puts the file where it should go.

Downloading is still broken however but I think the cause is different. IMO this PR should be merged and further work will be done after to figure out what's going wrong.

**Comment by zaliqarosli** [comment]
@johnsaigle yepp, the broken downloading is a separate issue that isn't taken care of in this PR. please hit approve if all good!

**Pull request merged**
