### PR TITLE
API: Update candidate and visit creation message for multisite users (re-open of PR2838)

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
This pull request informs the users that have a multi-site affiliation that they can not create candidates or visits with this version of the API, and that this will become possible in the next API release.

In Reference to Redmine 12020 (item 11 in the list)

This is partially based off of this pull request (which was closed):
https://github.com/aces/Loris/pull/2838

Update only v0.0.2, as v0.0.1 will eventually be removed (#2882)

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this was failing travis a lot in this pull request #2838, so it might here as well!

**Comment by kongtiaowang** [comment]
@MounaSafiHarab 
It failed because of "phpcs" , you need to fix it manually.
FILE: /home/travis/build/aces/Loris/htdocs/api/v0.0.2/Candidates.php
----------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
----------------------------------------------------------------------
 188 | ERROR | Doc comment for parameter "$centerID" missing
 191 | ERROR | Doc comment for parameter $DoB does not match actual
     |       | variable name $centerID
 192 | ERROR | Doc comment for parameter $edc does not match actual
     |       | variable name $DoB
 193 | ERROR | Doc comment for parameter $gender does not match
     |       | actual variable name $edc
 194 | ERROR | Doc comment for parameter $PSCID does not match actual
     |       | variable name $gender
----------------------------------------------------------------------

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
thanks! this was something I forgot to do, but I was anticipating all the Travis failures that @AnyhowStep was initially getting with his pull request (#2838)... anyway we will see once this commit goes through Travis.

**Comment by kongtiaowang** [comment]
@MounaSafiHarab 
When I did a post to create one new candidate, Got 501
screen shot 2017-06-14 at 1 52 11 pm

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this is the correct message if you are logged on as a user with more than one site affiliation.

**Comment by kongtiaowang** [comment]
@MounaSafiHarab 
I test with one user only have site permission. I got 401
screen shot 2017-06-16 at 12 58 08 pm

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

I assume after your second last comment of the 401 error, things worked because you added the passed manual test tag? please confirm!

**Comment by driusan** [comment]
What's the Caveat For Existing projects tag for? I don't think this changes things for existing projects other than making it a little more robust, does it?

(I'm mostly asking so that we know what needs to go in the release notes..)

**Comment by MounaSafiHarab** [comment]
@driusan 

I just added it so that projects know that users with more than one site will not be able to create candidates from the API in its current version (which is what the message in the changes of this pull request will tell them anyway). Perhaps in the release notes, when alluding to the users at multi sites feature, adding a little note about the API is appropriate I think.
But feel free to remove the tag if you think it is unnecessary.

**Pull request merged**
