### PR TITLE
Making Install Script more modular

### PR DESCRIPTION
**Pull request by Jkat**
Implementing prompts for steps within the Install Script

### CODE REVIEW

**Comment by tedstrauss** [comment]
`
Enter project name: jkat
What is the database name? jkat
Database host? localhost                               
What MySQL user will Loris connect as? loris_user
What is the password for MySQL user 'loris_user'? 
Re-enter the password to check for accuracy: 
Enter the front-end Loris 'admin' user's password: 
Re-enter the password to check for accuracy: 
Existing root MySQL username: root
MySQL password for user 'root': 
Re-enter the password to check for accuracy: 
./install.sh: line 310: syntax error near unexpected token `)'
./install.sh: line 310: `        [Nn]* )'
`

**Comment by tedstrauss** [comment]
BUG REPORT
Enter project name: jkat
What is the database name? jkat
Database host? localhost                               
What MySQL user will Loris connect as? loris_user
What is the password for MySQL user 'loris_user'? 
Re-enter the password to check for accuracy: 
Enter the front-end Loris 'admin' user's password: 
Re-enter the password to check for accuracy: 
Existing root MySQL username: root
MySQL password for user 'root': 
Re-enter the password to check for accuracy: 
./install.sh: line 310: syntax error near unexpected token `)'
./install.sh: line 310: `        [Nn]* )'

**Comment by Jkat** [comment]
Thanks Ted!

So I think a test should be written for this script in the near future and for this pull request to be delayed until later.

**Comment by tedstrauss** [comment]
That's ok by me. i can continue testing it as you debug it.

**Pull request merged**
