### PR TITLE
[Imaging Browser] Headers table reformat

### PR DESCRIPTION
**Pull request by davidblader**
originally intended to fix bug where headers table in imaging browser would not close (https://redmine.cbrain.mcgill.ca/issues/12685)

adding DOM nodes via jQuery Dynamic Table screws everything up within the React context
i am assuming the DynamicTable is necessary given the layout of the table, so i edited the table to be just 2 columns wide
Before:
image
After:
image

I can reorder the rows any way that is preferred

### CODE REVIEW

**Comment by driusan** [comment]
Added blocked tag because this is a fairly major UI change that needs the decision of the imaging specialists

**Comment by MounaSafiHarab** [comment]
@driusan 
already added to the Imaging meeting. But this is a bugfix (Redmine 12685) and it should stay in 17.1 (the implementation should changed, if feasible, to not change the UI, but I believe the bug should be fixed in this release because it was introduced in 17.1)

**Comment by MounaSafiHarab** [comment]
Discussed at the Imaging meeting, @davidblader to look at making the changes without the table column changes (from 2 to 1) and to confirm that the recommended changes by @driusan as a potential fix to the problem are fine by @jstirling91.

Moving to author need to incorporate changes as a result of the above

**Comment by davidblader** [comment]
format unchanged version in #2942

**Comment by MounaSafiHarab** [comment]
@davidblader 

so can this be closed now?

**Pull request closed without merging**
