### PR TITLE
[SQL] Removed mri_acquisition_dates table from the database and the LORIS code

### PR DESCRIPTION
**Pull request by cmadjar**
## Brief summary of changes

This PR removes the `mri_acquisition_dates` table from the database as this table does not necessarily store the correct acquisition date. Instead, replaced all the queries to look for the minimal date present in the `parameter_file` table which is more robust than what was stored in `mri_acquisition_dates`.

Note: the decision to remove this table was taken during an imaging meeting in 2017 and confirmed at an other imaging meeting in 2019. 

Link to the MRI PR: https://github.com/aces/Loris-MRI/pull/463

#### Testing instructions (if applicable)

1. Run the SQL patch `SQL/New_patches/2019-07-17_remove_mri_acquisition_dates_table.sql`
2. Make sure the dashboard is loading and plotting the correct graph for the MRI acquisitions
3. Make sure the imaging browser is loading and that the First Acquisition date properly populated

#### Links to related tickets (GitHub, Redmine, ...)

* https://redmine.cbrain.mcgill.ca/issues/6040

### CODE REVIEW

**Comment by cmadjar** [comment]
@driusan Done :)

**Comment by johnsaigle** [comment]
```
> ./test/run-php-linter.sh
FILE: ...aces/Loris/modules/imaging_browser/php/imaging_browser.class.inc
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 236 | WARNING | Line exceeds 85 characters; contains 88 characters
----------------------------------------------------------------------
```

Small code change needed to pass Travis

**Comment by cmadjar** [comment]
@johnsaigle Thank you for the copy of the Travis error! It was very handy to not have to go through the whole log ;). 

Should be fixed now and Travis will hopefully be happy this time!

**Comment by cmadjar** [comment]
@coreyAbout It should be fixed now. I also fixed Travis (hopefully)

**Comment by coreyAbout** [comment]
Great! It works! @cmadjar

**Pull request merged**
