### PR TITLE
[Access Profile (Beta)] remove Minimizing boxes

### LINKED ISSUE #7536: [Access Profile (Beta)] Minimizing boxes & inlcusion of 'Action' Items on 'Candidate's dashboard'
When accessing a candidate via the 'Access Profile (Beta)' route, the following improvements can be implemented to the 'Candidate's dashboard':

- When trying to minimize to hide a given card or box, the content will be hidden, but the card/box will not minimize.

Screen Shot 2021-08-09 at 4 04 13 PM

- Missing the 'Actions' button for 'Create Timepoint', 'Candidate Info' and 'View Imaging Datasets'. The latter can be accessed via the images 'card', but the other two actions can't and the user has to navigate to the standard 'Candidate's Profile' to do this, which is impractical.

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Past discussion came to conclusion of removing minimizing from cards displayed at candidate_profile.

#### Testing instructions (if applicable)

1. Checkout PR
2. Visit Access Profile (Beta)
3. Visit a candidate and the cards should not be able to be minimized.

### CODE REVIEW

**Comment by kongtiaowang** [comment]
This PR is temporary solution for the issue [Access Profile (Beta)] Minimizing boxes & inlcusion of 'Action' Items on 'Candidate's dashboard' ]

**Review by kongtiaowang — APPROVED** [review]
LGTM

**Comment by driusan** [comment]
What's the linked issue that this resolves?

**Comment by maltheism** [comment]
@driusan https://github.com/aces/Loris/issues/7536

**Comment by driusan** [comment]
thanks

**Pull request merged**
