### PR TITLE
[media] re-added accidentally removed declaration

### PR DESCRIPTION
**Pull request by ridz1208**
This pull request re-inserts into the code the instantiation of the FileDownload notification object. see link below to PR that removed it

### CODE REVIEW

**Comment by driusan** [comment]
How did they get deleted in the first place on that line?

Git shouldn't be removing lines that weren't touched on the branch.. was there a conflict that was incorrectly resolved?

**Comment by ridz1208** [comment]
@driusan conflict incorrectly resolved

**Comment by driusan** [comment]
It should still be tested. The code has changed since it was tested in the other PR, and it's possible that there's a semantic difference, or the line was changed, etc.

**Comment by ridz1208** [comment]
@davidblader can you make sure file downloads are not broken and notification gets triggered ?

**Pull request merged**
