### PR TITLE
2019 10 09 wiki to minor

### PR DESCRIPTION
**Pull request by ridz1208**
## Brief summary of changes
Bringing the new wiki to the minor branched to be progressively developed in beta mode until it completely replaces the WIKI

### CODE REVIEW

**Comment by johnsaigle** [comment]
@driusan Could you take a look at this? Merging this will allow us to start building the ReadTheDocs wiki on the minor branch.

**Comment by driusan** [comment]
@ridz1208 is this ready to be merged?

**Comment by ridz1208** [comment]
@driusan yeah

**Comment by driusan** [comment]
@ridz1208 Should the WIKI_revamp branch be deleted now?

**Comment by ridz1208** [comment]
@driusan not yet, I need to rebase my PRs

**Pull request merged**
