### PR TITLE
[New Profile] Removed Panel From New Profile Module

### PR DESCRIPTION
**Pull request by HenriRabalais**
Addressed Issue #5550 by removing the Panel around the New Profile Form and replacing it with a Fieldset.

### CODE REVIEW

**Comment by johnsaigle** [comment]
Travis is failing. It's possible you'll need to update the integration test if it's checking for some HTML element that was in that panel.

**Comment by ridz1208** [comment]
@HenriRabalais please fix

**Comment by driusan** [comment]
It's still failing because of phpcs

```
FILE: /home/travis/build/aces/Loris/modules/new_profile/test/new_profileTest.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 57 | WARNING | Line exceeds 85 characters; contains 86 characters
 64 | WARNING | Line exceeds 85 characters; contains 88 characters
--------------------------------------------------------------------------------
```

**Comment by ridz1208** [comment]
@driusan merge me

**Pull request merged**
