### PR TITLE
Add label to Checkbox

### LINKED ISSUE #6218: [Instrument List] Mysterious checkboxes require documentation
**Describe the bug**
See the image attached: 
image

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to instrument list of any candidate
2. Click on "double data entry"
3. Look at the left top corner

**What did you expect to happen?**
There should be a text to explain what those buttons are

**Browser Environment (please complete the following information):**
- Chrome

**Server Environment (if known):**
- LORIS Version: 23-release

### PR DESCRIPTION
**Pull request by haoweiqiu**
## Brief summary of changes
I added a label before the 2 checkboxes since I found that the checkboxes seem to be used for delete confirmation as shown in `php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc`. 

Haowei Qiu, GSOC Applicant
CC @christinerogers 
#### Link(s) to related issue(s)

* Resolves #6218  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by christinerogers** [comment]
Hi @haoweiqiu - Could you post a screenshot (here in a GitHub comment) of what this change looks like in the front-end? 
Thanks,  Christine

**Comment by haoweiqiu** [comment]
@christinerogers Thank you very much for your reply! I have been trying to find the Instrument Status Control Panel, however, I am not entirely sure where I could find it. Could you help me with this problem? Thanks!

**Comment by lingma** [comment]
The fix is not good enough, too much text there, it is better to have a help text, otherwise this is too cumbersome. Another way to do is that the concept of the 2 checkbox has to be modified to be simple.

**Comment by haoweiqiu** [comment]
@lingma Thank you very much for your comment! I think the checkboxes could be replaced by a pop-up window (for example Sweetalert) to confirm deletion. I could look into this.

**Comment by christinerogers** [comment]
Thanks @haoweiqiu ,  and thanks @lingma for your feedback. 
We are paused on GSOC contributions for now - I'll resolve this with @haoweiqiu shortly.

**Comment by driusan** [comment]
I think replacing those buttons with a modal window is a good idea.

Those checkboxes were added (long) before we were using swal in LORIS.

**Comment by pierre-p-s** [comment]
From @driusan, using a modal window would be best.

``` 
<script> 
    function swalFunction() {
    Swal({
      title: 'Please confirm deletion',
      text: 'The instrument data will be deleted',
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete the data'
    }).then((result) => {
  if (result.value) {
    Swal(
      'Deleted!',
      'The instrument data has been deleted.',
      'success'
    )
  }
});
  }
</script> 
```

Calling this function if the button is clicked should make a modal window appear asking for confirmation.
I am having issues setting up my VM to 23.0 from CCNA 21 version so I cannot test this for now

**Comment by haoweiqiu** [comment]
@pierre-p-s Thank you very much for your reply! The code looks fine to me. However, I think we are turning to use SweetAlert2 now. Here's my tweak on your code.
```
<script>
    function swalFunction() {
    Swal.fire({
      title: 'Please confirm deletion',
      text: 'The instrument data will be deleted',
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete the data'
    }).then((result) => {
  if (result.value) {
    Swal.fire(
      'Deleted!',
      'The instrument data has been deleted.',
      'success'
    )
  }
});
  }
</script>
 ```

**Comment by christinerogers** [comment]
Thanks very much @haowieqiu - we appreciate the options for this solution and catching the swal2 issue. 

I'm closing this PR only because @pierre-p-s will be implementing the modal in a separate PR to resolve #6218.

**Pull request closed without merging**
