### PR TITLE
New integration test for session time out while logging in

### PR DESCRIPTION
**Pull request by mohini-tripathi**
## Brief summary of changes

- [ ] Have you updated related documentation?

#### Testing instructions (if applicable)

1.

#### Link(s) to related issue(s)

* Resolves #  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by christinerogers** [comment]
Hi @mohini-tripathi  - Thanks for this. 
I see a CSS change from the Dicom-Archive module [see this](https://github.com/aces/Loris/pull/6194/files#diff-415f8812ba8451ff41d354d2b318496b)
- could you remove this from your PR? 

cc @kongtiaowang  - could you take a look at the integration test in this PR ?  
**Shen**, Does it look ok?

**Comment by johnsaigle** [comment]
Would you be able to fill out the pull request template to let us know what you're looking to improve?

It looks to me that your timeout test will always return true and will always add 65 seconds to our test suite. I'm not clear on what your intention is with adding this test.

If it's still a work in progress, please add the "Needs Work" label.

**Comment by christinerogers** [comment]
@mohini-tripathi  - per John's comment to update the PR description header - Thank you in advance for updating this, and please also mention in the PR description that you are applying for **GSOC** .

**Comment by mohini-tripathi** [comment]
Hi John,
I will go through the pull request template. My aim was to add an
integration test for the timeout session, I'll make changes to my code, my
work is still in progress I will add a label to it. I'll update the PR
after modifying it.

Thank You.

**Comment by mohini-tripathi** [comment]
@christine.rogers@mcgill.ca <christine.rogers@mcgill.ca> - I will remove
the CSS change and update it, I changed it while I was experimenting with
code-base and will mention that I'm applying for GSOC in my further PRs.

Thank You.

**Pull request closed without merging**
