### PR TITLE
[docs] Create generic test plan for all Modules

### LINKED ISSUE #7055: [docs] Create generic test plan for all Modules
Per discussion in the Loris meeting Sep.22: 

Create a generic test plan that can be executed manually on any module. 
(These steps are also covered by automated testing.)

Copy/adapt from [Imaging QC test plan](https://github.com/aces/Loris/blob/main/modules/imaging_qc/test/TestPlan.md) 
 Points 3-11   

After this is committed and we're done with test plan updates for this cycle, there will be a followup issue to link to this generic test plan from the top of every module test plan 

Derived from @CamilleBeau 's issue #6977

### PR DESCRIPTION
**Pull request by haoweiqiu**
## Brief summary of changes

- [x] Have you updated related documentation?

#### Link(s) to related issue(s)

* Resolves #7055  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by laemtl** [comment]
Thanks @haoweiqiu! Can you add the Documentation label to your PR?

**Review by laemtl — APPROVED** [review]

**Review by maltheism — APPROVED** [review]

**Review by driusan — DISMISSED** [review]
When this was discussed in the LORIS meeting it was agreed that the existing test plans should be updated to directly instruct the tester to refer to this document, otherwise it risks being missed. Can you update the other test plans to add a step instructing them to also follow this test plan for the module?

I don't mind if there's duplication for now, we can remove the duplications when people are going through the test plans for the next release, as long as the modules where it applies are updated to explicitly tell people to follow this too.

**Comment by haoweiqiu** [comment]
@driusan Sure! I'll look into this.

**Comment by christinerogers** [comment]
@driusan this looks ready to merge.  Do you want people do this for the 24 release @ridz1208 ? 

@haoweiqiu did not re-request your review but it's been ready for a while.

**Review by driusan — CHANGES_REQUESTED** [review]
My previous review was never addressed.

When this was discussed in the LORIS meeting it was agreed that the existing test plans should be updated to directly instruct the tester to refer to this document, otherwise it risks being missed. Can you update the other test plans to add a step instructing them to also follow this test plan for the module?

I don't mind if there's duplication for now, we can remove the duplications when people are going through the test plans for the next release, as long as the modules where it applies are updated to explicitly tell people to follow this too.

**Comment by christinerogers** [comment]
@driusan I think the best approach for this PR is probably to ask everyone to update test plans when we next do a round of testing.  we can close this until then, if that's better.

**Pull request closed without merging**
