### PR TITLE
[php/libraries/UserPermissions.class.inc] can't get longname

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes
if set one module as "No"  in the module_manager, user account module can't edit the user ( 500 error)
module[1] = y
module[2] = n
module[3] = y
when one user has module 2 permission, it will call module[2]->getLongName function. 
#### Testing instructions (if applicable)

1. set one module as "No" in module_manager.
2. create a new user or edit a user without 500 error.

### CODE REVIEW

**Comment by driusan** [comment]
why is the query including disabled modules? The line above the loop is `$modules = \Module::getActiveModulesIndexed($DB);` .. it seems like it would be better to update the query so that `$result` doesn't include disabled modules.

**Comment by kongtiaowang** [comment]
@driusan The query of getActiveModulesIndexed is correct. The issue is that one user has the permissions for one module, and the module is not activated,  although getActiveModulesIndexed is correct , but  "$modules[$perm['moduleID']]" will be null.

**Comment by driusan** [comment]
Yes, because the `$query` variable is incorrectly including inactive modules. Why not fix the query in the method being modified?

**Comment by kongtiaowang** [comment]
@driusan yes, you are right. The query has been fixed. Could you review again?

**Pull request merged**
