### PR TITLE
[Media] Use ES6 class syntax

### PR DESCRIPTION
**Pull request by jacobpenny**
A step toward standardising our components to use ES6 class syntax (like DicomArchive).

### CODE REVIEW

**Comment by driusan** [comment]
Doesn't the Gruntfile.js need to be updated too?

**Comment by jacobpenny** [comment]
Not for this change I believe. The compiling step can remain the same (unless I'm missing something).

**Comment by driusan** [comment]
The compiling step has the two rules: one for transpiling ES5 files, and one for transpiling ES6 files. Shouldn't the ones that are updated to ES6 in this PR move from the ES5 list to the ES6 list?

**Comment by jacobpenny** [comment]
Ah, this isn't an update to ES6 (they already were being compiled as ES6).

**Comment by jacobpenny** [comment]
@driusan rebased

**Comment by alisterdev** [comment]
@jacobpenny Need to be re-rebased :(

**Comment by jacobpenny** [comment]
re-rebased

**Pull request merged**
