### PR TITLE
[User] Remove usage of GROUP_CONCAT 

### LINKED ISSUE #7480: [User] GROUP_CONCAT truncates site names
The `getSiteName()` function in the User class returns a truncated array of site names when a study has many sites. This is due to mysql GROUP_CONCAT that truncates the string to 1024 characters by default. The offending statement is at https://github.com/aces/Loris/blob/main/php/libraries/User.class.inc#L71 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create 103 sites which names length are 10 characters
2. Assign them all to a user.
3. look at the output of `User::getSiteName()` 

**Server Environment (if known):**
- LORIS Version: >=17.01 

Reported by @alfredomp which runs an instance with 500+ sites.

### PR DESCRIPTION
**Pull request by xlecours**
Since group_concat limits the length of the string to 1024 characters by defaults, it becomes problematic for studies that have many sites. 

* Resolves #7480

### CODE REVIEW

**Comment by driusan** [comment]
@ridz1208 maybe you want to review this one?

**Review by ridz1208 — CHANGES_REQUESTED** [review]
Bugfix should be sent to 23.0 (or earlier if need be)

**Comment by xlecours** [comment]
@ridz1208 Correction made.

**Comment by ridz1208** [comment]
@xlecours could you rebase it on 23 ?

**Comment by xlecours** [comment]
https://github.com/aces/Loris/pull/7486

**Pull request closed without merging**
