### PR TITLE
[jsx/DataTable] Revert UI changes made in issuetracker PR

### PR DESCRIPTION
**Pull request by zaliqarosli**
fixes 1 part of https://github.com/aces/Loris/issues/4626

### CODE REVIEW

**Comment by driusan** [comment]
I don't understand this issue or the fix enough to write a commit message for this. Why is this reversion required? Why does the download as CSV feature need to be removed to fix.. something?

**Comment by zaliqarosli** [comment]
the IssueTracker PR had some old DataTable UI code in it that got merged. this PR just replaces that old UI with the new UI that was merged in a previous PR. soo the IssueTracker PR reverted UI changes. this PR reintroduces new UI that got removed

**Comment by zaliqarosli** [comment]
i.e. we had decided to remove the header and footer panels for the datatable

**Comment by driusan** [comment]
So why does the download table as CSV button get removed in the diff for this PR?

**Comment by zaliqarosli** [comment]
so that its only above the table with the rest of the "calls to actions". this change was made in line with talks in UX group regarding call to actions and their placement

**Pull request merged**
