### PR TITLE
Loris 20.3.0 Version + patches + JS transpiling + composer

### LINKED ISSUE #4445: Update 3rd party libraries to patch security vulnerabilties
### Background

LORIS depends on certain 3rd party libraries. Some of these external libraries have known security vulnerabilties:

* Smarty: https://github.com/sbaresearch/advisories/tree/public/2018/SBA-ADV-20180420-01_Smarty_Path_Traversal

* Diactoros: https://framework.zend.com/security/advisory/ZF2018-01

* PHPCS: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.8.1
    * This is already fixed on `major`

### TODO
These should be updated and the new `composer.lock` file should be committed to the next bugfix or minor release.

The vulnerabilities were discovered using https://security.symfony.com/ and its findings are based on the `composer.lock` file on the latest `aces/bugfix` branch.

### PR DESCRIPTION
**Pull request by ridz1208**
This PR prepares the 20.3 release.

Fixes #4445

### CODE REVIEW

**Comment by ridz1208** [comment]
BLOCKED: This PR was issued to the minor branch but is intended to be merged in the yet-to-come `20.3-release` branch after the #4442 gets merged

**Comment by johnsaigle** [comment]
@ridz1208 can you resolve https://github.com/aces/Loris/issues/4445 before this release goes out?

There are some security issues with our 3rd party PHP dependencies.

All that needs to be done is to update them to a newer version in composer and commit the `composer.lock` file.

**Comment by ridz1208** [comment]
@johnsaigle I have no opposition

**Comment by johnsaigle** [comment]
@ridz1208 I can work on it Monday (if no one does it before that)

**Comment by ridz1208** [comment]
@johnsaigle will you be doing it or should I ?

**Comment by johnsaigle** [comment]
@ridz1208 You can if it needs to go out today, otherwise will do tomorrow

**Comment by ridz1208** [comment]
@johnsaigle ran `composer update` and added lock file

**Comment by johnsaigle** [comment]
@ridz1208 I added a change here so that the only updated libraries are the vulnerable ones from #4445

**Comment by maltheism** [comment]
@ridz1208 It would be really nice if #4449 could be included. Having everything updated is my favourite thing in the world.

**Comment by ridz1208** [comment]
That issue seems to be for major. This is a minor branch

**Pull request merged**
