### PR TITLE
[MAYBE MERGE?] Update VERSION file to 17.0.6

### PR DESCRIPTION
**Pull request by johnsaigle**
Update the VERSION file to 17.0.6.

Note: This should not be merged until a 17.0.6 released is ready to be tagged. (There are currently no plans for a 17.0.6.)

### CODE REVIEW

**Comment by driusan** [comment]
Who passed tests on this?

The VERSION this is being changed to is wrong!

**Comment by johnsaigle** [comment]
@driusan This is meant to fix the 17.0.5 release. Should I change it to 17.0.6?

**Comment by driusan** [comment]
The 17.0.5 release is already tagged, 17.0.6 is the next release that this could possibly go into.

But it's not clear that there will be a 17.0.6 release, either, with all resources going into 17.1 right now.

**Comment by johnsaigle** [comment]
This should either be merged with #2948 or closed as that PR currently contains a version file bump.

**Comment by Jkat** [comment]
Oops didn't notice your PR for the version bump, mine can be ignored

**Pull request merged**
