### PR TITLE
[LorisForm] Add readonly capabilities to text elements

### PR DESCRIPTION
**Pull request by ridz1208**
This pull request adds the ability to make text fields readonly. readonly text fields get submitted with the form. disabled does not.

### CODE REVIEW

**Comment by AnyhowStep** [comment]
Duuuude, phpcs

**Comment by jstirling91** [comment]
@ridz1208 Fix the following phpcs errors
```
FILE: /home/travis/build/aces/Loris/php/libraries/NDB_Page.class.inc
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 390 | ERROR | [ ] Doc comment for parameter "$attribs" missing
 395 | ERROR | [ ] Doc comment for parameter $attr does not match
     |       |     actual variable name $attribs
 404 | ERROR | [x] Equals sign not aligned correctly; expected 1
     |       |     space but found 0 spaces
 404 | ERROR | [x] No space found after comma in function call
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

**Comment by ridz1208** [comment]
@jstirling91 phpcs'ed it

**Comment by ridz1208** [comment]
@davidblader please test when possible

simply add the read only attribute to a text field and make sure the field is not editable when it is added but still submitted with the form

**Comment by jstirling91** [comment]
@ridz1208 whats the difference between using readonly and using disabled?

**Comment by ridz1208** [comment]
@jstirling91 readonly fields are still submitted when form is submitted but their values can not be manually changed. i.e. a js could be filling in those fields automatically such as timestamps ...

**Comment by davidblader** [comment]
> @jstirling91 readonly fields are still submitted when form is submitted but their values can not be manually changed. i.e. a js could be filling in those fields automatically such as timestamps ...

so this attribute really only makes sense in the context of there being some JS extension? you're doing something like this for CBSR right?

**Pull request merged**
