### PR TITLE
[RB] Fix BMI scoring code

### PR DESCRIPTION
**Pull request by ridz1208**
## Brief summary of changes
updating scoring code to latest standards

### CODE REVIEW

**Comment by ridz1208** [comment]
@zaliqarosli could you test this at the same time when testing #7818 they are related. The BMI instrument in 7818 tries to run the scoring based on the SQL values but if it is set to `jsondata=true` the SQL table would be empty.

All you need to do is make sure the data loads, calculates and save in the JSON string the proper scores

**Review by zaliqarosli — CHANGES_REQUESTED** [review]
getting the console output error

```
An error occurred while running the scoring
                algorithm of instrument bmi.
```

once again, i'm not able to see anything useful in my apache log

**Comment by ridz1208** [comment]
can you just make sure the .score file is available and executable on your VM ?

**Review by zaliqarosli — APPROVED** [review]
@ridz1208 you're right, i needed to make the file executable. the scoring ran well, and score fields saved to Data column of flag table

**Pull request merged**
