### PR TITLE
[issue_tracker] Fixes An error occurred when loading the form!

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Two small solutions for fixing the "An error occurred when loading the form!" frontend message.

#### Testing instructions (if applicable)

1. Pull PR
2. Test on Rasinbread data.
3. Click an issue from the table column "Issue ID" and no error with PR changes.

### CODE REVIEW

**Comment by johnsaigle** [comment]
Related to #5348

**Comment by maltheism** [comment]
Hey @johnsaigle just to note this PR doesn't fix the array index issue. My PR just solves the problem of not being able to view the issue with a simple fix if you look at my code change. In any case I just wanted to get a fixed out and so I can start working on @leighevans feature request.

**Comment by leighevans** [comment]
@maltheism wrong Leigh! :)  @LeighMac is who you're looking for

**Comment by maltheism** [comment]
Sorry @leighevans and I mean @LeighMac

**Pull request closed without merging**
