### PR TITLE
[dataquery] Fixed broken link for 'deleteAll' and fixed save error on query names that contain spaces

### PR DESCRIPTION
**Pull request by jesscall**
Re-issue of #5379 

### Brief summary of changes
This PR addresses the issues reported in #5364 
1. The `Delete All` link in DQT was broken and not actually deselecting the fields. 
2. You couldn't save a query if it had a space in the name. No error was displayed, it just wouldn't save. The code now replaces any space by underscores. 

#### Testing instructions (if applicable)

1. Head over to DQT. 
2. Add some fields to your query. 
3. Attempt to deselect those fields using the `Delete All` button. 
4. Try saving a query that has spaces in the name. When you refresh, your query should appear. 

#### Links to related tickets (GitHub, Redmine, ...)

* #5364, #5500
* aces/CCNA#3342

### CODE REVIEW

**Comment by cmadjar** [comment]
@johnsaigle Do you have the DQT set up? Is this something you could review/test?

**Comment by johnsaigle** [comment]
@cmadjar I am using @ridz1208 's CouchDB credentials so yes the module loads. I'm not really familiar with it but I can give it a try.

**Comment by maltheism** [comment]
@jesscall I'm not able to manual test this PR because the Load Saved Queries button isn't working for me. I think @cmadjar made an issue about it. The code in your PR does make sense and should probably be sent anyways.

**Comment by johnsaigle** [comment]
@ridz1208 Should this be rebased to 22.0-release?

**Comment by ridz1208** [comment]
@johnsaigle no this is a 21 issue detected while CCNA was testing the upgrade to 21

**Comment by jesscall** [comment]
@maltheism 
`Laod Saved Queries` is not actually a button. If you hover over it, you should see the saved queries, if any exist. 

To test this PR you would:
1. Define fields and filters of your choice.
2. Navigate to `Manage Saved Queries`
3. Click `Save Current Query` button (shown in image)
image

4. A modal window should pop-up asking for a query name. Populate this field with any string of your choice, preferably one with a space in it to test the functionality of this PR. 
image

5. Try refreshing the page. Hopefully everything should behave as normal.

**Comment by maltheism** [comment]
@jesscall I broke the DQT with following your steps.

1) Define Fields-> Instrument-> bmi
2) Define Filter-> (And) demographics-> PSCID = DCC090
3) Manage Saved Queries-> Save Current Query-> Query Name: hooray -> Save Changes
4) Refresh
5) Load Saved Queries ->  hooray
6) Crash!%#!@
7) Console output:
`TypeError: null is not an object (evaluating 'this.props.selectedFields[this.state.selectedCategory]')`

**Comment by maltheism** [comment]
@jesscall found a fix for the crash when loading a saved query.
Modify dataquery/jsx/react.tabs.js replace the <FieldSelector/> component with this code:
```
<FieldSelector
          title='Fields'
          items={this.props.categories}
          onFieldChange={this.props.onFieldChange}
          selectedFields={this.props.selectedFields
            ? this.props.selectedFields
            : {}
          }
          Visits={this.props.Visits}
          fieldVisitSelect={this.props.fieldVisitSelect}
        />
```

**Comment by driusan** [comment]
@maltheism selectedFields is a prop and the default value of the state that it's passed from is `{}`.. how is it getting unset?

**Comment by maltheism** [comment]
@driusan I'm not quite sure yet but if you add a console.log before the component is rendered. You will find it outputting null when loading a saved query and before the module crashes. I would like to find the root cause but thought in the meantime that's a solution.

**Comment by jesscall** [comment]
@maltheism thanks for your help!

@driusan is the fix suggested adequate ?

The DQT code is really messy and I'm not confident enough in my react skills to actually debug this

**Comment by maltheism** [comment]
@jesscall, @driusan  I've debugged more and the line 475 found here:
https://github.com/aces/Loris/blob/bed8d21c64fd641660e57fcb9ae7732110ee43ac/modules/dataquery/jsx/react.app.js#L475
where `selectedFields = fields;` happens to be the problem. You can instead of the foregoing solution in the previous comment, change this line to `selectedFields = fields ? fields : {};`

**Comment by kongtiaowang** [comment]
I have tested this fix on 22.0-release, it works well. We should merge this PR on 22.0-release.

**Comment by driusan** [comment]
@jesscall the second solution (ensuring it gets fixed in the state instead of modifying the prop) sounds good to me. #5673 has the same problem as the first solution.

**Comment by jesscall** [comment]
@driusan @maltheism 

I implemented Alizee's suggestion and tested quickly. It seems to solve the issue of not being able to load queries.

**Comment by driusan** [comment]
@maltheism can you test the latest iteration of this?

**Comment by maltheism** [comment]
@driusan @jesscall everything is working great!

**Pull request merged**
