### PR TITLE
[Issue Tracker] Priority Dropdown Issue 

### PR DESCRIPTION
**Pull request by mohini-tripathi**
## Brief summary of changes

- [x] Have you updated related documentation?
- Made changes in the file priority array to add the 'Low' option in priority dropdown

#### Testing instructions (if applicable)
1. Click on Issue Tracker Tool under Tools in the menu bar
2. On ```https://demo.loris.ca/issue_tracker/``` click on Priority dropdown.

#### Link(s) to related issue(s)

* Resolves #  This fixes https://github.com/aces/Loris/issues/6262
#GSOC Aspirant
CC @christinerogers

### CODE REVIEW

**Comment by ShubhamDhingra96** [comment]
I have already resolved that issue

**Comment by johnsaigle** [comment]
@ShubhamDhingra96 can you link to the fix?

**Comment by christinerogers** [comment]
Thanks @mohini-tripathi for the contribution 👍 
@ShubhamDhingra96 we will go with this fix, thanks for spotting the issue #6262 👍

**Comment by johnsaigle** [comment]
I think this PR is effectively replaced by #6609 @ridz1208

**Comment by ridz1208** [comment]
closed for duplication.#6609 is going to the release branch

Thanks all

**Comment by christinerogers** [comment]
thanks @mohini-tripathi for your contribution here. 
We've committed a similar fix to a branch that is going to be released sooner (and then contributed to master)

**Pull request closed without merging**
