### PR TITLE
Update phpstan

### PR DESCRIPTION
**Pull request by johnsaigle**

### CODE REVIEW

**Comment by xlecours** [comment]
@johnsaigle Was it necessary?

**Comment by johnsaigle** [comment]
It's not necessary for any specific reason but for developer tools I think it makes sense to try to use the more recent available versions. Since this won't affect production LORIS I don't think there's any harm.

**Comment by driusan** [comment]
@johnsaigle this can't be merged because of conflicts, can you rebase?

**Comment by johnsaigle** [comment]
@driusan done!

**Pull request merged**
