### PR TITLE
[DocRepo] Clean up directory content and let filter without folders

### PR DESCRIPTION
**Pull request by zaliqarosli**
## Brief summary of changes

1. Remove extraneous files that actually belong to subdirectories
2. Add global filtering of files only, without directory structure
3. Rename a couple states and functions to be more meaningful

#### Testing instructions (if applicable)

On `22.0-release`, verify:

1.  Files in subcategories are recursively shown in parent categories (read description of this issue https://github.com/aces/Loris/issues/5449 for more clarity)
2. Clicking on 'Global Selection Filter' just takes you to the root directory

On this branch, test:

1. Files exist in their rightful categories and their categories alone.
2. Clicking on 'Filter globally' removes the directory structure and lists all files so that you can filter for all. The directory tree display ( _Root > ...._ ) disappears as well.
3. Unchecking 'Filter globally' will return table to normal folder structure with directory tree display. Filtering whilst in this state will only filter for files within the directory you're in.

#### Links to related tickets (GitHub, Redmine, ...)

* Fixes https://github.com/aces/Loris/issues/5449
* Fixes https://github.com/aces/Loris/issues/4857 (duplicate)

### CODE REVIEW

**Comment by zaliqarosli** [comment]
@jesscall if you're interested!

**Comment by jesscall** [comment]
This is the greatest thing ever

**Comment by driusan** [comment]
Is there a reason the "Filter globally" checkbox is outside of the filters section?

**Comment by zaliqarosli** [comment]
Because it’s not rendered within the FilterableDataTable component. It’s rendered in the Doc Repo index file. I think this makes sense because it’s not a feature needed in other uses of FilterableDataTable. It’s specific to doc repo alone

**Comment by driusan** [comment]
It looks a little out of place to me, but I'm not going to block over it.

**Pull request merged**
