### PR TITLE
[react] Added Material-UI and Redux for Loris and bug fixes

### PR DESCRIPTION
**Pull request by intralizee**
### Brief summary of changes

# This PR adds both the React Framework "Material-UI" and the state container "Redux" into Loris. 

- The PR brings react components based on Material Design by Google. 
- The state container redux for better managing state in components. 
- Updated package.json and fixed bug with react includes. 
- Modified eslint rules.
- Syntax cleanup because of eslint rules.
- Updated broken code by latest react version (refs are bad).
- Moved components in directory jsx/ to jsx/components

### This resolves issue...

- [ ] Redmine? #

- [x] Github? #3965

### To test this change...

- [x] Check out the PR!
sudo rm -rf node_modules
npm install && npm run compile
Visit every module and see if anything is broken.

### CODE REVIEW

**Comment by intralizee** [comment]
Adding the Blocked tag because some react errors sprung up with updating.

**Comment by intralizee** [comment]
The load pane for the instrument builder is the only thing broken right now. Need to fix before removing Blocked label.

**Comment by intralizee** [comment]
Okay, everything should be fixed and ready to be tested for merging.

**Comment by HenriRabalais** [comment]
I suggest closing this PR since there seems to be no one who is maintaining it.

**Comment by driusan** [comment]
Closing as @HenriRabalais suggested (and because @zaliqarosli has already implemented the material design theory in her UI overhaul in other PRs)

**Pull request closed without merging**
