### PR TITLE
[Imaging Browser] Doctors Hate Him!

### PR DESCRIPTION
**Pull request by AnyhowStep**
In reference to 12514,

I speak for everyone when I say that patients should have the right to refuse getting vaxxed.
The needles are sharp and cause autism.

This pull request causes very little change to the system.
But all great things begin with a little change.

### CODE REVIEW

**Comment by johnsaigle** [comment]
@driusan [This line](https://github.com/aces/Loris/pull/2835/files#diff-97a98df45d51244f922738278e8a5a3bR132) makes it seems like the query is a bit more complex than just accepting `outputType` (otherwise I'd agree with your suggestion!)

ie.:
* `processed` means we want all matches that are not `native`
* `native` means we want only `native`
* `skull_mask` means we only want `skull_mask`
Which means `skull_mask` is a subset of `processed`? I'm not familiar with the functionality so I can't really comment.

In any case, the takeaway is **_this fixes the security hole_** so I say -- pull it! ~

**Comment by johnsaigle** [comment]
@AnyhowStep Can you make your PR titles a bit more informative in the future? Don't get me wrong - I appreciate the humor - but it makes it a bit easier to look over PRs. 😅

**Comment by driusan** [comment]
But those are specific types of output type, so just having a `WHERE OutputType=:val` should be sufficient.. but anyways, it's out of scope for this pull request, I'll bring it up with the imaging team.

**Comment by AnyhowStep** [comment]
Yeah, I wanted to clean it up but I didn't want to accidentally introduce anything that Travis might not catch. So, I kept most of it intact =(

**Pull request merged**
