### PR TITLE
Remove references to deleted Reliability module

### LINKED ISSUE #4997: [Stats/reliability] Remove orphan fxn : updateReliabilityTab()
Reliability module was removed with release 21 #4596 

I believe this JS function/file can be removed too.  (May be relevant only to IBIS.)

### LINKED ISSUE #5431: [Test] Remove Reliability tags from test/config.xml
This module was deleted so we don't need this information in that file.

### PR DESCRIPTION
**Pull request by johnsaigle**
Resolves #5431
Resolves #4997

### CODE REVIEW

**Comment by johnsaigle** [comment]
TODO: restart Travis after release prep.

**Comment by ridz1208** [comment]
@johnsaigle I wouldnt mind this one going to 21.0-release

**Comment by ridz1208** [comment]
might have to do the rebase on your VM, too many commits are showing

**Comment by johnsaigle** [comment]
@ridz1208 rebased

**Comment by driusan** [comment]
@ridz1208 why do you want this in a 21 release?

**Comment by christinerogers** [comment]
lol how about a 22 release since it was deleted for 21?  @ridz1208 @driusan

**Pull request merged**
