### PR TITLE
[Utility] Removed unused methods and added notes for future refactoring

### PR DESCRIPTION
**Pull request by AnyhowStep**
Deleted unused methods (checked with `grep` and used Github's search tool).
Added `@note` annotations to keep track of future clean ups.
Made line endings consistent with `LF` convention (we have a `LF` convention, right? guys?)

Less code means less bugs?
(Please pass Travis...)

### CODE REVIEW

**Comment by AnyhowStep** [comment]
I'd like to move some of these (I didn't annotate them all) Database-specific methods over to the `Database` class and the appropriate DAO classes at some point. I'm really trying to remove dependencies to the `Utility` class as much as possible to ease refactoring efforts in future.

**Comment by AnyhowStep** [comment]
The things to grep are,
```
grep -nr 'explodeEncapsulated\|arrayMergeKeepKeys\|ty::flatten\|flattenFull\|getColumnThresholdCount\|getVisitLabelUsingTestName\|getSourcefrom'
```

**Comment by ridz1208** [comment]
@AnyhowStep 
I would not mind seeing this going to 17.2, it can be merge early and thus tested during development
I think we are too late in 17.1 to do this kind of cleanup

and yes my concern is like @johnsaigle expressed some older code/override might be using it even though loris got rid of those.

**Comment by AnyhowStep** [comment]
Changed to 17.2. It isn't super urgent.

**Comment by johnsaigle** [comment]
This will be closed in favour of #2913. The changes of this PR have been merged into it.

**Pull request closed without merging**
