### PR TITLE
Fixing sql query in the statistics

### PR DESCRIPTION
**Pull request by kongtiaowang**

### CODE REVIEW

**Comment by driusan** [comment]
I don't know if this is right. It looks like $where is a (poorly named..) variable that's defined above the lines that are changed, and used to create an OR section but the variable name starts with "WHERE (".. changing it from the variable $where to the SQL keyword WHERE is going to change the behaviour/results of the query.

**Comment by driusan** [comment]
I don't know if this is right. It looks like $where is a (poorly named) variable above the lines that are changed which generates a bunch of OR statements and the value of the variable starts with "WHERE". Changing it from the variable $where to the SQL keyword WHERE will change the results that are returned.

**Comment by kongtiaowang** [comment]
Changing $where to where, because I didn’t find mri_scan_type table be used in FROM statement. If I miss something pls reminder me, Thank you. 
  $where = "WHERE ("  foreach (**$scan_types** as $index=>$scan) { ......

 FROM **mri_parameter_form** m LEFT JOIN flag f ON
                                        (f.CommentID=m.CommentID)
                    LEFT JOIN **session** s ON (s.ID=f.SessionID)
                    LEFT JOIN **files** fi ON (fi.SessionID=f.SessionID)
                    LEFT JOIN **candidate** c ON (c.CandID=s.CandID)

**Comment by driusan** [comment]
It's an awkward way of doing things, but it's using the mri_scan_type table to get a list of scan_types. 

The existing scan_types are expected to have a matching column in the mri_parameter_form instrument. It's not included in the join because it's not used in the table, it's only used to derive the column name.

**Comment by kongtiaowang** [comment]
Thank you. It is very clearly for me. I got it.

**Pull request merged**
