### PR TITLE
[WIKI] Removal of unused files

### PR DESCRIPTION
**Pull request by ridz1208**
followup to https://github.com/aces/Loris/pull/4227

Clean-up of formatting files resulting from the cloning of the github wiki repo

### CODE REVIEW

**Comment by ridz1208** [comment]
@kongtiaowang `DashboardTest::testConflictResolver` keeps failing randomly on branches

**Comment by kongtiaowang** [comment]
@ridz1208 You have it all figured out the Travis issue, I will remove the tag.

**Comment by driusan** [comment]
I don't understand these "_DELETED" files. If they're deleted why don't you delete them? They're always available in the history.

**Comment by ridz1208** [comment]
@driusan the plan is to delete them as soon as this branch is ready to be merged with any of the 3 main branches... the reason is 2 fold:

1. deleted files are hard to track on github especially when one does not know when it was deleted
2. submitting them as deleted informs reviewers that this content is not simply being moved or revamped but rather completely erased in a near future... its kind of like a deprecation warning.

**Pull request merged**
