### PR TITLE
[Media] Display instrument name

### PR DESCRIPTION
**Pull request by laemtl**
The field instrument in media (Upload) displays the Test_name instead of the Full_name. This PR fixes the issue.
Per @ridz1208's comment, this PR also changes the way the full name is queried in the rest of the module to use the instrument getFullName()'s  method.

### CODE REVIEW

**Review by ridz1208 — CHANGES_REQUESTED** [review]
That is not the correct full name. the full name must be queried from the instrument itself with `getFullName()` that column in the database is just legacy

**Comment by laemtl** [comment]
@ridz1208 In this case, the logic applied here (https://github.com/aces/Loris/blame/main/modules/media/php/media.class.inc#L100) should be revisited too.

**Comment by ridz1208** [comment]
@laemtl certaainly seems like it. Back then however the full name was in the DB. 👍

**Comment by laemtl** [comment]
@ridz1208 Comment addressed.

**Comment by laemtl** [comment]
@driusan Fixed.

**Review by ridz1208 — DISMISSED** [review]

**Comment by driusan** [comment]
That might be the case if the new LorisInstance instantiation is the only thing that needs to be moved out, but if the whole factory call does then ` $record["Test_name"]` is only available in the loop. You'd need to create a separate loop before the loop to create a dictionary of test_name => full name mappings for all instruments (O(instrument types) instead of O(sessions)) and use that map inside the loop.

**Comment by driusan** [comment]
I took a stab at fixing it with https://github.com/laemtl/Loris/pull/38 .. can you see if it helps?

**Comment by ridz1208** [comment]
@driusan rebased and fixed. Only `_LINST` file changes were added. it's ready for you to review

**Review by ridz1208 — APPROVED** [review]
Approving all changes OTHER THEN MY OWN

**Pull request merged**
