### PR TITLE
Merge bugfix branch into release branch

### PR DESCRIPTION
**Pull request by driusan**
This pulls the latest bugfix changes into the 21.0-release branch.

Note that there were conflicts in php/libraries/User.class.inc and modules/dataquery/jsx/reacts.tabs.js. Extra care should be taken reviewing file changes from those files.

### CODE REVIEW

**Comment by driusan** [comment]
@ridz1208 can you review the dqt changes (conflicts were caused by #4499) and @johnsaigle can you review the User.class.inc changes (I think the password line there was from one of your PRs.)

**Comment by ridz1208** [comment]
@driusan yeah I think there was an issue during the conflict resolution, some changes that should appear are not there

**Comment by driusan** [comment]
@ridz1208 what changes? Is it just the GetJS.php link?

**Comment by ridz1208** [comment]
it was only that file see #4700

**Comment by driusan** [comment]
superceded by #4700

**Pull request closed without merging**
