### PR TITLE
[DO NOT MERGE] Clean up the tools directory by deleting everything

### PR DESCRIPTION
**Pull request by driusan**
This cleans up the tools directory by deleting everything,
as proposed in the LORIS meeting by @jstirling91. Any
script that turns out to be necessary can be retrieved
from the history and cleaned up.

### CODE REVIEW

**Comment by ridz1208** [comment]
@driusan 
reinsert:
 - mri_violations_something
 - fix_timepoint_something_something

**Comment by ridz1208** [comment]
@driusan please decide on the fate of this PR. If still valid lets fix it and tag it as 18.0 ?

**Comment by ridz1208** [comment]
@driusan can we close this and make a PR after the release of 17.1 to 18.0 ?

**Comment by driusan** [comment]
Sure, that's a good idea.

**Comment by jstirling91** [comment]
@driusan but why, this was the pull request that remove the most bugs in loris

**Pull request closed without merging**
