### PR TITLE
[candidate_parameters] participant staus can save either comment or values

### PR DESCRIPTION
**Pull request by ridz1208**
possible commit messages: 
 - Get values from formData instead of data element for participant_status
 - Fixed values being overridden with null in participant status
 - bugfix participant_status
 - this is a commit message
 - Rida is the best

### CODE REVIEW

**Comment by sruthymathew123** [comment]
@ridz1208 
Good catch Rida. I tested it and it is now working as expected.
screenshot from 2017-03-16 09 29 30

**Comment by alisterdev** [comment]
- On @ridz1208  request fixed a bug where reason dropdown wasn't resetting its value while being disabled.
- On Travis' request fixed ESLint errors

PS: this probably needs to be tested one more time

**Comment by alisterdev** [comment]
@ridz1208 Since I wrote half of this code, I think somebody else should review

**Comment by ridz1208** [comment]
@alisterdev I'm surprised (a bit deceived actually) you didn't revamp the entire module while you'r at it...

@sruthymathew123 please re-test

**Comment by alisterdev** [comment]
@ridz1208 lol

**Comment by sruthymathew123** [comment]
@ridz120@ I somehow missed the request to retest conversation. The dropdown is not populating on Inactive/Incomplete. 

screenshot from 2017-03-24 12 42 45

**Comment by ridz1208** [comment]
@sruthymathew123 make sure you remove your override

**Comment by sruthymathew123** [comment]
@ridz1208 oops. I forgot on the quick retesting. I will do that and test it again.

**Comment by sruthymathew123** [comment]
@ridz1208 @alisterdev Sorry, it was my mistake that I forgot to remove my override. Working well as expected.

**Comment by sruthymathew123** [comment]
@ridz1208. This testing and fixing found an issue in ibis overridden module. Gonna create a ticket in ibis.

**Comment by ridz1208** [comment]
@driusan ready to go

**Comment by driusan** [comment]
@ridz1208 The description/title still hasn't been changed to something that would be meaningful in a commit message.

**Comment by ridz1208** [comment]
@driusan pick a message, create a message or close the PR... really all good options

**Pull request merged**
