### PR TITLE
[Documentation] Fix broken links

### LINKED ISSUE #6543: [Documentation] markdown broken links
I run a script to find all broken links in the markdown files of v23.0.

Reading: docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
Dead: github.com/aces/loris/releases
Reading: docs/wiki/99_Developers/Automated_Testing.md
Dead: test/UnitTestGuide.md
Reading: modules/behavioural_qc/test/TestPlan.md
Dead: https://github.com/aces/Loris/blob/17.1-dev/modules/behavioural_qc/test/behavioural_qcTest.php
Reading: docs/Routing.md
Dead: https://www.php-fig.org/psr/psr-15/]
Reading: CONTRIBUTING.md
Dead: https://github.com/aces/Loris/tree/minor/raisinbread#exporting-rb
Reading: README.md
Dead: ./docs/wiki/00%20-%20SERVER%20INSTALL%20AND%20CONFIGURATION/01%20-%20LORIS%20Install/CentOS/README.CentOS7.md

### PR DESCRIPTION
**Pull request by laemtl**
I ran a script to find all broken links on v 23.0, and fixed all the broken links found.

* Resolves #6543

### CODE REVIEW

**Comment by johnsaigle** [comment]
Also out of curiosity do you have the script? This seems like it could be a useful tool to run periodically to keep our documentation clean. Maybe it's worth adding to `tools/`?

**Comment by laemtl** [comment]
Yes, I noticed the possible conflict too. I can recheck from that branch!

**Comment by laemtl** [comment]
@johnsaigle I used the following tool: https://github.com/tcort/markdown-link-check, with the following command:
`find . -path ./node_modules -prune -o -name \*.md -print -exec markdown-link-check {} \;`

**Comment by christinerogers** [comment]
@laemtl request my review on this when ready and we'll get er done

**Comment by laemtl** [comment]
Found errors:

Reading: modules/genomic_browser/README.md
Server error on target: ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/ProductFiles/HumanMethylation450/HumanMethylation450_15017482_v1-2.csv
Reading: docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
Dead: github.com/aces/loris/releases
Reading: docs/HelpStyleGuide.md
Dead: /docs/images/helptext.png
Reading: docs/wiki/99_Developers/Automated_Testing.md
Dead: test/UnitTestGuide.md
Reading: modules/behavioural_qc/test/TestPlan.md
Dead: https://github.com/aces/Loris/blob/17.1-dev/modules/behavioural_qc/test/behavioural_qcTest.php
Reading: docs/Routing.md
Dead: https://www.php-fig.org/psr/psr-15/]
Reading: CONTRIBUTING.md
Dead: https://github.com/aces/Loris/tree/minor/raisinbread#exporting-rb
Reading: README.md
Dead: ./docs/wiki/00%20-%20SERVER%20INSTALL%20AND%20CONFIGURATION/01%20-%20LORIS%20Install/CentOS/README.CentOS7.md

**Comment by laemtl** [comment]
Closing and migrating to PR #6510

**Pull request closed without merging**
