### PR TITLE
PUSH 20.3.0 INTO MAJOR

### PR DESCRIPTION
**Pull request by ridz1208**
This is a tentstive PR for pushing code from the eventual 20.3.0 release into the `major` branch.

### CODE REVIEW

**Comment by ridz1208** [comment]
@maltheism @zaliqarosli 

I got some major conflicts when attempting to push forward the `modules/candidate_parameters/jsx/ConsentStatus.js` file.

the file underwent both extensive codestyle changes and functionality changes. I opted to conserve all functionality changes and sacrifice codestyle to resolve the conflicts.
the 2 commits below were omitted and should be reapplied on the file in this PR:
 - https://github.com/aces/Loris/commit/071aadde652fc979a8701ff9ad3b1407e47472c9#diff-9b7651c2e28b1697bce537314d97f6fd
 - https://github.com/aces/Loris/commit/aa7d3e9b4775797345742ff59135353221f0e769#diff-9b7651c2e28b1697bce537314d97f6fd

**Comment by zaliqarosli** [comment]
@ridz1208 from the looks of it, changes from your first link (https://github.com/aces/Loris/commit/071aadde652fc979a8701ff9ad3b1407e47472c9#diff-9b7651c2e28b1697bce537314d97f6fd) is included in the second link(https://github.com/aces/Loris/commit/aa7d3e9b4775797345742ff59135353221f0e769#diff-9b7651c2e28b1697bce537314d97f6fd) so we can just focus on the latter. what can I do to resolve this right now? push changes in the second commit to this PR?

**Comment by ridz1208** [comment]
@zaliqarosli indeed the second commit is done on top of the first. Right now the changes in either are included in the code for this class

Basically right now the changes would need to be made manually on top of this branch. Another option is to close this and you do the merge urself and simply resolve all the different conflicts.

**Comment by zaliqarosli** [comment]
@ridz1208 lol no no i'm not looking to pull all my hair out. I can manually push a commit to this branch if that is kosher

**Pull request merged**
