### PR TITLE
[Core] Code style file

### PR DESCRIPTION
**Pull request by alisterdev**
- Suggestion to add an `.editorconfig` to loris root in order to maintain consistent code style across different developers
- The idea is to avoid changes in whitespace in the future PRs
- Used and recommended by [a lot](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig) of people

>Note: the plugins seems to be smart enough to not affect existing code. (i.e when making changes to a file, it is shown in proper format + new changes are made in proper format, but old code is not converted, avoiding insane changes in PRs)

- [More info](http://editorconfig.org/) 
- [Plugins for text editors and IDEs](http://editorconfig.org/#download)

### CODE REVIEW

**Comment by johnsaigle** [comment]
Look into a way to have this be automatically consistent with our linting and code standards etc.

**Comment by alisterdev** [comment]
So after a quick research, it seems that there is no easy way to sync `.editorconfig` and `phpcs` / `eslint`, but in any case the overlap between these tools is very small (essentially just tabs or spaces, number of those and trailing spaces). 

Since these are the settings that are not expected to change often, if at all, I think there is still value in this addition.

**Comment by jstirling91** [comment]
@alisterdev Can you add a comment to the top of the file with the link to the plugins page so people don't have to go searching for this pull request

**Comment by alisterdev** [comment]
@jstirling91 Done

**Comment by johnsaigle** [comment]
@driusan I think this can be merged if you get a second

**Pull request merged**
