### PR TITLE
[document_repository] Error for filenames with comma

### PR DESCRIPTION
**Pull request by victori444**
## Brief summary of changes
In the Document Repository module's upload file section, have an error message appear when an uploaded file's name contains a comma

- [ ] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Upload a file containing a comma in its name in the document repository module and check that the appropriate error message appears
2. Upload a properly formatted file and ensure that the upload is successful

[CCNA Override](https://github.com/aces/CCNA/pull/6369)

### CODE REVIEW

**Comment by driusan** [comment]
Why can't file names contain commas?

**Comment by victori444** [comment]
Chrome has a restriction that prevents users from downloading files with commas in their names

**Comment by CamilleBeau** [comment]
@victori444 Check if #9029 fixes this issue

**Comment by victori444** [comment]
Based on [this](https://httpd.apache.org/docs/2.4/rewrite/flags.html#page-header) source, the changes in #9029 only escape space characters and question marks because of the argument `[B= ?]`. This can be set to `B` (without the character specifications) to escape all non-alphanumeric characters

**Comment by driusan** [comment]
@victori444 did you verify that that works? If so, can you update the PR and assign it to @racostas to test/review (@racostas don't forget to make sure there aren't regressions with #9029)

**Comment by victori444** [comment]
Update: the above comment does not work. Instead, I've removed the PR's original changes and allow for files with commas in their name to be uploaded by encoding the filenames when downloading

**Review by racostas — APPROVED** [review]
Changes are looking good in my end, I was able to upload, then download a file with a "," on it. Also compatible with a file with "spaces" on it ].

image

**Pull request merged**
