### PR TITLE
[Instrument List] Replaced the cross icon with (No actions)

### PR DESCRIPTION
**Pull request by AnyhowStep**
Now, it says "(No actions)"

image

### CODE REVIEW

**Comment by johnsaigle** [comment]
@driusan for you to merge now, I think.

**Comment by driusan** [comment]
Did @samirdas approve of this change?

**Comment by johnsaigle** [comment]
@driusan is that necessary? I think this is an improvement as it's more descriptive

**Comment by johnsaigle** [comment]
@samirdas

**Pull request merged**
