### PR TITLE
[Core] Getting rid of Database warnings about primary keys/values

### PR DESCRIPTION
**Pull request by Jkat**
Less PHP warnings 🙏

### CODE REVIEW

**Comment by driusan** [comment]
What/how many tables don't have a primary key set?

It seems to me like it would make more sense to fix those tables than to add this change, which could result in rows in the history table with no way to figure out where they came from..

**Comment by Jkat** [comment]
I'm not sure, but at least 1 table? :rofl:

**Comment by AnyhowStep** [comment]
At least `project_rel`
#2888 was made after experiencing this problem.

**Comment by johnsaigle** [comment]
@driusan are the Justins persuasive enough that we can move this to `Needs Testing`?

**Comment by driusan** [comment]
We should fix the warnings by adding primary keys, not hide them and prevent history from getting logged for them.

If there's any other than project_rel that are generating warnings, they'd warrant a new PR.

(We should also probably try and find a way to see if we can get Travis to fail if any of the tests generate warnings so that we catch things like this quickly..)

**Pull request closed without merging**
