### PR TITLE
[Forms] fix parameter position problems because of PR #6396

### PR DESCRIPTION
**Pull request by lingma**
## Brief summary of changes

Fix parameter position problem after the merge of the PR #6396. This is in addition to those processed in the PR #6431.

There are some trailing white spaces removed because of editor settings, which I did not notice early, but no much impact so I didn't redo the modification.

### CODE REVIEW

**Comment by driusan** [comment]
@ridz1208 can you check the impact on instruments of #6396 to determine if it should be reverted? If it's just the modules, I'm fine with this fix, but if it's all the text fields in project instruments it's probably not worth keeping the cleanup change.

**Comment by driusan** [comment]
@lingma This can't be merged because of conflicts, can you rebase?

**Comment by lingma** [comment]
sure

**Comment by lingma** [comment]
rebase

**Pull request merged**
