### PR TITLE
Illustrate abject failure of democracy

### PR DESCRIPTION
**Pull request by driusan**
This commit updates the code to disallow PHP 5.4+ short-array syntax, and
require the PHP3 style "array" keyword, after a vote in which it was
determined that a narrow majority of LORIS developers fear change.

Since being consistently wrong is better than being inconsistent, this
is still a slight improvement over the current state where different
people were doing different things.

See also: spaces for indentation.

Note: The code changes in this PR are just the result of updating the standards
XML file and running phpcbf until `test/run-php-linter.sh` stopped complaining.

### CODE REVIEW

**Comment by johnsaigle** [comment]
I'm still down for a mutiny if we can form a coalition with enough leverage

**Comment by driusan** [comment]
With the number of conflicts, it's probably easier/safer to just redo this change on a fresh branch.

**Comment by johnsaigle** [comment]
We should revote

**Comment by driusan** [comment]
Even with a revote that changes the outcome, it would still be easier to just send a new PR.

**Pull request closed without merging**
