### PR TITLE
[Tools] Add option to specify tables to dump for RB on command line

### PR DESCRIPTION
**Pull request by driusan**
This adds the ability to only dump certain tables by specifying them
as arguments on the command line to DB_dump_table_data.php.

### CODE REVIEW

**Comment by ridz1208** [comment]
I'm okai with that, but we might be running the risk of people accidentally forgetting to submit some changes that should submitted.

the opposite is true though, without it, we are running the risk of people submitting unnecessary changes... so pass!

**Comment by kongtiaowang** [comment]
I tested it, If I gave a correct table name, it worked well.
If I gave a wrong table name, It showed that "Couldn't find table" --- But it will create a backup file with the wrong table name under "/raisinbread/RB_files".

**Comment by driusan** [comment]
thanks for testing @kongtiaowang, I'll try and add a little more error checking for that

**Comment by driusan** [comment]
@kongtiaowang I added some error checking to ensure tables exist, can you test again?

**Pull request merged**
