### PR TITLE
[roles] new module

### PR DESCRIPTION
**Pull request by regisoc**
## Brief summary of changes

New `roles manager` module. 

Roles are pre-configured sets of permissions automatically assigned when the user is given a new role. This feature allows managers/coordinators to assign permissions to users based on their roles in a study. 

New in `roles_manager` (roles + role-permissions):
- a main table managing roles and their associated permissions.
- if users are attributed to a role, changing permissions of that role will trigger the update of user permissions for all user having this role.

Changes in `user_account` module (users + user-permissions + user-role):
- permissions are now disabled by default. Permissions goes through role selection.
- new component to select which roles are to be attributed to a user. 

Also:
- Added: generic vertical `Collapsible` React component.
- Added: tool to check/fix roles anomalies, e.g. if a user has been affected to a role through SQL, checks if permissions matches. 
- Removed: `permission_category` table.
- Added: `roles`, `user_role_rel`, `role_permission_rel` tables.

Other tasks:

- [x] Documentation
  - [x] readme
  - [x] test plan
- [ ] Raisinbread
  - [x] remove permission category
  - [ ] add role, role-permission, user-role data
- [ ] Tests
  - [x] remove permission category references in UserTests
  - [x] add Role lib tests
  - [ ] add roles_manager module tests
  - [ ] update user_accounts module tests for role selection

#### Screenshots of the current state

<details>
  <summary>Click to see the screenshots</summary>
  
Main Role page
image

Edit Role page
image

User account role selection
image

</details>

#### Testing instructions (if applicable)

1. Apply patch `2023-11-03_roles_module.sql` or `make testdata`.
2. Go to `LORIS front-end > Admin > Roles Manager` and `LORIS front-end > Admin > user accounts`

#### Link(s) to related issue(s)

Linked to #7416

### CODE REVIEW

**Comment by regisoc** [comment]
@driusan not all tests there, I will try to do that today.
Some functions need to move but main logic can be reviewed.

**Comment by regisoc** [comment]
@driusan after our discussion, this PR will be cut down in 3:
1. `roles_manager` itself for this release.
2. `Collapsible` LORIS React element.
3.  `user_accounts` changes for later.

**Comment by driusan** [comment]
What is the difference between the Collapsible component and jsx/Panel.js?

**Comment by regisoc** [comment]
Good point, I did not know Panel was a collapsible. 
I have only seen it without collapsed element somehow. 
So only 2 points then.

**Pull request closed without merging**
