### PR TITLE
Replace zend-diactoros with laminas-diactoros

### PR DESCRIPTION
**Pull request by driusan**
Fixes the error "Package zendframework/zend-diactoros is
abandoned, you should avoid using it. Use laminas/laminas-diactoros instead."
while running composer install on LORIS.

### CODE REVIEW

**Comment by johnsaigle** [comment]
The error doesn't occur for me when running `make checkstatic` on `aces/master`. Can you provide detailed steps to replicate?

I did:
```bash
git fetch aces
git checkout aces/master
make dev
make checkstatic
```

and there were no issues.

**Comment by driusan** [comment]
@johnsaigle ?

**Comment by driusan** [comment]
I don't have detailed steps to replicate, I just started getting the error when I followed those same steps (at the `make dev` part) this morning.

**Comment by driusan** [comment]
Maybe you can replicate by deleting your `~/.composer/cache` directory?

**Comment by johnsaigle** [comment]
```bash
git fetch aces
git checkout aces/master
rm -rf ~/composer/cache/
make dev
```

No issue appeared.

**Comment by driusan** [comment]
I'm not getting the error anymore either, but I still think we should move forward with this since, as you say, it's definitely abandoned (or at least renamed.)

**Pull request merged**
