### PR TITLE
[user_accounts] Fix Access when only own site permission is set

### LINKED ISSUE #7642: [User Accounts] Page loads with error when site's only permission set
**Describe the bug**
When given just the permission `User Accounts: View/Create/Edit User Accounts - Own Sites`, when loading the page you get the error `An error occurred while loading the page.`.

**To Reproduce**
Steps to reproduce the behaviour (attach screenshots if applicable):
1. Create a new user and assign them the `User Accounts: View/Create/Edit User Accounts - Own Sites` permission
2. Login as new users and go to User Accounts page

**What did you expect to happen?**
The page should load with all users's at you given site.

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser Chrome

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24.0.0
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

### PR DESCRIPTION
**Pull request by driusan**
Fix access to the user accounts module when the user has only the
"own site" permission. The user_accounts module was returning
strings of CenterIDs instead of objects, this updates it to return
CenterID objects.

Resolves #7642
Replaces/Closes #7764

### CODE REVIEW

**Comment by driusan** [comment]
@racostas this is the replacement for #7764.. can you review/test?

**Review by racostas — COMMENTED** [review]
The PR is doing what is intended to showing the users that have only same sites that the one logged in. 
It is failing some automatic test after fixing it should be fine.

Something I notice during the testing that not sure if is a "desired effect" is that every user with this permission (User Accounts: View/Create/Edit User Accounts - Own Sites) will be able to modify the permissions of the admin user as well.

image

I was effectively able to disable the admin account logged as test@test.test 

It's also seems that if one user have more than one site and get edited by one user having other sites (after saving) the "edited user" will be able to have "at most" the sites of the "editing user".

**(This is a bug)**

1. Sites of testrs2 before been edited
image

2. testrs2 been edited by test@test.test.
image

3. testrs2 after been edited.
image

**Comment by driusan** [comment]
@racostas are these new bugs, or is it the existing behaviour from before this change?

**Comment by racostas** [comment]
> @racostas are these new bugs, or is it the existing behaviour from before this change?

As mentioned in the first comment. This should not be introduced by this PR. This should be coexisting. Nevertheless don't  think nobody have been able to detect it as nobody have access before (This PR granted access for first time). 

If you agree, I will approve this PR after the automatics test pass. The issues should be addressed at some point nevertheless. @driusan

**Comment by driusan** [comment]
Can you make an issue for it and tag it as critical to release/discussion required?

**Review by racostas — APPROVED** [review]

**Pull request merged**
