### PR TITLE
[media] add feedback to dropdown field when is empty

### LINKED ISSUE #7951: [media] No feedback provided when candidate has no sessions or instruments
**Describe the bug**
In the media module,s uploading functionality, if the user selectsa  PSCID for a candidate with no timepoints, the Visit Label dropdown is empty with no clear explanation or message. Ideally the empty field should read "No visits available for this candidate" or something along those lines, an overkill would be to pop a swal but it might be too intrusive in this case

Similarly when no instruments are available the dropdown should indicate so as well.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. TEST loris -> media -> updload
2. choose DCC435
3. see dropdowns for Visit Label and instrument

### PR DESCRIPTION
**Pull request by shonibare**
Fixes #7951

### CODE REVIEW

**Comment by ridz1208** [comment]
Screenshot from 2023-03-08 20-13-07

not exactly how I was expecting the placeholder to behave. it shows up as an actual option not a place holder. @driusan im on the fence about this but functionally it works.

**Comment by driusan** [comment]
@ridz1208 how are you expecting a placeholder for a dropdown to work?

**Comment by ridz1208** [comment]
Screenshot_20230309_091505_com android chrome

Like a placeholder

**Review by ridz1208 — CHANGES_REQUESTED** [review]
Issue found (see screenshots)

To reproduce on RB:
1. go to the upload form
2. select candidate DCC090 + V2 + AOSI
3. change candidate to DCC355
4. ERROR

Screenshot from 2023-03-09 09-54-15

to reproduce without RB:
try choosing a candidate which has visits and a visit and an instrument then try selecting a candidate which doesn't have any visits

**Comment by shonibare** [comment]
> Issue found (see screenshots)
> 
> To reproduce on RB:
> 
> 1. go to the upload form
> 2. select candidate DCC090 + V2 + AOSI
> 3. change candidate to DCC355
> 4. ERROR
> 
> Screenshot from 2023-03-09 09-54-15
> 
> to reproduce without RB: try choosing a candidate which has visits and a visit and an instrument then try selecting a candidate which doesn't have any visits

Error fixed

**Review by ridz1208 — APPROVED** [review]

**Pull request merged**
