### PR TITLE
[Statistics] Fix site statistics page loading

### LINKED ISSUE #9353: [statistics] 500 coming from dashboard
**Describe the bug**

Follows the last comment from #9232.

Tested it, not a same issue anymore: redirects to a 500.
image

This is the log:
```
PHP Fatal error:  Uncaught TypeError: LORIS\\statistics\\Statistics_Site::_checkCriteria(): Argument #1 ($centerID) must be of type CenterID, string given, called in /var/www/Loris/modules/statistics/php/statistics_site.class.inc on line 189 and defined in /var/www/Loris/modules/statistics/php/statistics_site.class.inc:97\nStack trace:\n#0 /var/www/Loris/modules/statistics/php/statistics_site.class.inc(189): LORIS\\statistics\\Statistics_Site->_checkCriteria()\n#1 /var/www/Loris/modules/statistics/php/statistics_site.class.inc(277): LORIS\\statistics\\Statistics_Site->_completeCount()\n#2 /var/www/Loris/php/libraries/NDB_Page.class.inc(741): LORIS\\statistics\\Statistics_Site->setup()\n#3 /var/www/Loris/src/Middleware/UserPageDecorationMiddleware.php(247): NDB_Page->handle()\n#4 /var/www/Loris/src/Middleware/PageDecorationMiddleware.php(58): LORIS\\Middleware\\UserPageDecorationMiddleware->process()\n#5 /var/www/Loris/php/libraries/NDB_Page.class.inc(725): LORIS\\Middleware\\PageDecorationMiddleware->process()\n#6 /var/www/Loris/php/libraries/Module.class.inc(321): NDB_Page->process()\n#7 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): Module->handle()\n#8 /var/www/Loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process()\n#9 /var/www/Loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process()\n#10 /var/www/Loris/src/Middleware/ExceptionHandlingMiddleware.php(54): LORIS\\Router\\ModuleRouter->handle()\n#11 /var/www/Loris/src/Router/BaseRouter.php(132): LORIS\\Middleware\\ExceptionHandlingMiddleware->process()\n#12 /var/www/Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle()\n#13 /var/www/Loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process()\n#14 /var/www/Loris/htdocs/index.php(73): LORIS\\Middleware\\ContentLength->process()\n#15 {main}\n  thrown in /var/www/Loris/modules/statistics/php/statistics_site.class.inc on line 97, referer: https://rongarocarcy-dev.loris.ca/
```

CenterID not initialized [to a defined \CenterID object here](https://github.com/aces/Loris/blob/0413aaf275212a8fb3a69efc8605f67dca9e371d/modules/statistics/php/statistics_site.class.inc#L258).
Do we have a default site? The same kind might happen for ProjectID too.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to LORIS main page
2. Click on right panel, "My tasks" > "incomplete form"

image

3. See error

### PR DESCRIPTION
**Pull request by driusan**
Fix type errors on the page loaded from the link on the LORIS dashboard for "data entry incomplete" in my tasks.

Fixes #9353

### CODE REVIEW

**Comment by regisoc** [comment]
@driusan tested on my end, but one automatic test failed.

This is what I can see now, which looks good.
Recording 2024-09-24 at 14 12 47

**Comment by driusan** [comment]
@regisoc I think the test failure is an unrelated failure on the main branch.. I've already asked @kongtiaowang to look into it (tests were added that passed but I think there were incompatible changes on the main branch between the time the PR was sent and the time it was merged.)

**Review by regisoc — APPROVED** [review]
I will approve it now because it looks good to me.
@kongtiaowang Let me know if this failed test is not linked to the mentioned incompatibility.

**Comment by kongtiaowang** [comment]
@regisoc https://github.com/aces/Loris/pull/9355 will fix it.

**Pull request merged**
