### PR TITLE
[request_account] Remove First Name & Last Name fields more than 3 chars from test plan

### PR DESCRIPTION
**Pull request by kongtiaowang**
This pull request adds an error message when the first name and the last Name is too short.
https://redmine.cbrain.mcgill.ca/issues/13815

### CODE REVIEW

**Comment by thomasbeaudry** [comment]
I don't think that this is the best idea, since I have seen first names that are 2 characters long before.

**Comment by kongtiaowang** [comment]
@thomasbeaudry you are right.
I will change the test plan and make the first name and last name more than 1 character.

**Comment by zaliqarosli** [comment]
Looks like the errors aren't getting updated as needed i.e. if you try to submit with names having not enough characters, and then resubmit with empty field names, the error stays as " .. name is too short!" and not " .. name is required!"

**Comment by ridz1208** [comment]
it should say "You'r drunk, go home !!"

**Comment by driusan** [comment]
I agree with @thomasbeaudry, I don't think there's any good reason to enforce arbitrary name lengths. Some people have short names. I think if there's anything that's not whitespace entered, it should be valid.

**Comment by kongtiaowang** [comment]
@driusan I only change the test plan this time.

**Pull request merged**
