### PR TITLE
QC comments now import

### PR DESCRIPTION
**Pull request by nirtiac**

### CODE REVIEW

**Comment by driusan** [comment]
I don't think the changes in this pull request are related to the subject? Is this the right pull request/branch?

**Comment by nirtiac** [comment]
@driusan yep, that's the right fix for the bug; took me forever to find it. Adding the checkbox comments had already been implemented. These were random extra lines added, causing a error in the insert statement.

**Comment by driusan** [comment]
In that case, this is a deeper issue that might need @cmadjar or @MounaSafiHarab to give some input to make sure this doesn't break anything. That's a base class that's used elsewhere in the MRI pages. I think @cmadjar added those lines and might know the details of what they're supposed to do.

**Comment by cmadjar** [comment]
Hi,

You do need those fields in the files_qcstatus in case you have to remove and reupload the minc files so you can map the QC status in the files_qcstatus using the seriesUID and the echo_time. Do not remove this, it needs to be set.

Thanks!

Cécile

**Comment by nirtiac** [comment]
Hi @cmadjar I'm trying to come up with a work-around to not include those fields.. but I'm not quite sure I understand the issue. The function I'm editing (_addComment) only edits the feedback_mri_comments table as a side effect, it doesn't change any other values in any other table. The feedback_mri_comments table does not have the SeriesUID and EchoTime fields so any insert with those fields will always fail..

**Comment by cmadjar** [comment]
Hi @nirtiac ,

Are you sure you were looking at the right table or have an up-to-date feedback_mri_comments table? I just looked into the default schema of LORIS and the feedback_mri_comments table does have the SeriesUID and the EchoTime, as you can see from the following screenshot. It has to be there, otherwise you cannot reload imaging data without losing all the QC comments.

screen shot 2016-06-29 at 5 21 50 am

If you do not have the SeriesUID and EchoTime in your table, you will need to update it to include those fields as all other projects have them if the update was correctly done. The commands are included this pull request and was merged 2 years ago. https://github.com/aces/Loris/blob/bb6a6e2bd2ecc8c725ceba9b17f407005dbdf9e6/SQL/Archive/Pre-14.10/2013-01-21-SeriesUID-fix.sql

Hope this helps,

Cécile

**Comment by nirtiac** [comment]
@cmadjar Huh, thanks! I see now that my ccna db has those fields while my sandbox db doesn't... I now know I need to go through and check that patches have been run!

**Pull request closed without merging**
