### PR TITLE
[Imaging Uploader] Add React table and refactor old code

### PR DESCRIPTION
**Pull request by alisterdev**
>This is a first round of changes in attempt to modernize `Imaging Uploader`
---

- [x] Replace old data table with React data table
- [x] Remove JS from templates
- [x] A bit of ESLint and refactoring of the old code
- [x] Get ready to update filters and convert them to React

>Note: The code removed from `imaging_uploder_helper.js` was moved to `index.js`

[See Changes](https://github.com/aces/Loris/pull/2489/files?w=1)

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@alisterdev 
I tested this (namely filters, the table itself I originally had, etc...).
One comment though: when I click on the Number of MincInserted link, it takes me to imaging browser, but the filter is not applied. I can hit the "show data" button and data becomes filtered by the DCCID, but I thought I would bring this up.

**Comment by alisterdev** [comment]
@MounaSafiHarab Good catch, this should be fixed now!

**Comment by kongtiaowang** [comment]
The link of "Number Of MincInserted" goes to "https://demo.loris.ca/main.php?test_name=imaging_browser". It is better to remove "main.php?test_name".

**Comment by alisterdev** [comment]
@kongtiaowang I have to use this piece of code for the link to work and update the table results in imaging browser. 
```js
loris.loadFilteredMenuClickHandler('imaging_browser', {
  DCCID: dccid
})(e);
```

So the link should be updated separately in `loadFilteredMenuClickHandler` function.

**Comment by MounaSafiHarab** [comment]
@alisterdev 
I re-tested the updated pull request and it resolves the link problem!
it is all good from my end.

**Pull request merged**
