### PR TITLE
[IssueTracker] Fix single watcher problem

### LINKED ISSUE #8866: [issue_tracker] Singular watcher does not show as selected on issue form
**Describe the bug**
If there is only one potential watcher of an issue, and that user is already watching the issue, they are not shown as selected in the 'Add others watching?' dropdown of the issue form. 

**To Reproduce**
The following steps are assuming you only have the admin user in the DB, and no other users 
1. Create a new user
2. Create a new issue with the admin account and add the new user as a watcher -> click update issue
3. Refresh the page and see that the new user doesn't appear as selected in the watcher dropdown, while it is assigned in the issues_watching table in the DB. 

The following screenshot are taken when logged in as the admin account
image 

image

**Note**: if there are more than 1 options for watchers, i.e. >1 users apart from the issue reporter, then the watcher appears as selected correctly. 
image

### PR DESCRIPTION
**Pull request by sanjay-thiyagarajan**
## Brief summary of changes

- Fix for singular user highlighting in other watching list

#### Link(s) to related issue(s)

* Resolves #8866

### CODE REVIEW

**Review by charlottesce — CHANGES_REQUESTED** [review]
This doesn't seem to work, I still can't see the single watcher as selected.

**Comment by racostas** [comment]
Thank you @charlottesce, @sanjay-thiyagarajan will be working on this one and let you know for re-testing.

**Comment by racostas** [comment]
> @charlottesce The code is updated now. Can you check out ?

@charlottesce, when you have a chance could you re-test ? Thanks !

**Comment by charlottesce** [comment]
Yes I will test it as soon as I can

**Comment by racostas** [comment]
Hi @sanjay-thiyagarajan , this fix seems to be working. Nevertheless I do notice another issue we might want to solve as part of this PR:
image


In the BackEnd is the table:
**issues_history**

**Review by racostas — APPROVED** [review]
I approve the PR. There was a collateral issue found when testing. @sanjay-thiyagarajan to decide if want to addressed here or in a new PR,.

**Comment by racostas** [comment]
> It works for me too now, thanks!

Thank you Charlotte.

**Comment by racostas** [comment]
Ok. It seems this field was in facts never tracked in the history table. I think this definitively should go to a different issue. I know @sanjay-thiyagarajan this the last week of the GSoC program so I don't think is something you should solve. 
@sanjay-thiyagarajan, please create a new issue for this so other team member -- or maybe future GSoC :-) -- can take it from there. Thanks !!

**Pull request merged**
