### PR TITLE
[instrument_builder] Fix display order of select options

### PR DESCRIPTION
**Pull request by zaliqarosli**
## Brief summary of changes

- [ ] Have you updated related documentation?

#### Testing instructions (if applicable)

1.

#### Link(s) to related issue(s)

* Resolves #  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by ridz1208** [comment]
Quick question, have you in your attempt to fix this checked the following usecases:

 - when you are building an instrument and export it in LINST, does the exporting process re-arrange the order or the enum? or is the generated select line in the LINST in the correct order?
 - If you have a LINST with a select field with a specific order of options, when you load it back into the instrument builder does it modify the order of fields ? (I'm guessing this is what you are fixing in this PR?)

**Comment by zaliqarosli** [comment]
the order of the options in the linst file isn't affected at all.  it's just that the display of the options on the front end is re-ordered alphabetically

**Comment by ridz1208** [comment]
@zaliqarosli great thanks !

**Comment by zaliqarosli** [comment]
@ridz1208 wanna approve? :)

**Review by ridz1208 — APPROVED** [review]

**Pull request merged**
