### PR TITLE
JSON data toolkit

### PR DESCRIPTION
**Pull request by CamilleBeau**
This PR creates a toolkit for manipulating and interacting with instrument JSON data, intended for future instruments that will not have their own SQL tables. 
Operations include:
- Renaming fields
- Dropping fields
- Selecting specified data
- Modifying fields

This includes a library with functions to interact with the instrument data as well as a tools script to perform operations directly.

Needs work:
- functionality blocked until issue #6746 is solved as it prevents saving for modification of instruments that have a Data_entry_completion_status field in the flag data
- Score check not working
- PHP notices printed from validation check (although the validation check does seem to be functional)

### CODE REVIEW

**Comment by ridz1208** [comment]
@CamilleBeau 

> functionality blocked until issue #6746 is solved as it prevents saving for modification of instruments that have already been set to complete.

Instruments set to complete should not be saved. is the bug only for completed instruments ?

**Comment by CamilleBeau** [comment]
> @CamilleBeau
> 
> > functionality blocked until issue #6746 is solved as it prevents saving for modification of instruments that have already been set to complete.
> 
> Instruments set to complete should not be saved. is the bug only for completed instruments ?

Also instruments that have had one page (for example) saved but are not yet set to complete.

**Comment by ridz1208** [comment]
@CamilleBeau maybe modify the description its a bit confusing. its basically any instrument that has been started

**Comment by CamilleBeau** [comment]
> @CamilleBeau maybe modify the description its a bit confusing. its basically any instrument that has been started

Yes my bad!

**Comment by ridz1208** [comment]
@CamilleBeau can you make sure it passes travis and conflicts are fixed ?

**Comment by CamilleBeau** [comment]
Blocked by #6876

**Comment by CamilleBeau** [comment]
Closing this PR as most functionalities intended to be introduced from this PR will be possible with MariaDB JSON

**Pull request closed without merging**
