### PR TITLE
Fix the major branch

### PR DESCRIPTION
**Pull request by driusan**
This fixes the build on the major branch after an incorrectly resolved conflict.

### CODE REVIEW

**Comment by davidblader** [comment]
This fixes the 500 error with a 404 since I am guessing NDB_Caller has not been updated to handle the new module structure which I suppose is sufficient for a Passed Review in this instance?

**Comment by davidblader** [comment]
btw ```composer install``` is not working for me on major branch
image

**Comment by driusan** [comment]
The module structure support was added to all branches at least 2 releases ago, the modules just weren't updated until now.. this bug was introduced trying to merge things forwards, so it should still work.

**Comment by kongtiaowang** [comment]
@driusan 
     modules/new_profile/php/new_profile.class.inc:263
   "$config =& \NDB_Config::singleton();" to "$config = \NDB_Config::singleton();"

**Comment by driusan** [comment]
@kongtiaowang thanks

**Pull request merged**
