### PR TITLE
[database] Improve schema defaults

### PR DESCRIPTION
**Pull request by MaximeMulder**
## Brief summary of changes

While browsing the database schema, I noticed there were a lot of `default '0'` everywhere, even for foreign keys ! This is an anti-pattern that is easy to fix and should not require any change to the codebase outside of the schema, so here is a PR.

List of changes:
1. Drop the `DEFAULT 0` for foreign key fields (we do not have any table with a record at index `0` as far as I know/checked)
2. Change `DEFAULT '0'` (or `'1'`) to `DEFAULT 0` (or `1`) for other fields, which is more correct (the former can notably raise type errors with some database engines IIRC).

I don't think the `ALTER column SET DEFAULT 0` is actually useful in the SQL patch, but it cannot hurt.

I omitted the `mri_protocol.Scan_type` field as it is fixed in #9304 instead.

More broadly, it seems to me that there is an overuse of defaults in our database, but fixing everything would require a lot more work and analysis, and is therefore a job for another day.

#### Testing instructions (if applicable)

1. Apply patch and/or reset Rainsinbread
2. Use LORIS

### CODE REVIEW

**Comment by MaximeMulder** [comment]
All tests are passing, pinging random people @ridz1208 @kongtiaowang if anyone wants to review it, if not I'll just add this PR to the next LORIS meeting.

**Review by ridz1208 — APPROVED** [review]
Visual check passes. I would like IBIS @nicolasbrossard and CCNA @CamilleBeau to give the patch a test.

**Comment by CamilleBeau** [comment]
@ridz1208 I ran the patch on CCNA database and did not get any errors

**Comment by nicolasbrossard** [comment]
@ridz1208 Ran the patch on IBIS (uses V25) and did not get any errors or warnings.

**Pull request merged**
