### PR TITLE
[EEG Browser] Make fix

### LINKED ISSUE #8170: Error with Make: make: *** [Makefile:15: javascript] Error 2

### PR DESCRIPTION
**Pull request by laemtl**
Fix #8170

### CODE REVIEW

**Review by cmadjar — APPROVED** [review]
That fixes the issue! 👍

**Comment by cmadjar** [comment]
@laemtl @driusan @ridz1208  I wonder whether this fix should go to main or 24.1-release since this is a bug fix for 24.0?

**Comment by laemtl** [comment]
> @laemtl @driusan @ridz1208 I wonder whether this fix should go to main or 24.1-release since this is a bug fix for 24.0?

Probably both?

**Comment by driusan** [comment]
I'm not crazy about just ignoring the errors but I'm not the expert on typescript.

It should probably go to 24.1, though. I don't think there's any reason someone would upgrade to 24.0 now that 24.1 is finally released.

**Comment by laemtl** [comment]
> I'm not crazy about just ignoring the errors but I'm not the expert on typescript.
Those errors need to be ignored until the package is updated or the dependency is removed.

**Pull request merged**
