### PR TITLE
Added .nrrd filetype to files table

### PR DESCRIPTION
**Pull request by ridz1208**

### CODE REVIEW

**Comment by xlecours** [comment]
I don't know what is the threshold to decide that this column deserve its own table. 
Because it is an enum, this pull request can only be pull to 17.0 (ALTER TABLE statement)

**Comment by driusan** [comment]
I don't know about its own table, but it might make sense to just make it a varchar(255) for 17.0

**Comment by xlecours** [comment]
- I don't know if there is many rows in that table but if we want to have all distinct file_type then it will require a full table scan. (it might already be the case with that enum though). Having it in its own table reduce this overhead. 
- There is also the robustness issue of inconsistent values (e.g.: 'CSV', 'csv', 'CsV', ' CSV', '    CSV   ',...)
should we add the 'To be discussed' label?

**Comment by driusan** [comment]
No, there's no reason to discuss: you're right. Normalizing it is a better idea.

**Comment by ridz1208** [comment]
all in all, close this pull request.. to be made to 17.0 ?

**Comment by ridz1208** [comment]
TO BE MOVED TO 17.0

**Pull request closed without merging**
