### PR TITLE
[Issue Tracker] Updating patch for Issue Tracker issues_categories table

### PR DESCRIPTION
**Pull request by Jkat**
The initial patch to create the issues_categories table used latin1 charset.

### CODE REVIEW

**Comment by driusan** [comment]
@ridz1208 wasn't this affecting you? Can you verify if this fixes your issue?

**Comment by driusan** [comment]
@ridz1208 see above.

**Comment by jstirling91** [comment]
@jkat will the charset be UTF-8 on initial sourcing of the default schema?

**Comment by driusan** [comment]
It appears to already be utf8 in the default schema:

https://github.com/aces/Loris/blob/17.1-dev/SQL/0000-00-00-schema.sql#L1347-L1352

**Comment by MounaSafiHarab** [comment]
@driusan 

indeed, default schema was fine for new installs, but not for existing projects which ran this patch when they upgraded from v16.1 to v17.0:
https://github.com/aces/Loris/blob/17.1-dev/SQL/Release_patches/16.1_To_17.0_upgrade.sql#L218-L223

**Pull request merged**
