### PR TITLE
[Media] Media upload updates

### PR DESCRIPTION
**Pull request by alisterdev**
- [x] Fix react warning related to StaticElement format
- [x] Remove unused CSS
- [x] Replace bootstrap alerts and JS alerts with [SweetAlert](http://t4t5.github.io/sweetalert/)
- [x] Replace default `confirm` dialog with a fancy sweetalert confirm
- [x] Setup `htdocs/vendor/` directory for front-end dependencies
----

For discussion: 
- Are people interested in this library? YES
- Should we place all external libraries in the `htdocs/vendor` with a README explaining what is used and why? YES

----

image

### CODE REVIEW

**Comment by alisterdev** [comment]
Based on the discussion during PR meeting, people were open to using sweetalert library

**Comment by davidblader** [comment]
having some trouble testing this. which branch did you base this on?

**Comment by alisterdev** [comment]
17.1  but it wasn't updated to most recent changes. In any case it shouldn't matter, but I suspect you'll need to remove CCNA override to test it

**Comment by davidblader** [comment]
i'm unable to get the new stylized alert on my vm

**Comment by alisterdev** [comment]
@davidblader Can you please test this again + make sure your long instruments names are not going over the popup

**Comment by davidblader** [comment]
Still getting old school alert from existing file exception:
screenshot from 2017-02-16 12-55-51

and then when clicking OK:
screenshot from 2017-02-16 12-56-13

should probably be :x:  instead of :white_check_mark: :

**Comment by alisterdev** [comment]
@davidblader Fixed the bug you pointed out and even implemented a confirm dialog which was not originally included in the PR. One last test please 👼

**Comment by davidblader** [comment]
i'd say this is good, only remark i have is that the progress bar sticks at 100% after upload either success or failure.
also the confirm dialog is great but i think there should be a second message after saying whether the upload went through or not.

**Comment by alisterdev** [comment]
@davidblader That is probably a problem with your upload folder permissions, not with the PR itself

**Pull request merged**
