### PR TITLE
[Core] Fixed an error in downloading files

### PR DESCRIPTION
**Pull request by johnsaigle**
This pull request fixes a bug where text files, xml files, and others could be downloaded unintentionally. This patch represents a big security improvement.

Specific changes:

- [x] Improved detection of illegal paths (and removed incomplete checks)

- [x] Increased safety for file access

- [x] Removed empty `header` case

- [x] Applied phpcs for formatting

### CODE REVIEW

**Comment by driusan** [comment]
@johnsaigle Doesn't this need to go in 17.0? This PR is going to the 17.1 branch.

**Comment by johnsaigle** [comment]
Struggling with git but I'll rebase soon

**Comment by johnsaigle** [comment]
SOS

**Comment by johnsaigle** [comment]
I think I accidentally deleted everything. I am sad.

**Pull request closed without merging**
