### PR TITLE
[JSX] Relax Strictness of Filter for Multiselect in Filter Component

### PR DESCRIPTION
**Pull request by HenriRabalais**
## Brief summary of changes

This PR reduces the strictness of the filter logic in the Filter.js component by adjusting the conditions for the exactMatch variable, functionally changing the multiselect filter from an AND to an OR boolean operators.

If this change is contentious, I can work on a way of have this be decided either by individual modules via a prop, or by use input by incorporating some sort of toggle button.

### CODE REVIEW

**Comment by maximemulder** [comment]
Hum, do you have a use case for this change ? I am not sure we want it if it is not used somewhere.

**Comment by HenriRabalais** [comment]
The use-case is all filters because this would influence the behaviour of multi-select filters across the board. The idea being that multi-select filters should behave with OR behaviour rather than AND behaviour. But that's why I think this needs discussion, since it's a pretty large change it might merit having some sort of optional toggle or module-specific configuration. @ridz1208 and @driusan do you have any thoughts?

**Comment by maximemulder** [comment]
Oh, hum okay, I do see a utility in your projects example. But I am not the best person to answer whether or not this is a desirable feature, so I guess we should either get a reply from the devs you pinged or talk about it at a LORIS meeting (every Tuesday at 11AM).

**Comment by skarya22** [comment]
Is it possible to have a parameter in addMultiselect that let's you choose if it is an OR or AND? I can see the possibility of a project wanting to allow users to be able to see when a participant as two visits such as both Baseline_V2a and Baseline_V2b in CCNA.
image
I think that it would make it less restrictive and prevent a future override from needing to be made.

So I feel like the `I can work on a way of have this be decided either by individual modules via a prop` would be beneficial

**Review by maximemulder — APPROVED** [review]
Works on my machine !

**Pull request merged**
