### PR TITLE
[conflict_resolver] api + dataframework (version 3)

### PR DESCRIPTION
**Pull request by xlecours**
## Brief summary of changes
 - implements the auto-saving of conflict resolution
 - add 2 endpoints (/conflict_resolver/unresolved and /conflict_resolver/resolved)
 - Adds a schema.yml file 

Previous versions:
https://github.com/aces/Loris/pull/6862
https://github.com/aces/Loris/pull/5140

This will conflict with https://github.com/aces/Loris/pull/7535

### CODE REVIEW

**Comment by maltheism** [comment]
Hi @xlecours when I visit the conflict_resolver module while on the unresolved pane and try to set the correct answer. I've having an error caused by $this->table being null for the following code:
```
$db->update(
   $this->table,
   $values,
   ['CommentID' => $this->getCommentID()]
);
```
located at Loris/php/libraries/NDB_BBVL_Instrument.class.inc at line # 829

```
PHP Fatal error:  Uncaught TypeError: Database::update(): Argument #1 ($table) must be of type string, null given, called in Loris/php/libraries/NDB_BVL_Instrument.class.inc on line 832 and defined in Loris/php/libraries/Database.class.inc:510
Stack trace 
0 Loris/php/libraries/NDB_BVL_Instrument.class.inc(832): Database->update(NULL, Array, Array
1 Loris/php/libraries/NDB_BVL_Instrument.class.inc(802): NDB_BVL_Instrument->_save(Array
2 Loris/modules/conflict_resolver/php/endpoints/unresolved.class.inc(256): NDB_BVL_Instrument->_saveValues(Array
3 Loris/modules/conflict_resolver/php/endpoints/unresolved.class.inc(121): LORIS\\conflict_resolver\\Endpoints\\Unresolved->_handlePOST(Object(Laminas\\Diactoros\\ServerRequest
4 Loris/src/Middleware/ETag.php(78): LORIS\\conflict_resolver\\Endpoints\\Unresolved->handle(Object(Laminas\\Diactoros\\ServerRequest
5 Loris/src/Http/Endpoint.php(46): LORIS\\Middleware\\ETag->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\conflict_resolver\\Endpoints\\Unresolved
6 Loris/modules/conflict_resolver/php/module.class.inc(72): LORIS\\Http\\Endpoint->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\conflict_resolver\\Endpoints\\Unresolved
7 Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\conflict_resolver\\Module->handle(Object(Laminas\\Diactoros\\ServerRequest
8 Loris/src/Middleware/AuthMiddleware.php(63): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\conflict_resolver\\Module
9 Loris/src/Router/ModuleRouter.php(74): LORIS\\Middleware\\AuthMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\conflict_resolver\\Module
10 Loris/src/Middleware/ExceptionHandlingMiddleware.php(39): LORIS\\Router\\ModuleRouter->handle(Object(Laminas\\Diactoros\\ServerRequest
11 Loris/src/Router/BaseRouter.php(126): LORIS\\Middleware\\ExceptionHandlingMiddleware->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\ModuleRouter
12 Loris/src/Middleware/ResponseGenerator.php(50): LORIS\\Router\\BaseRouter->handle(Object(Laminas\\Diactoros\\ServerRequest
13 Loris/src/Middleware/ContentLength.php(52): LORIS\\Middleware\\ResponseGenerator->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter
14 Loris/htdocs/index.php(48): LORIS\\Middleware\\ContentLength->process(Object(Laminas\\Diactoros\\ServerRequest), Object(LORIS\\Router\\BaseRouter
15 {main thrown in Loris/php/libraries/Database.class.inc on line 510, referer: http://localhost/conflict_resolver/
```

**Review by maltheism — CHANGES_REQUESTED** [review]
Hi @xlecours, please see my comment. I did make clean && make dev on your branch with tools/raisinbread_refresh.php and I did check to see that your mysql patch was applied.

**Comment by driusan** [comment]
what is the instrument that you're using to try and resolve a conflict on?

**Comment by maltheism** [comment]
thanks @driusan that's probably my issue.

**Comment by xlecours** [comment]
@maltheism Did you had the chance to review this with another instrument?

**Review by maltheism — APPROVED** [review]
Everything looks great!

**Comment by driusan** [comment]
I tried to merge this but there's a conflict with `webpack.config.js`

**Pull request merged**
