### PR TITLE
[Publications] Error and swal fix

### PR DESCRIPTION
**Pull request by laemtl**
Small changes following the comment made in #7315 
- Fix missing error message
- Fix missing swal callback change (#6195 regression) previously in #7091

### Replace #7091

### CODE REVIEW

**Comment by driusan** [comment]
@maltheism Maybe you can review?

**Comment by maltheism** [comment]
Hi @laemtl, I'm not seeing the swal when there's an error in the publication module. Example if I'm trying to make a publication with the exact details as an existing one. I think the showPublicationError() function is to blame in the ajax/FileUpload.php

**Review by maltheism — CHANGES_REQUESTED** [review]
Hi @laemtl, I'm not seeing the swal when there's an error in the publication module. Example if I'm trying to make a publication with the exact details as an existing one. I think the showPublicationError() function is to blame in the ajax/FileUpload.php

**Comment by laemtl** [comment]
I just tried and saw the error popup: 
Screenshot from 2021-02-11 19-40-42

**Review by maltheism — APPROVED** [review]
Hi @laemtl, it works now for me. I'm unsure why it wasn't before. Maybe I didn't delete my cache, sorry!

**Pull request merged**
