### PR TITLE
[BugFix] Modified process.php for Security Check for Study Description, added …

### PR DESCRIPTION
**Pull request by intralizee**
…two new functions inside Utility.class.inc and wrote testcase UtilityTest.php

This pull request `Fixes the security issue`.

See also: `Bug #14303`

### CODE REVIEW

**Comment by ridz1208** [comment]
switching blocked to needs discussion.

**Comment by ridz1208** [comment]
This has conflicts

**Comment by johnsaigle** [comment]
@intralizee I am going to bring this up in my security presentation but it would probably be good to add as an agenda item to a LORIS meeting if you want this PR to get moving.

**Comment by driusan** [comment]
@intralizee this has conflicts

**Comment by driusan** [comment]
(and is failing travis)

**Comment by johnsaigle** [comment]
@intralizee It's important that this bug be fixed. Are you going to have time to work on this PR?

**Comment by zaliqarosli** [comment]
@johnsaigle is this a PR you might be able to take over?

**Comment by johnsaigle** [comment]
@zaliqarosli Not at this time until the discussion is resolved. I'll bring it up in a LORIS meeting.

**Comment by zaliqarosli** [comment]
@johnsaigle i am wondering if you would want to take over resolving the discussion as well, as it won't get resolved on its own

**Comment by johnsaigle** [comment]
As discussed in the meeting today we'll be going for a Markdown-based approach for the study description instead of HTML whitelisting, and so I will close this PR.

**Pull request closed without merging**
