### PR TITLE
[composer] manage project dependencies

### PR DESCRIPTION
**Pull request by regisoc**
## Brief summary of changes

- Allow additional composer deps to be managed in `project/` without the need to override the main `composer.json`.
- Adds the documentation section to cover how to override LORIS.

#### Testing instructions (if applicable)

1. create a `project/composer.json` with additional deps.
2. run `composer update`

#### Related PR

Reopening #8319 as a new dependency is needed in HBCD.

### CODE REVIEW

**Comment by ridz1208** [comment]
@regisoc I'm seeing a bunch of unrelated changes for ID alphabet? were those meant to be in the same PR?

**Comment by regisoc** [comment]
@ridz1208 not at first no. I wanted to add the `composer.json/.lock` + doc change for one unique dependency.
When pushing the new `composer.lock`, it must have added updated requirements, with PHPStan 2, because looking into it, some of the changes are related to phpstan v2.
Several errors started to pop up on github checks, and I could not validate the PR.

Here is the list I can see:

- `phpstan v2` deprecated rule [`excludes_analyse` in favour of `excludePaths`](https://github.com/phpstan/phpstan/blob/14d2bed0874dd067270fd544e2f2f4a9d6a13caf/UPGRADING.md?plain=1#L81).
- `phpstan v2` also added a [stricter rule level system](https://phpstan.org/user-guide/rule-levels), we were using the `--level max` but this hits the `mixed` type hard. Mentioned [here](https://github.com/aces/Loris/pull/9490/files#diff-902a31b6588d96090db4b44712b75643fd0d924ae48e40472fa1fa9cabbe903e), I lowered it to `level 8` for now but I can try to put it back to `9` or `10 (max)`. Not sure what is the best here.
- PHPStan v2 did not like implicit parameter types in Candidate/FeedbackMRI/issue_tracker classes, `null` added as explicit type for all.
- I because the type returned in `SideIDGenerator::_getIDSetting()` was a [mixed type](https://github.com/aces/Loris/blob/8f118bdd7cc572b785b627b891753032304147dc/php/libraries/SiteIDGenerator.php#L153) (i.e. "array<int,int|string>|string|null") and phpstan v2 did not like that, I extracted the "alphabet" option to its own method `SideIDGenerator::_getIDSettingAlphabet()` to isolate returned types.
  - `SideIDGenerator::_getIDSetting()` returns `string|null`.
  - `SideIDGenerator::_getIDSettingAlphabet()` returns `array<int,int|string>`.

**Comment by regisoc** [comment]
@driusan pinging you here because not sure of the solution and what it would involve.

**Comment by regisoc** [comment]
Closed for #9496

**Pull request closed without merging**
