### PR TITLE
[Training] Remove training module

### PR DESCRIPTION
**Pull request by driusan**
This removes the training module, which is currently only used by CCNA
project (which also overrides the module.)

### CODE REVIEW

**Comment by kongtiaowang** [comment]
raisinbread/RB_files/RB_certification_training_quiz_answers.sql    
raisinbread/RB_files/RB_certification_training_quiz_questions.sql 
raisinbread/RB_files/RB_certification_training.sql

**Comment by johnsaigle** [comment]
Failing Travis due to some issue with Subprojects.

**Comment by driusan** [comment]
Restarted 7.2 and it's passing now.

**Comment by ridz1208** [comment]
*Yu gonplei ste odon*

**Pull request merged**
