### PR TITLE
[tools] Replace a constant date with current date

### LINKED ISSUE #8066: [tools] Hard-coded date in DB_date_zeros_removal.php Patch
**Describe the bug**
Tool runs successfully, but the Patch generated always has the same name with the date "2016-06-01"
`The output file is SQL/Archive/18.0/2016-06-01-update_zero_fields_statements.sql and includes foreign key checks disabling and re-enabling.
`

The output should have a name with the current date.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run tool as intended
2. Observe name of generated patch

### PR DESCRIPTION
**Pull request by shonibare**
fixes #8066

### CODE REVIEW

**Comment by ridz1208** [comment]
@driusan this should probably go to 24.1, please confirm

**Comment by driusan** [comment]
I don't think we need to. The script should probably be moved to single use though.

**Comment by ridz1208** [comment]
@shonibare can you make sure to move this script to the single use directory and update all relative paths in the script ?

**Comment by shonibare** [comment]
> @shonibare can you make sure to move this script to the single use directory and update all relative paths in the script ?
Updated

**Pull request closed without merging**
