### PR TITLE
[SQL] Schema files cleanup

### PR DESCRIPTION
**Pull request by xlecours**
- [x] Include all relevant alter table from the old ticket
- [x] Make sure foreign keys are created and not ignored
- [x] Rectifying some discrepancies between the schema file and the upgraded version of the database
- [x] Removing unused indexes
- [x] Using more of column default values and auto_increment while inserting initial data 
- [x] Finalising last ENGINE and CHARSET changes
- [x] Adding comments on some cryptic tables
- [x] Removing dead code in HelpFile.class.inc

This patch has a side effect: It delete orphan data from `Config`, `session_status`, `participant_status`.

### CODE REVIEW

**Comment by xlecours** [comment]
I think we should go back to the single schema file but split the data inserts.

**Comment by AnyhowStep** [comment]
I already pointed this out in person and it's being looked into but I thought I'd just add a comment here.

The `SELECT`s, `WARNINGS`, and `SET SQL_NOTES` statements cause `$DB->PDO->exec()` to fail on subsequent calls to it. One hack I can think of is to just close the DB connection and reopen it after each call to `exec()` in the `installdb.php` script.

But there's probably a better way to handle this.

**Comment by AnyhowStep** [comment]
I just realized something.

`installdb.php` uses `/php/installer/Installer.class.inc`, which looks for `0000-00-99-indexes.sql`.

It appears that this file does not exist and will cause `installdb.php` to return an error. I am unsure if this file is necessary or what its significance is.

**Comment by xlecours** [comment]
@AnyhowStep see https://github.com/aces/Loris/pull/2673 for the indexes.sql file problem

**Pull request merged**
