### PR TITLE
[Help Editor - edit help subpage] created help text

### PR DESCRIPTION
**Pull request by knoll-alex**
created a page for the edit content page within the help editor module

#### Testing instructions

1. review copy
2. see screenshot for rendering

#### Links to related tickets

* https://github.com/aces/Loris/issues/5576
* https://github.com/aces/Loris/issues/5729 

Screenshot 2019-11-24 19 37 21

### CODE REVIEW

**Comment by christinerogers** [comment]
review / merge for **22** pls - @ridz1208 @driusan     

(discussion on #5776 notwithstanding)

**Comment by ridz1208** [comment]
This seems incorrect given our latest discussion on the matter. This should probably remove any reference to modules and specify it is for instruments ?

**Comment by christinerogers** [comment]
@knoll-alex FYI - this PR may languish for a little while given the current debate about the purpose of this page.  I'll try to steer/modify the Help text on this PR as needed and get it merged.

**Comment by zaliqarosli** [comment]
this is how editing help content works:

> Modules get 'Help' content from Markdown help file in modules/module_name/help. Instruments and modules without help file get content from DB help table. Only help content from DB is editable on the front-end using the Help Editor module (content for .md files are not editable on the front-end).

This is from the description of PR https://github.com/aces/Loris/pull/3558. This was how the code worked from even before I made changes to the module. This PR https://github.com/aces/Loris/pull/3345 removed the projectContent column of the help table.

Whilst the Markdown help file is favoured over the DB help table, maybe we should reverse this order of preference. If people agree, I can make a github issue for this @driusan @johnsaigle @christinerogers @ridz1208 . I'm also having trouble finding where the code for this is if anyone knows!

**Comment by johnsaigle** [comment]
@christinerogers What is this Blocked by?

**Comment by cmadjar** [comment]
@christinerogers What is this Blocked by?

**Comment by christinerogers** [comment]
Closing this for now since we need a new direction for the Help Editor module. 
this content could well be re-sourced and modified slightly for the next iteration of this module. 
Thanks @knoll-alex for your contributions here!

**Pull request closed without merging**
