### PR TITLE
LorisForm multiselect elements

### PR DESCRIPTION
**Pull request by driusan**
This adds support for multiselect elements to the LorisForm QuickForm replacement.

### CODE REVIEW

**Comment by taracampbell** [comment]
Code looks good, tested and multiselect appears to be working, however the form element does not have bootstrap styling.

**Comment by driusan** [comment]
Why would it have bootstrap styling? LorisForm is the replacement for QuickForm.. quickform never had bootstrap styling.

**Comment by taracampbell** [comment]
Other form elements have the bootstrap styling applied automatically. I think this happens in NDB_Page?

**Comment by taracampbell** [comment]
Nvm I don't know what I'm doing...

**Pull request merged**
