### PR TITLE
[Imaging Browser] Updated module help text

### PR DESCRIPTION
**Pull request by knoll-alex**
## Brief summary of changes

New copy for Imaging Browser module help text
#### Testing instructions (if applicable)

1. Edit copy if necessary
2. Check out screenshots of rendering below

#### Links to related tickets (GitHub, Redmine, ...)

*https://github.com/aces/Loris/issues/5576

Screenshot 2019-11-12 22 48 02
Screenshot 2019-11-12 22 47 23

### CODE REVIEW

**Comment by johnsaigle** [comment]
This one also has the Conflict Resolver changes included. It would be good to either create a separate PR for it or include it in just one of these two PRs.

**Comment by christinerogers** [comment]
has the conflict resolver md on it.  probably started from the wrong branch?

**Comment by christinerogers** [comment]
@driusan - another cherry-pick, looking for advisement

**Comment by johnsaigle** [comment]
I'm closing this in favour of the PR replacing it

**Pull request closed without merging**
