### PR TITLE
Redmine 10105 - DCC cannot access candidate_list without access_all_profiles

### PR DESCRIPTION
**Pull request by stellarxo**
DCC can now enter with data_entry permissions
(can access without data entry permissions, but doesn't show up in loris menu)

### CODE REVIEW

**Comment by ridz1208** [comment]
run phpcs

**Comment by jstirling91** [comment]
run the following ```vendor/bin/phpcs --standard=docs/LorisCS.xml --extensions=php/php,inc/php modules/candidate_list``` to run phpcs

**Comment by christinerogers** [comment]
Logic on this line is a little confusing as to intention: a && b || c 
If DCC user doesn't have data-entry permission, should they be able to access? (I'd say yes)
Could you clarify with brackets? e.g. 
$user->hasPermission('access_all_profiles')
|| ($site->isStudySite() && $user->hasPermission('data_entry') ) 
|| $site->getCenterName() == "DCC"
cc: @jstirling91

**Comment by stellarxo** [comment]
Updated so DCC can view DCC candidates with data_entry and not access_all

**Pull request closed without merging**
