### PR TITLE
[issue tracker] function less arguments error in php 7.1.

### PR DESCRIPTION
**Pull request by kongtiaowang**
fixing issue tracker function less arguments error in PHP 7.1.

### CODE REVIEW

**Comment by kongtiaowang** [comment]
@xlecours 
Thanks

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

I know this fix worked on your setup, so I can add the passed manual test because I saw it working on your setup. But I suggest to assign it to someone to test with PHP 7.1 as I personally do not have this issue (with or without your fix, things work for me).

**Comment by kongtiaowang** [comment]
@xlecours 
Could u review it again?

**Comment by ridz1208** [comment]
@davidblader please test

**Pull request merged**
