### PR TITLE
User class: Throw Loris exception for getCenterID, getData(CenterID), getSiteName, and getData(Site): Redmine 12945

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
Throws Loris exception for calling some functions in the User class that have been changed to reflect users at multiple sites.

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@ridz1208 
took the liberty to assign to you (I do think you somehow said assign it to you when I do the changes?).
I did not tag it as critical for the release, but I want to say it is critical for the testing.

**Comment by ridz1208** [comment]
@MounaSafiHarab look failures !!!

**Comment by ridz1208** [comment]
@MounaSafiHarab issues encountered should be resolved in https://github.com/aces/Loris/pull/2721

**Comment by MounaSafiHarab** [comment]
@ridz1208 
so I will rebase on 17.1 once yours is merged

**Comment by driusan** [comment]
@MounaSafiHarab #2721 is merged. Can you rebase and see if that fixes the tests?

**Comment by MounaSafiHarab** [comment]
@driusan 
rebased; waiting for Travis now.
 @ridz1208 
it looks like re-basing dismissed your review, sorry!

**Pull request merged**
