### PR TITLE
[document_repository] fix can't load 

### PR DESCRIPTION
**Pull request by kongtiaowang**
solve :[Document Repository] Module broken, does not load https://github.com/aces/Loris/issues/6066
 wrong variable name.

### CODE REVIEW

**Comment by driusan** [comment]
Shouldn't there be a test to make sure that it didn't load before and that this fixes it?

**Comment by johnsaigle** [comment]
It was a weird bug... the page did load but the contents got auto-hidden from the user. The doc repo integration tests are really basic so it's possible they are still contained in the HTML response body so Travis had no issue.

If it had tests for menu filters, buttons, etc then I imagine they would've failed.

**Comment by kongtiaowang** [comment]
To test the react page, it is necessary to do "Ctrl + Shift + R" to reload the currently open page and override the locally cached version after running make dev.
@maltheism Could u manually test this PR?

**Comment by kongtiaowang** [comment]
@johnsaigle when you load page "document_repository/doctree/0" if the subcategories are empty,  you may not on this branch.

**Comment by johnsaigle** [comment]
I only tested `/document_repository/` and the page was still blank.

**Pull request merged**
