### PR TITLE
[Core: NDB Page and Children] Add return types to function signatures

### PR DESCRIPTION
**Pull request by johnsaigle**
See #3878 for background.

This PR covers NDB Page and its child classes. They must be updated together because their function signatures all need to match.

### CODE REVIEW

**Comment by johnsaigle** [comment]
This PR will be easier to deal with when #4073 is merged so I'm adding `Blocked` for the time being.

**Comment by driusan** [comment]
Can we close this and reopen it after the next major release? NDB_Page type signature changes will also require the updating of every single instrument file in every project that upgrades, and we already forced people to do that a couple releases ago, so giving them a break might be a good idea.

**Comment by johnsaigle** [comment]
@driusan Sure that makes sense. This also impacts other classes that are tightly coupled with NDB_Page, such as LorisForm I believe. I'll make a list of the libraries that will be excluded from the 21 release.

**Comment by johnsaigle** [comment]
Closing for now. Should be re-opened after the LORIS 21 release.

**Pull request closed without merging**
