### PR TITLE
Update NodeJS version

### LINKED ISSUE #7067: [Install] Update Node 8 (deprecated) for Node 10 (12 recommended)
In the install guides, we should update the version of Node to adjust to the current release.
Node 8 is not supported anymore. The deprecation warning suggests to use v12 (recommended), or v10.

### PR DESCRIPTION
**Pull request by laemtl**
* Resolves #7067

### CODE REVIEW

**Comment by driusan** [comment]
This is failing Travis

**Comment by driusan** [comment]
Also it doesn't seem to update the NodeJS version, just the documentation?

**Comment by laemtl** [comment]
Yes, It does only update the documentation. What about something like this:
* NodeJS 8.0 or higher  (10.0 or higher recommended)

**Comment by driusan** [comment]
The documentation aren't suggestions. They're under the heading minimum requirements in each of the documents.

**Comment by driusan** [comment]
I just tried doing a `make dev` on the master branch and got a bunch of errors like:

```
npm install
npm WARN notsup Unsupported engine for copy-webpack-plugin@6.3.2: wanted: {"node":">= 10.13.0"} (current: {"node":"8.4.0","npm":"6.13.4"})
```
so the node version *does* need to be updated in the documentation now, but it looks like the minimum is 10.13, not 10.0, can you update this PR?

**Comment by laemtl** [comment]
@driusan Done

**Review by driusan — APPROVED** [review]

**Pull request merged**
