### PR TITLE
[JSX] transpiling files not done properly

### PR DESCRIPTION
**Pull request by ridz1208**
This updates the compiled js to match the current jsx

### CODE REVIEW

**Comment by ridz1208** [comment]
@driusan this should have been done when the files were modified...

**Comment by driusan** [comment]
Yes.

What discussion is required on this?

**Comment by ridz1208** [comment]
if I look at the media jsx/js files they have last been edited by the same pr/commit (which leads me to assume that the person who submitted the change had indeed compiled the files) so i'm not sure why they seem to be out of sync

also, how did the PR making the changes pass tests when the effects of it were apparently not in effect... if the rendering is done using the JS not the JSX !

**Comment by driusan** [comment]
Maybe they were compiled using a different version of webpack or babel?

**Comment by ridz1208** [comment]
which means that this PR should be closed then otherwise it fixes it for me but not for whoever commited them..
thus the discussion required

**Comment by kongtiaowang** [comment]
@ridz1208 
There is one module "Media" doesn't work. 
screen shot 2017-11-20 at 12 13 33 pm

**Comment by ridz1208** [comment]
@kongtiaowang how come travis didnt catch this one ?

**Comment by kongtiaowang** [comment]
@ridz1208 
The test for media, I am working on it.
 So far it only tests the breadcrumbs part. 
You could remove this part from your PR if you want. 
Media module could be fixed in other PR.

**Comment by ridz1208** [comment]
@kongtiaowang I removed the media changes

**Comment by ridz1208** [comment]
@xlecours can you please re-approve (nothing changed other than ignoring media files to be fixed by @kongtiaowang )

**Pull request merged**
