### PR TITLE
[Issue Tracker] update test plan to delete items not relevant

### LINKED ISSUE #5495: [issue_tracker] Test Plan needs to be updated
Some tests cannot be completed based on previous changes made to the module

### PR DESCRIPTION
**Pull request by coreyAbout**
## Brief summary of changes

To fix the test plan indicating that some the function was not available now

#### Testing instructions (if applicable)

Check the test plan that the following items are removed:
Issue Tracker Create New Issue [Manual Testing]
7. Navigation bar should lead you back to list

Issue Tracker Edit Existing Issue [Manual Testing]
7. Check that the navigation bar bring you to the next issue in your previously filtered list of issues.

#### Links to related tickets (GitHub, Redmine, ...)
fixes #5495
*

### CODE REVIEW

**Comment by johnsaigle** [comment]
I think it makes sense to delete these lines from the test plan rather than say that they are not available now. Whether or not a feature exists or is planned for development is relevant from the standpoint of someone testing.

**Comment by coreyAbout** [comment]
I am not sure about that. Keep the items there would work as a reminder for developers when writing the test plan after the function is available. Otherwise, it may be easily forgotten, or sliped through. For testing purpose, testers know to skip it when the not available label is there. This should be the less harmful way. But anyway, whoever is in the position to make a final decision, I will happen to implement it.

**Comment by driusan** [comment]
@johnsaigle is right. Test plans aren't the place to document a backlog of work..

**Comment by johnsaigle** [comment]
We can make issues for those features so that there is a record that they should be implemented.

**Comment by johnsaigle** [comment]
Would you mind adding a new issue card for these features @coreyAbout ?

**Comment by coreyAbout** [comment]
Done as you wish @johnsaigle @driusan . 
Note that in another pull request I made, #5534, I was told to add not available label, but keep the item there.

**Comment by coreyAbout** [comment]
@christinerogers contributed in discussion about this one as well.

**Comment by christinerogers** [comment]
why is this a backlog / feature to be added?  The navigation panel was removed for 21.0 in this PR :
* #4855 `[issue_tracker] Remove navigation control panel`

We clearly wanted it removed.  Has this changed?

**Comment by johnsaigle** [comment]
You're right, we can close this issue actually since it relates to an old feature.

When reviewing an older version of this PR there were items saying "not yet implemented" or something like that so I thought they were feature requests, not deleted features.

I'll close the issue that was opened.

**Comment by driusan** [comment]
If it was intentionally removed then that's even more reason to delete the line and not annotate it as "[not available now]."

**Pull request merged**
