### PR TITLE
[Issues] Removed usage of CouchDB in User class when updating password

### PR DESCRIPTION
**Pull request by AnyhowStep**
In reference to a bug as reported:

> If CouchDB is not running, trying to use the socket still causes the request to time out.
>
> I thought this was fixed a while ago.
>
> Very low priority though.

I found code in the `User` class that would attempt to connect to CouchDB when updating a user's password if `SyncAccounts` is set to `true` in the `config.xml`.

That bit of code has been removed because it should not be used. Also, the following lines have been found in the code base,

```
./test/config.xml:        <SyncAccounts>false</SyncAccounts>
./test/unittests.sh:#       *  Set SyncAccounts to false: <SyncAccounts>false</SyncAccounts>
./test/integration.sh:#       *  Set SyncAccounts to false: <SyncAccounts>false</SyncAccounts>
./docs/config/config.xml:        <SyncAccounts>false</SyncAccounts>
./project/config.xml:        <SyncAccounts>false</SyncAccounts>
```

Should I remove them all?

They appear to be wrapped in a `<CouchDB>` tag,

```
    <CouchDB>
        <SyncAccounts>false</SyncAccounts>
    </CouchDB>
```

Do I remove the `<CouchDB>` tags, too?

### CODE REVIEW

**Comment by Jkat** [comment]
Actually, I made this Redmine ticket in reference to a different bug - when CouchDB is not running, in the ideal scenario, you should not run into a request timeout.

**Comment by Jkat** [comment]
(meaning to say, this issue is not isolated to just updatePassword or SyncAccounts, which should be gotten rid of)

**Comment by Jkat** [comment]
Also, I don't think you can get rid of the CouchDB tag, we're not at that stage yet of config migration, but I could be wrong. @driusan can verify.

**Comment by AnyhowStep** [comment]
@Jkat The issue is listed under the `user_accounts` module and I could only find this usage left in that module.

**Comment by AnyhowStep** [comment]
@jstirling91 , done.

**Pull request merged**
