### PR TITLE
[package.json] unbound variable

### PR DESCRIPTION
**Pull request by kongtiaowang**
Add a bound variable.

test: 
run "npm run tests:integration" with error.

### CODE REVIEW

**Comment by johnsaigle** [comment]
I think this PR is solving the same problem as #5571, but that PR fixes more errors.

**Comment by driusan** [comment]
Can someone confirm that #5571 fixed the issue and this is now unnecessary?

**Comment by maltheism** [comment]
@johnsaigle @kongtiaowang  @driusan see the below for what I get when running the command on #5571  
```
$ npm run tests:integration

> loris@1.0.0 tests:integration /Users/alizee/Development/GitHub/McGill/Loris
> ./test/dockerized-integration-tests.sh

WARNING: The XDEBUG_REMOTE_HOST variable is not set. Defaulting to a blank string.
Creating network "loris_default" with the default driver
Building db
...
```
Seems to be working correctly on #5571 .

**Comment by johnsaigle** [comment]
@maltheism Yep that's the expected fix.

**Comment by kongtiaowang** [comment]
duplicate

**Pull request closed without merging**
