### PR TITLE
Fix type of physiological electrode X, Y and Z fields to be nullable

### PR DESCRIPTION
**Pull request by cmadjar**
## Brief summary of changes

The values stored in the X, Y and Z columns of the `*electrodes.tsv` BIDS file can be set to `n/a` which cannot be inserted into the current type of the corresponding fields in the `physiological_electrode` table. This PR modifies the default schema and adds a patch to make those columns NULLABLE so the values of X, Y and Z can be set to `NULL` when `n/a` is provided in the BIDS `*electrodes.tsv` file.

### CODE REVIEW

**Comment by cmadjar** [comment]
@driusan @ridz1208 I added the critical to release tag here as these SQL changes will be required for LORIS-MRI release 24.0.

@ridz1208 is that a big enough change to add to the CHANGELOG? Happy to add it. Just not sure whether it is relevant or not...

**Comment by cmadjar** [comment]
Blocking LORIS-MRI PR: https://github.com/aces/Loris-MRI/pull/726

**Review by AlexandraLivadas — APPROVED** [review]
The patch and the new `CREATE TABLE`  command work as expected. Looks great to me!

**Comment by cmadjar** [comment]
@driusan ready for you. Thank you!

**Pull request merged**
