### PR TITLE
[BVL Feedback] Add dynamictable and fix margin-top

### PR DESCRIPTION
**Pull request by zaliqarosli**
## Brief summary of changes

fixes https://github.com/aces/Loris/issues/5074

#### Testing instructions

1. Check BVL Feedback panel with data

#### Links to related tickets (GitHub, Redmine, ...)

*https://redmine.cbrain.mcgill.ca/issues/15186

### CODE REVIEW

**Comment by xlecours** [comment]
I can't see how to test the caroussel. The bvl_panel has fixed width and is not "device responsive"
Also, the Feedback Threads status change dropdown extends over the table and creates scroll bars. I think this could be avoided but might be out of scope for this PR.

**Comment by zaliqarosli** [comment]
@xlecours could you provide screenshots of your second point? to test the carousel, you can inject data into the table so it becomes wider than the width of the panel. this will activate the carousel and allow you to scroll horizontally to see the overflow

**Comment by sruthymathew123** [comment]
@zaliqarosli Can you add a sample screenshot(before/after) on how it looks like. Actually, I didn't see any difference when I tried to test this.

**Comment by zaliqarosli** [comment]
@sruthymathew123 

before:
Screenshot 2019-10-02 16 32 46

after:
Screenshot 2019-10-02 16 41 03

**Comment by sruthymathew123** [comment]
Thanks @zaliqarosli 
Changes look
bvl_inst
 good.

**Comment by zaliqarosli** [comment]
@sruthymathew123 thanks for reviewing and testing :)

**Pull request merged**
