### PR TITLE
main.tpl jQuery cleanup

### PR DESCRIPTION
**Pull request by laemtl**
- remove jQuery instances from main.tpl
- bootstrap jQuery tooltip is replaced by a simple css tooltip (Site affiliations)
- ~~jQuery eslint rules are simplified and turned off for files that still uses jQuery to clean the console output.~~

### CODE REVIEW

**Review by driusan — CHANGES_REQUESTED** [review]
The eslint rules shouldn't be changed. The code violating them should be fixed.

**Comment by driusan** [comment]
(in other PRs, eventually.)

**Comment by laemtl** [comment]
> The eslint rules shouldn't be changed. The code violating them should be fixed.

That's the plan, but jQuery rules produce a lot of warnings that prevent devs to notice and fix new warnings they introduce.

**Comment by ridz1208** [comment]
@driusan & @laemtl to discuss removal of warnings

**Pull request merged**
