### PR TITLE
Remove SWAL library

### LINKED ISSUE #6114: Remove SWAL from htdocs/vendor
We currently have 2 versions of swal used in LORIS: sweetalert2, managed by npm, and sweetalert, which is placed in the htdocs/vendor/js/sweetalert directory. We should migrate all usage to be the sweetalert2 version and remove the old vendored code.

### PR DESCRIPTION
**Pull request by haoweiqiu**
## Brief summary of changes

Try to remove SWAL library.

#### Link(s) to related issue(s)

* Resolves #6114  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by christinerogers** [comment]
Hi Laetitia @laemtl and Shen @kongtiaowang  - Any ideas here for the integration test failures we're seeing in Travis?

**Comment by laemtl** [comment]
@christinerogers I investigated a few with @haoweiqiu and they passed. Closing to see if we get the same result twice.

**Comment by laemtl** [comment]
Made a small change and Travis is passing now.

**Comment by laemtl** [comment]
Find one last occurence that may be problematic in htdocs/js/instrument_controlpanel_swaldeletedata.js:
```
function swalFunction(event) {
  swal.fire({
    title: 'Please confirm deletion',
    text: 'The instrument data will be deleted',
```

reference in smarty/templates/instrumentstatus_controlpanel.tpl

**Comment by haoweiqiu** [comment]
Hi @laemtl I have also found this function. It was originally `swal`, but I changed to `swal.fire` (Sweetalert 2).

**Comment by laemtl** [comment]
@haoweiqiu It is not embedded in a react component so this change will not work. @maltheism, any suggestions?

**Comment by laemtl** [comment]
Fixed. If someone can test to validate that the change didn't break anything, that would be great.

**Comment by christinerogers** [comment]
Hi @laemtl - could you comment on how this PR should move forward? 
Is it still relevant - does it just need @haoweiqiu to rebase it?

**Comment by laemtl** [comment]
This PR is ready for review once it is rebased. I think it is still relevant, except if @ridz1208 or @driusan think otherwise.

**Comment by christinerogers** [comment]
@haoweiqiu would you be able to rebase this? Thank you -

**Comment by christinerogers** [comment]
@laemtl could you review this, and then ask Dave and Rida for review/input? thank you.

**Comment by laemtl** [comment]
@christinerogers @haoweiqiu Tests failing.

**Comment by cmadjar** [comment]
@kongtiaowang can you take over this PR?

**Comment by laemtl** [comment]
@kongtiaowang @cmadjar A rebase should fix all the problems

**Comment by ridz1208** [comment]
@laemtl rebase done. please make sure everything is good

**Comment by ridz1208** [comment]
@laemtl static tests reveal a bunch or errors in the JSX file. rebasing did not resolve the issues

**Comment by cmadjar** [comment]
@jesscall can you fix the Travis errors of this PR?

**Comment by jesscall** [comment]
@cmadjar @ridz1208 
I fixed the static errors, but noticed that the `save` functionality is broken for this module. It seems like the response is fine, but the DB entry is not actually updated. I don't think this is a result of my changes, but I could be wrong. 
I should note that it is not working on `main` either.

Maybe @laemtl can confirm if my changes look good.

**Comment by zaliqarosli** [comment]
@laemtl @ridz1208 @christinerogers guys i think we should probably keep this library until all modules are reactified? sweetalert2 only works if embedded in a react component.

i would like to use sweetalert in this PR https://github.com/aces/Loris/pull/7069/files targeting the non-reactified configuration module. how should i move forward?

**Comment by cmadjar** [comment]
@driusan to be discussed at the LORIS meeting.

**Comment by laemtl** [comment]
This PR has been updated to address @zaliqarosli comment. It should be ready to go after a rebase.

**Review by maltheism — APPROVED** [review]

**Comment by driusan** [comment]
@maltheism can you rebase again? I think I merged a different one of your PRs today that added a reference to it somewhere else, I want to be sure the tests still pass..

**Comment by maltheism** [comment]
@driusan I think this PR makes my other PR irrelevant. I manually tested the preview button of the help_editor module and it works correctly in this PR as well.

**Comment by driusan** [comment]
@maltheism conflicts in .eslintrc.json too

**Pull request merged**
