### PR TITLE
403 Forbidden code should not happen when a page loads properly. removing

### PR DESCRIPTION
**Pull request by tedstrauss**
The 403 status code is defined here https://en.wikipedia.org/wiki/List_of_HTTP_status_codes:

> 403 Forbidden: The request was a valid request, but the server is refusing to respond to it. 403 error semantically means "unauthorized", i.e. the user does not have the necessary permissions for the resource.

We were issuing this code on the normally loading login/logout page. It is not a semantically correct use of the code.
Testing and monitoring tools rely on correct use of http codes.

### CODE REVIEW

**Comment by xlecours** [comment]
I don't think that the 403 error is inaccurate. This access to main.php for users that are not logged in is forbidden.

**Comment by xlecours** [comment]
There might be implication with the API though

**Comment by tedstrauss** [comment]
This will not be going to the current release, so i will resubmit this PR for the 16.1 branch.

@xlecours jordan asked the same about API, so we will research this question.

I will close this PR once the new one is created.

**Comment by jstirling91** [comment]
Make pull request to 16.1-dev

**Comment by johnsaigle** [comment]
@tedstrauss does this still require discussion?

**Pull request closed without merging**
