### PR TITLE
Redmine 7868 - Delete Recycling Bin candidates from Conflict Resolver

### PR DESCRIPTION
**Pull request by stellarxo**
Discussed w/Leigh & Samir - Recycling Bin candidates to be removed from Conflict Resolver.

### CODE REVIEW

**Comment by evanluc** [comment]
@stellarxo this query:

*DELETE FROM conflicts_unresolved WHERE MD5(CONCAT_WS(':',TableName, ExtraKeyColumn, ExtraKey1, ExtraKey2, FieldName, CommentId1, CommentId2)) = '$hash'"* runs fine

but the second one

*"DELETE FROM conflicts_unresolved USING conflicts_unresolved cu JOIN flag f ON (cu.CommentID1=f.CommentID) JOIN session s ON (f.SessionID=s.ID) WHERE s.Current_stage='Recycling Bin'"*

Gives me the following error: **ERROR 1109 (42S02): Unknown table 'conflicts_unresolved' in MULTI DELETE**.

I am running mySQL version : **5.6.23**.

**Comment by evanluc** [comment]
Similar issues seem to have been reported here:
http://stackoverflow.com/questions/10728581/unknown-table-in-multi-delete

**Comment by stellarxo** [comment]
@evanluc sorry about that, I think I fixed it. can you take another look at it?

**Comment by evanluc** [comment]
Worked on my sandbox perfectly now.

**Comment by stellarxo** [comment]
See PR #1212

**Pull request closed without merging**
