### PR TITLE
Add phan rule PhanUnusedPrivateMethodParameter

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

Adds a rule to check when a function has a parameter in its signature that is never used.

#### Link(s) to related issue(s)

* #6027 must be merged first. This PR removes an exception introduced by that PR.

### CODE REVIEW

**Comment by ridz1208** [comment]
@laemtl to review you should be making sure that the parameters are actually not used anywhere in the code

**Comment by laemtl** [comment]
Build has failed. 

1) Issue_TrackerTest::testIssueTrackerFilter

Failed asserting that '<html platform="linux" class="theme-light" dir="ltr"><head><link rel="stylesheet" type="text/css" href="resource://devtools-client-jsonview/css/main.css"><script src="resource://devtools-client-jsonview/lib/require.js" data-main="resource://devtools-client-jsonview/viewer-config.js" defer=""></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="viewer-config" src="resource://devtools-client-jsonview/viewer-config.js"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="json-viewer" src="resource://devtools-client-jsonview/json-viewer.js"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="devtools/client/shared/vendor/react-dom" src="resource://devtools-client-shared/vendor/react-dom.js"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="devtools/client/shared/react-utils" src="resource://devtools-client-shared/react-utils.js"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="components/main-tabbed-area" src="resource://devtools-client-jsonview/components/main-tabbed-area.js"></script><script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="devtools/client/shared/vendor/react" src="resource://devtools-client-shared/vendor/react.js"></script></head><body><div id="content"><plaintext id="json">{"data":[["999999","Test Issue","",null,"TestUser",null,"new","low","55",null,null,null,"2020-02-11 20:48:19",null,null,false],["27","test ticket with visit label","Create Timepoint",null,"admin","admin","new","low","2","MTL002","V1","2016-09-06 17:38:06","2019-06-11 14:01:43","2","300002",false],["26","testing site population","Dashboard",null,"admin","admin","new","low","2",null,null,"2016-09-06 17:19:20","2016-09-07 01:19:20",null,null,false],["25","ticket to end all tickets ","",null,"admin","admin","new","low","4",null,null,"2016-09-02 15:47:01","2019-06-11 14:00:36",null,null,false],["24","ticket to end all tickets ","",null,"admin","admin","new","low","3",null,null,"2016-09-02 15:46:56","2019-06-11 14:00:31",null,null,false],["23","ticket to end all tickets ","",null,"admin","admin","new","low","3",null,null,"2016-09-02 15:46:48","2016-09-02 23:46:48",null,null,false],["22","ticket to end all tickets ","",null,"admin","admin","new","low","2",null,null,"2016-09-02 15:46:32","2019-06-11 14:00:24",null,null,false],["21","ticket to end all tickets ","",null,"admin","admin","new","low","2",null,null,"2016-09-02 15:45:39","2019-06-11 14:00:19",null,null,false],["20","testing if assignee gets email upon ticket update+re-assign","Data Release",null,"admin","admin","feedback","urgent","4",null,null,"2016-09-02 14:02:29","2019-06-11 14:01:24",null,null,false],["19","testing if assignee gets email  - new ticket","Dashboard",null,"admin","admin","feedback","urgent","3",null,null,"2016-09-02 13:59:55","2016-09-02 21:59:55",null,null,false],["18","ticket 3 testing email","",null,"admin","admin","new","low","3",null,null,"2016-09-02 12:33:47","2019-06-11 14:00:01",null,null,false],["17","another ticket to test assignment notification","",null,"admin","admin","new","low","2",null,null,"2016-09-02 12:31:45","2019-06-11 13:59:53",null,null,false],["16","new issue to test assignee notification","Imaging Quality Control",null,"admin","admin","new","low","2",null,null,"2016-09-02 12:30:38","2019-06-11 13:59:47",null,null,false],["15","Need form added","",null,"admin","admin","new","low","2","MTL002",null,"2016-09-01 10:51:46","2016-09-02 20:28:38",null,"300002",false],["14","Need form added","",null,"admin","admin","closed","high","2","MTL001",null,"2016-09-01 10:47:54","2016-09-01 18:49:55",null,"300001",false]],"fieldOptions":{"modules":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"categories":{"Behavioural Battery":"Behavioural Battery","Behavioural Instruments":"Behavioural Instruments","Data Entry":"Data Entry","Examiners":"Examiners","Imaging":"Imaging","Other":"Other","Technical Issue":"Technical Issue","User Accounts":"User Accounts"},"reporters":{"admin":"Admin account"},"assignees":{"admin":"Admin account"},"statuses":{"new":"New","acknowledged":"Acknowledged","feedback":"Feedback","assigned":"Assigned","resolved":"Resolved","closed":"Closed"},"priorities":{"normal":"Normal","high":"High","urgent":"Urgent","immediate":"Immediate"},"sites":{"1":"Data Coordinating Center","2":"Montreal","3":"Ottawa","4":"Rome","55":"TESTinPSC"},"userID":"UnitTester"}}</plaintext></div></body></html>' contains "issueID".

**Comment by laemtl** [comment]
@ridz1208 I removed a few new unused method parameterds and we should good to go.

**Comment by laemtl** [comment]
@driusan this is ready for review

**Pull request merged**
