### PR TITLE
[EEG] Montage color map

### PR DESCRIPTION
**Pull request by laemtl**
Add a colormap to flag specific channels in the EEG montage:

Screenshot 2024-06-04 at 10 04 26 AM

To enable it, add the following in In `modules/electrophysiology_browser/jsx/electrophysiologySessionView.js`

```
<EEGMontage colorMap={
    { 
      color: '#FF0000',
      ids: [1,2,4,7] // index of electrodes to include in the colorMap
    }
 } />
```

### CODE REVIEW

**Comment by laemtl** [comment]
@christinerogers @jeffersoncasimir For visibility

**Review by jeffersoncasimir — APPROVED** [review]
Works as expected!

**Comment by laemtl** [comment]
@ridz1208 Ready

**Comment by christinerogers** [comment]
amazing, thanks team.  ok if i add the 26 label?

**Comment by driusan** [comment]
This doesn't have any description. What is it doing and why?

**Comment by laemtl** [comment]
@driusan done

**Pull request merged**
