### PR TITLE
[Media] Rename date_uploaded column to last_modified

### LINKED ISSUE #5078: [Media] Date Uploaded changes on update / edit, does not keep actual "Date Uploaded"
Date uploaded is changed to date of edit. Perhaps add "date modified" column?

https://redmine.cbrain.mcgill.ca/issues/13802

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

The `Date Uploaded` column is not named accurately. It is a timestamp value that updates to the current timestamp upon edit. 

Given this behaviour, it should be called "Last Modified". This PR does that.

#### Testing instructions (if applicable)

1. Check out this pull request and run the patch
2. Run `make dev`
3. Go to the media module and verify that the column `Date Uploaded` now says `Last Modified`

#### Links to related tickets (GitHub, Redmine, ...)

* Resolves #5078

### CODE REVIEW

**Comment by cmadjar** [comment]
@johnsaigle Renaming the column to `Last Modified` makes a lot of sense since this is what it actually stores. 

Just wondering, is there a value in having an `Initial Upload Date` field? Is that a useful information to have?

**Comment by johnsaigle** [comment]
I'm not sure. Maybe someone who works on a project would be able to say whether this is valuable information or not.

**Comment by maltheism** [comment]
modules/media/ajax/FileUpload.php line 167

**Comment by johnsaigle** [comment]
@maltheism Thanks, I updated the code.

**Pull request merged**
