### PR TITLE
[Core] ESLint shortcut

### PR DESCRIPTION
**Pull request by alisterdev**
- [x] Add eslint as a script to package.json

Now, running can be done in the following ways from Loris root directory:

1. `node_modules/.bin/eslint [--fix] $path$` 
2. `npm run -s lint [--fix] $path`

### CODE REVIEW

**Comment by alisterdev** [comment]
@driusan Here are relatively easy ways for people to run `eslint`. Adding a grunt plugin is possible but would require to specify all the paths in advance instead of just passing them as parameters.

**Comment by driusan** [comment]
Is there any easy way to run it on all the files that have already had it run on them to ensure there's no regressions?

**Comment by alisterdev** [comment]
Either run `eslint modules/` to run on everything, or we need to maintain a list of linted modules, in which case grunt should be used

**Comment by alisterdev** [comment]
Closing until future notice

**Pull request closed without merging**
