### PR TITLE
[Tools] Enable PHPCS for config_to_db.php

### PR DESCRIPTION
**Pull request by laemtl**
Replaces #5988

### CODE REVIEW

**Comment by christinerogers** [comment]
This script can probably be deprecated/deleted. 
It was a one-time script for a 2015 release upgrade -- [see history](https://github.com/johnsaigle/Loris/commits/master/tools/config_to_db.php).
 
@johnsaigle, given your commit in Jan - do you recall any recent discussion? 
re value in keeping it for future re-use / possibility of maintaining it?

**Comment by johnsaigle** [comment]
No I don't know the context behind it. We can put it in the `tools/deprecated` folder instead.

**Comment by driusan** [comment]
This belongs in `tools/single_use`, not `tools/deprecated`. It was a script used for an upgrade.

**Comment by laemtl** [comment]
Do we still want to run PHPCS for this script for each build then?

**Pull request merged**
