### PR TITLE
[media] Correct explainer text in the Upload tab

### PR DESCRIPTION
**Pull request by PapillonMcGill**
change the example text to meet expectation of the code

### This resolves issue...
https://github.com/aces/Loris/issues/4571 

### To test this change...
go to media and upload a file for instrument Body Mass Index (BMI)

### CODE REVIEW

**Comment by ridz1208** [comment]
@PapillonMcGill why is package.json being modified ?

**Comment by PapillonMcGill** [comment]
shouldn't be included. It was modified by Make.  
Will take it out.

**Comment by driusan** [comment]
This is failing Travis. (I tried restarting it, but it's still failing.)

**Comment by johnsaigle** [comment]
@driusan This is passing now

**Pull request merged**
