### PR TITLE
[Clean Up] Deleting htdocs/mri/jiv/show_one_jiv_file.php

### PR DESCRIPTION
**Pull request by AnyhowStep**
I found a file, `htdocs/mri/jiv/show_one_jiv_file.php`, with the `@category Garbage` tag. According to @driusan , this should be deleted. Should the entire `htdocs/mri` folder be deleted, too?

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@driusan @gluneau @gluneau 

For projects using the JIV viewer, I am thinking this might be a needed file. We are moving away to using BrainBrowser as the visualization tool, but we need to confirm with @LeighMac that JIV viewers are no longer used.

As to your comment @AnyhowStep on deleting the whole folder, I believe that get_file.php is a needed script.

**Comment by driusan** [comment]
A few places still use `get_file.php`, but I don't believe anyone uses jiv anymore.

**Comment by MounaSafiHarab** [comment]
@driusan 

I believe Louis still does, but @LeighMac can confirm otherwise.

**Comment by driusan** [comment]
I just confirmed with @LeighMac that Louis is on the brainbrowser now.

**Pull request merged**
