### PR TITLE
Remove version file

### PR DESCRIPTION
**Pull request by driusan**
The VERSION file is not properly maintained, and is more confusing
than enlightening for users. Even if it were updated more consistently,
it prevents merging between the bugfix/minor/major branches.

This removes the file so that users aren't misinformed. It's not
maintainable in the current state of LORIS unless/until there's a way to
automate its generation through GitHub releases :(

### CODE REVIEW

**Comment by johnsaigle** [comment]
Related: https://github.com/aces/Loris/pull/3037/files
Might help it pass Travis

**Comment by kongtiaowang** [comment]
This failure may be caused by travis_CI,
I hope I can try to restart to fix it.

**Comment by driusan** [comment]
I think it's caused by the PR that @johnsaigle linked to. The VERSION file is displayed in the footer, so removing it is causing the tests to fail.

**Comment by ridz1208** [comment]
@driusan should we just merge the 2 PRs and send them as 1 ??

**Comment by johnsaigle** [comment]
@ridz1208 If you merge mine first and then rebase it should be fine.

**Comment by driusan** [comment]
Replaced by #3292

**Pull request closed without merging**
