### PR TITLE
[Redmine-11707] Fixing link of T1 Inserted 

### PR DESCRIPTION
**Pull request by kongtiaowang**
Adding the links for T1 Inserted which column is "Yes",
the links go to "/imaging_browser/viewSession/?sessionID=...".

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

does not work; page stays in the "Loading" phase

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

tested the link, still not enabled....

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

link works now

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

Shouldn't this go to 17.0.1 since it is a bug fix? please check with @LeighMac if this can wait to 17.1 because she requested this feature.

**Comment by alisterdev** [comment]
Module currently breaks on MySQL 5.7. This [PR](https://github.com/aces/Loris/pull/2494) seems to fix the issue, so I was able to test.

**Comment by ridz1208** [comment]
@kongtiaowang to 17.0

**Pull request closed without merging**
