### PR TITLE
[webpack] eslint-loader deprecated and replaced by eslint-webpack-plugin

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

The eslint-loader dependency has been deprecated and it's recommended to be replaced with eslint-webpack-plugin. I've added .eslintcache to the .gitignore rules.

The eslint-webpack-plugin package requires a newer version of eslint. The newer version of eslint has the .eslintrc.json use the extends array outside of rules. I'm unsure if the extends rules were ever being used before. Since, these errors are now being displayed:
```

 ERROR in 
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/CSSGrid.js
      63:31  error  'Cards' is missing in props validation          react/prop-types
      63:37  error  'Cards.length' is missing in props validation   react/prop-types
      64:32  error  'Cards' is missing in props validation          react/prop-types
      65:20  error  'Cards' is missing in props validation          react/prop-types
      65:29  error  'Cards[].Order' is missing in props validation  react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/Card.js
      52:20  error  'style' is missing in props validation     react/prop-types
      53:52  error  'style' is missing in props validation     react/prop-types
      55:20  error  'cardSize' is missing in props validation  react/prop-types
      56:40  error  'cardSize' is missing in props validation  react/prop-types
      65:34  error  'cardSize' is missing in props validation  react/prop-types
      71:25  error  'children' is missing in props validation  react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/DynamicDataTable.js
       31:4   error  Unnecessary semicolon                              no-extra-semi
      141:28  error  'Filter' is missing in props validation            react/prop-types
      142:38  error  'getFormattedCell' is missing in props validation  react/prop-types
      143:34  error  'freezeColumn' is missing in props validation      react/prop-types
      144:28  error  'onSort' is missing in props validation            react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/Form.js
        70:39  error  'children' is missing in props validation                                  react/prop-types
       106:30  error  'fileUpload' is missing in props validation                                react/prop-types
       197:39  error  'children' is missing in props validation                                  react/prop-types
       332:34  error  'sortByValue' is missing in props validation                               react/prop-types
       373:21  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
       533:34  error  'sortByValue' is missing in props validation                               react/prop-types
       562:21  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
       877:11  error  Missing "key" prop for element in iterator                                 react/jsx-key
      1201:10  error  'Modernizr' is not defined                                                 no-undef
      1466:20  error  'errorMessage' is missing in props validation                              react/prop-types
      1467:40  error  'errorMessage' is missing in props validation                              react/prop-types
      1709:36  error  'class' is missing in props validation                                     react/prop-types
      1942:36  error  'columnSize' is missing in props validation                                react/prop-types
      1946:35  error  'buttonClass' is missing in props validation                               react/prop-types
      2031:35  error  'element' is missing in props validation                                   react/prop-types
      2032:18  error  'element.ref' is missing in props validation                               react/prop-types
      2032:37  error  'element.name' is missing in props validation                              react/prop-types
      2033:18  error  'element.onUserInput' is missing in props validation                       react/prop-types
      2033:43  error  'onUserInput' is missing in props validation                               react/prop-types
      2037:26  error  'element.type' is missing in props validation                              react/prop-types
      2080:24  error  'element.type' is missing in props validation                              react/prop-types
      2159:30  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/Markdown.js
      5:23  error  'require' is not defined  no-undef
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/MultiSelectDropdown.js
       25:16  error  'toggleCheckbox' is missing in props validation         react/prop-types
       25:42  error  'label' is missing in props validation                  react/prop-types
       34:31  error  'checked' is missing in props validation                react/prop-types
       36:20  error  'multi' is missing in props validation                  react/prop-types
       40:29  error  'label' is missing in props validation                  react/prop-types
       49:33  error  'label' is missing in props validation                  react/prop-types
       76:16  error  'updateFilter' is missing in props validation           react/prop-types
       86:16  error  'updateFilter' is missing in props validation           react/prop-types
      105:31  error  'filter' is missing in props validation                 react/prop-types
      155:20  error  'multi' is missing in props validation                  react/prop-types
      156:32  error  'options' is missing in props validation                react/prop-types
      157:18  error  'onFieldClick' is missing in props validation           react/prop-types
      159:18  error  'onFieldClick' is missing in props validation           react/prop-types
      168:35  error  'options' is missing in props validation                react/prop-types
      169:23  error  'options' is missing in props validation                react/prop-types
      170:20  error  'onFieldClick' is missing in props validation           react/prop-types
      179:35  error  'options' is missing in props validation                react/prop-types
      180:22  error  'options' is missing in props validation                react/prop-types
      181:20  error  'onFieldClick' is missing in props validation           react/prop-types
      213:20  error  'multi' is missing in props validation                  react/prop-types
      214:30  error  'options' is missing in props validation                react/prop-types
      217:47  error  'options' is missing in props validation                react/prop-types
      223:35  error  'options' is missing in props validation                react/prop-types
      225:33  error  'multi' is missing in props validation                  react/prop-types
      228:26  error  'options' is missing in props validation                react/prop-types
      240:31  error  'multi' is missing in props validation                  react/prop-types
      250:31  error  'multi' is missing in props validation                  react/prop-types
      258:30  error  'options' is missing in props validation                react/prop-types
      261:47  error  'options' is missing in props validation                react/prop-types
      264:24  error  'options' is missing in props validation                react/prop-types
      264:37  error  'options[].toLowerCase' is missing in props validation  react/prop-types
      270:33  error  'options' is missing in props validation                react/prop-types
      271:35  error  'options' is missing in props validation                react/prop-types
      273:33  error  'multi' is missing in props validation                  react/prop-types
      284:22  error  'selectedCategory' is missing in props validation       react/prop-types
      287:34  error  'selectedCategory' is missing in props validation       react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/PaginationLinks.js
       58:34  error  'RowsPerPage' is missing in props validation  react/prop-types
       62:44  error  'Active' is missing in props validation       react/prop-types
       63:45  error  'Active' is missing in props validation       react/prop-types
       68:39  error  'RowsPerPage' is missing in props validation  react/prop-types
      103:22  error  'Active' is missing in props validation       react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/Panel.js
      75:36  error  'panelSize' is missing in props validation  react/prop-types
      85:38  error  'style' is missing in props validation      react/prop-types
      86:25  error  'children' is missing in props validation   react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/Password.js
      72:51  error  'inputName' is missing in props validation    react/prop-types
      73:50  error  'class' is missing in props validation        react/prop-types
      74:35  error  'placeholder' is missing in props validation  react/prop-types
    
    /Users/alizee/Development/GitHub/McGill/Loris/jsx/StaticDataTable.js
       51:22  error  'freezeColumn' is missing in props validation                              react/prop-types
       53:36  error  'freezeColumn' is missing in props validation                              react/prop-types
       95:22  error  'freezeColumn' is missing in props validation                              react/prop-types
       97:36  error  'freezeColumn' is missing in props validation                              react/prop-types
      194:21  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
      196:32  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
      217:31  error  'RowNameMap' is missing in props validation                                react/prop-types
      229:41  error  'Filter' is missing in props validation                                    react/prop-types
      230:32  error  'Filter' is missing in props validation                                    react/prop-types
      236:20  error  'Filter' is missing in props validation                                    react/prop-types
      236:27  error  'Filter.keyword' is missing in props validation                            react/prop-types
      318:22  error  'RowNameMap' is missing in props validation                                react/prop-types
      319:64  error  'RowNameMap' is missing in props validation                                react/prop-types
      377:20  error  'Filter' is missing in props validation                                    react/prop-types
      378:31  error  'Filter' is missing in props validation                                    react/prop-types
      378:46  error  'Filter[].value' is missing in props validation                            react/prop-types
      379:31  error  'Filter' is missing in props validation                                    react/prop-types
      379:46  error  'Filter[].exactMatch' is missing in props validation                       react/prop-types
      444:50  error  'freezeColumn' is missing in props validation                              react/prop-types
      446:59  error  'freezeColumn' is missing in props validation                              react/prop-types
      472:20  error  'Filter' is missing in props validation                                    react/prop-types
      472:27  error  'Filter.keyword' is missing in props validation                            react/prop-types
      504:49  error  'Filter' is missing in props validation                                    react/prop-types
      509:49  error  'Filter' is missing in props validation                                    react/prop-types
      566:20  error  'Filter' is missing in props validation                                    react/prop-types
    
    ✖ 111 problems (111 errors, 0 warnings)
      1 error and 0 warnings potentially fixable with the `--fix` option.
    

```
#### Testing instructions (if applicable)

1. delete node_modules and package-lock.json
2. npm install
3. npm run compile

### CODE REVIEW

**Comment by maltheism** [comment]
Added Blocked tag since needing to make PR that fixes the missing props validations.

**Comment by laemtl** [comment]
Blocked by #6947

**Comment by laemtl** [comment]
#6947 has been merged.

**Comment by driusan** [comment]
Does it need to be rebased? I'm not sure if the blocking PR was the reason it's failing CI or if they're unrelated and it needs work to fix the tests..

**Comment by driusan** [comment]
Actually it needs to be rebased regardless, there's a conflict in webpack.config.js

**Comment by maltheism** [comment]
Hi @laemtl & @driusan, I fixed by rebasing and it looks like eslint.json extends rules are being applied now that previously weren't. So travis is failing from the enforced eslint.json extends rules.

**Comment by laemtl** [comment]
Should we turn these rules off then?

**Comment by maltheism** [comment]
@laemtl good idea. I'll do that next week.

**Comment by maltheism** [comment]
@laemtl ready for review.

**Review by laemtl — APPROVED** [review]

**Comment by laemtl** [comment]
The plugin prints a warning

`Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
`

That can be disabled by adding the settings data below (.eslintrc.json)

```
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "settings": {
    "react": {
      "version": "detect"  // React version. "detect" automatically picks the version you have installed.
                           // You can also use `16.0`, `16.3`, etc, if you want to override the detected value.
                           // default to latest and warns if missing
    }                      // It will default to "detect" in the future
  },
  "env": {

```

**Comment by maltheism** [comment]
@driusan ready :)

**Pull request merged**
