### PR TITLE
[imaging_browser] fixed query for the imaging browser

### PR DESCRIPTION
**Pull request by cmadjar**
## Brief summary of changes

This fixes the query for the imaging browser by taking the ProjectID from the session table instead of the candidate table.

#### Testing instructions

1. Test that loading imaging browser on 22.0 fails
2. Test that after running the SQL patches it works again

#### Special note: 
The following patch (`SQL/New_patches//2019-07-01_add_projects_to_sessions.sql`) should be modified so that the `ProjectID` is populated correctly in the `session` table when studies have `scanner` candidates that are not associated to projects.
The update statement in that file should have been:
```
UPDATE session s JOIN candidate c ON s.CandID=c.CandID SET ProjectID=c.RegistrationProjectID WHERE PSCID != 'scanner';
```
@driusan @ridz1208 What should I do about this one? Should I create a new patch or just modify the one with the update since this is from a patch for that release? Let me know.

### CODE REVIEW

**Comment by ridz1208** [comment]
@cmadjar modify the same patch
once its merged I'll make the release patch

**Comment by driusan** [comment]
Yeah, modify the patch since it hasn't been released.

**Comment by cmadjar** [comment]
Patch updated.

Note: modified the column RegistrationProjectID to have default NULL as well since this is how it is defined in the default schema and NULL is needed for the scanner candidates for that field

**Comment by zaliqarosli** [comment]
@driusan @kongtiaowang @cmadjar has this been pulled on the testing vm yet?

**Comment by kongtiaowang** [comment]
@zaliqarosli it has been updated on testing VM.

**Comment by kongtiaowang** [comment]
This PR failed on testing VM.

**Comment by zaliqarosli** [comment]
:(

**Comment by zaliqarosli** [comment]
@kongtiaowang you ran the patch?

**Comment by kongtiaowang** [comment]
@zaliqarosli I ran the 0000-00-00-schema.sql.

**Comment by cmadjar** [comment]
@zaliqarosli @kongtiaowang should be fixed now that #5528 has been merged in 22.0-release :). It was a separate bug that I did not catch cause I still had the `mri_acquisition_dates` table that was deleted from the database as useless.

**Pull request merged**
