### PR TITLE
[behavioural_qc] pagination fix

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Replaced old code with <PaginationLinks> component.

#### Testing instructions (if applicable)

1. Test the pagination of the behavioural_qc module

#### Links to related tickets (GitHub, Redmine, ...)

* https://github.com/aces/Loris/issues/5505

### CODE REVIEW

**Comment by ridz1208** [comment]
@HenriRabalais please do manual tests

**Comment by sruthymathew123** [comment]
@maltheism @driusan Tested and looks good to me.
Screen Shot 2019-11-14 at 9 08 53 AM

**Comment by driusan** [comment]
@maltheism this has conflicts

**Comment by maltheism** [comment]
@driusan I fixed the conflicts

**Pull request merged**
