### PR TITLE
Ajax login

### PR DESCRIPTION
**Pull request by jstirling91**
As we move towards using more and more react, we are tending to use more ajax calls instead of page loads. This can become problematic when the users session has timed out and a 401 error is returned from the serve. Currently our pages don't handle this error accordingly.

To fix the issue, a generic error handler is introduced in this pull request to handle all 401 errors when using ajax. It works by having a pop out login for users to login without losing their current work the have been doing in the various react modules. 

This current implementation doesn't resend the failed ajax call, users will have to trigger the call again but atleast they won't loose all their work they did.

### CODE REVIEW

**Comment by driusan** [comment]
@alisterdev Can you review this?

**Comment by alisterdev** [comment]
@driusan Yes, but how does one test session timeouts without waiting for them?

**Comment by driusan** [comment]
You can set your timeout to a very small value in your php.ini

**Comment by alisterdev** [comment]
@jstirling91 When trying to upload a file through AJAX when my session is expired, I get this in response instead of a popup
image

**Comment by alisterdev** [comment]
@driusan Final review/merge?

**Pull request merged**
