### PR TITLE
[User account] Fixes user name containing a space

### PR DESCRIPTION
**Pull request by maltheism**
### Brief summary of changes

Solves the 500 error for username with spaces.

### This resolves issue...

- [ ] Redmine? #

- [x] Github? #4742

### To test this change...

- [x] Make user containing a space and see issue details for more information.

### CODE REVIEW

**Comment by nicolasbrossard** [comment]
@driusan do we want to allow user names that contain spaces? Are there any special characters that are not allowed?

**Comment by johnsaigle** [comment]
It might be good to limit it to alphanumeric characters for simplicity.

**Comment by driusan** [comment]
I don't know if we want to allow spaces. It seems like a security problem that could let people impersonate other people if not handled carefully.

**Comment by nicolasbrossard** [comment]
@maltheism can you please update your PR so that user names with non-alphanumeric characters are not allowed? I'll review/test once you are done

**Comment by ridz1208** [comment]
I'm with @driusan on this one, spaces in usernames are not a good idea.

**Comment by nicolasbrossard** [comment]
Has been replaced by #4888

**Pull request closed without merging**
