### PR TITLE
[Genomics] Uploader now showing error message (on error)

### PR DESCRIPTION
**Pull request by xlecours**
This pull request redo the message handling and now display the error message (on error)

It include an inelegant way of handling empty response body.

### CODE REVIEW

**Comment by ridz1208** [comment]
https://redmine.cbrain.mcgill.ca/issues/12634

**Comment by johnsaigle** [comment]
Tested and it works for me.

**Comment by ridz1208** [comment]
@xlecours eslint issues

**Comment by ridz1208** [comment]
@johnsaigle did you review or only test ?

**Comment by xlecours** [comment]
this is cover by https://github.com/aces/Loris/pull/2932

**Pull request closed without merging**
