### PR TITLE
[WIKI] datadict trait and version update

### PR DESCRIPTION
**Pull request by ridz1208**
## Brief summary of changes
updating wiki to include the LorisFormDictionaryImpl trait and updating the version for the release

### CODE REVIEW

**Comment by ridz1208** [comment]
@christinerogers any other places need updating ?

**Comment by christinerogers** [comment]
@ridz1208 ok if i just unassign myself and say it's passed review?

**Review by christinerogers — APPROVED** [review]
lgtm @ridz1208  - approving

**Comment by christinerogers** [comment]
resolves #8094

**Pull request merged**
