### PR TITLE
[Travis] increase memory

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes
increase memory for Docker PHP container

#### Testing instructions (if applicable)
Travis

### CODE REVIEW

**Comment by johnsaigle** [comment]
What does this do? Is it going to speed up Travis? Were there memory issues?

**Comment by driusan** [comment]
Yeah, why does Travis need more memory? If something in LORIS is eating memory we should investigate what and fix the root cause..

**Comment by kongtiaowang** [comment]
@johnsaigle @driusan It only happens in Testing Docker system #5835.  
Loris works fine on VM.
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in <b>/app/src/Data/Table.php</b> on line <b>84</b><br />

**Comment by johnsaigle** [comment]
Is there a specific test that is using all of that memory and causing that failure?

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/5835 has been fixed.  I will close this PR

**Pull request closed without merging**
