### PR TITLE
[Modules] Sites/Project/subproject filters populated according to user's permission

### LINKED ISSUE #6691: [Imaging Browser] project filter ComboBox shows all projects (including the ones the user doesn't have permissions to see)
**Describe the bug**
This seems to be a minor issue.

The `Project filter ComboBox` shows all projects (including the ones the user doesn't have permissions to see). In the other hand the results for querying projects where the user doesn't have permissions are not been shown in the result table which is a good thing. 

**To Reproduce**
1. Go to Imaging -> Imaging Browser
2. Click on the `Project ComboBox`
3. The user is able to see and choose projects it doesn't have permission to access.

**What did you expect to happen?**
In step number 3 the user should be able to see and choose only from the project it have access.

### PR DESCRIPTION
**Pull request by laemtl**
This PR:
1. modifies the way project/subproject/site filters are populated. Now those filters are displayed with values the current user has permission for.
2. fixed the data table for some modules, to remove entries for Projects and Sites the user does not have access to.
3. add some integration tests

## To test
* Visit all the modules and check that all data entries belong to sites and projects the user has access to.
* Visit all the modules and check that the site/project/subproject menu filters contain entries the user has access to.
* Modified modules:
    - behavioural_qc 
    - candidate_list
    - media
    - new_profile
    - statistics
    - user_accounts
    - survey_accounts

Related to #6829
Related to #6729

### CODE REVIEW

**Comment by laemtl** [comment]
MRI test integration are failing:

1) MriViolationsTestIntegrationTest::testNotResolvedSearchButton
Facebook\WebDriver\Exception\UnexpectedJavascriptException: TypeError: document.querySelector(...) is null
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: '720892ba3c5b', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1028-gcp', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 57.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 12580, moz:profile: /tmp/rust_mozprofile.ghzvUB..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1028-gcp, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 2652331f-8afd-4203-85c4-675a2a52ba1e
/app/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:183
/app/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:376
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:590
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:334
/app/modules/mri_violations/test/mri_violationsTest.php:675
/app/modules/mri_violations/test/mri_violationsTest.php:507
2) MriViolationsTestIntegrationTest::testNotResolvedSaveButton
Facebook\WebDriver\Exception\UnexpectedJavascriptException: TypeError: document.querySelector(...) is null
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: '720892ba3c5b', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1028-gcp', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 57.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 12687, moz:profile: /tmp/rust_mozprofile.Y69Kyw..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1028-gcp, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: c56ae5ce-2096-4fc2-bf89-dd72b1fc5e8b
/app/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:183
/app/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:376
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:590
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:334
/app/modules/mri_violations/test/mri_violationsTest.php:550
3) MriViolationsTestIntegrationTest::testResolvedSearchButton
Facebook\WebDriver\Exception\UnexpectedJavascriptException: TypeError: document.querySelector(...) is null
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: '720892ba3c5b', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1028-gcp', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 57.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 12788, moz:profile: /tmp/rust_mozprofile.aFgv8Z..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1028-gcp, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 934c5d68-437a-4ed4-b7ca-a36bf722c005
/app/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:183
/app/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:376
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:590
/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:334
/app/modules/mri_violations/test/mri_violationsTest.php:675
/app/modules/mri_violations/test/mri_violationsTest.php:573
--
There was 1 failure:
1) MriViolationsTestIntegrationTest::testDashboardWidgetAllSites
Failed asserting that '174' contains "175".
/app/test/integrationtests/LorisIntegrationTest.class.inc:699
/app/modules/mri_violations/test/mri_violationsTest.php:619

**Comment by christinerogers** [comment]
general comment: this PR is intended to solve the problem that Users can currently see the names of Projects and Subprojects they shouldn't know about in menu filter dropdowns.  (And lets them select these Projects/subprojects to try to view their data.) 

@laemtl - who would you like to review this?  Or are you looking for input from Dave (e.g. on generalizing anything ot the DataFrameworkMenu class) before review?

**Comment by laemtl** [comment]
@christinerogers Except for my question in the description: 

> As per @christinerogers comment, it can be a good idea to move this snippet into a function to avoid code duplication. Is DataFrameworkMenu a good class candidate?

It is ready for review. The changes are currently implemented with code duplication.

**Comment by christinerogers** [comment]
@driusan @ridz just to re-iterate laetitia's question above, before we head too far down the code-review path
 -- Is there a better way to abstract this for all modules e.g. DataFrameworkMenu ?

**Comment by christinerogers** [comment]
@nicolasbrossard does this PR answer your question from the Loris meeting?  -- the Projects visible to the user don't yet correspond to user permissions but will be, once this is merged. 

If you're open to reviewing this PR to test it, that would be fantastic. 

p.s. this PR is still [looking for input from](https://github.com/aces/Loris/pull/6836#issuecomment-675558107) @driusan et al on whether this could be more centralized through the data framework.

**Comment by nicolasbrossard** [comment]
@christinerogers Thanks! I'll have a look this PM but it definitely seems related to what I observed.

**Comment by driusan** [comment]
The best way to abstract it for the DataframeworkMenu class would probably be to add it to getFieldOptions, perhaps with a helper function in the class that makes it easier to put the redundant code in one place

**Comment by nicolasbrossard** [comment]
@laemtl I'll review/test once this PR passes Travis.

**Comment by laemtl** [comment]
@nicolasbrossard It's not ready yet.. I will update you as soon as it is!

**Comment by nicolasbrossard** [comment]
@laemtl Thanks!

**Comment by laemtl** [comment]
Blocked by #6945 (Bvl_feedback cannot be tested).

**Comment by christinerogers** [comment]
Let's see if @haoweiqiu has time to help test this - just to pull this PR and check that all modules are correctly working according to this pr

**Comment by haoweiqiu** [comment]
Hi @christinerogers, I'll first finish Issue #7053 and see if I could help with this. Thank you!

**Comment by laemtl** [comment]
@haoweiqiu The PR is not ready for review yet, I will let you know.

**Comment by laemtl** [comment]
@haoweiqiu Ready for review!

**Comment by laemtl** [comment]
@ridz1208 @driusan Following today's discussion on project permissions, this PR addresses a few project permissions issues on different modules.

**Comment by laemtl** [comment]
@driusan @christinerogers Should I rebase this?

**Comment by driusan** [comment]
If you want it to not have 7 file conflicts..

**Comment by laemtl** [comment]
I will preferably rebase if this PR has a chance to be merged soon.

**Comment by christinerogers** [comment]
The bug this fixes is still critical in the Electrophysiology Browser -- Site permissions are not currently enforced without it.  

A smaller PR will be issued that will hopefully resolve this issue sooner.  
cc @laemtl

**Comment by laemtl** [comment]
EEG PR: #7400 
Blocked by #7400

**Comment by cmadjar** [comment]
@ridz1208 to rebase while @laemtl is away.

**Comment by ridz1208** [comment]
I rebased this PR. @laemtl in case any errors were made during the rebase this is your latest commit pre-rebase `17920246cc442d4bca8ccbd7d57274316e96158c`

The tests will most likely fail because phan is complaining that it cant find the getProjectOptions and getSiteOptions functions since they are not in `NDB_Page` here in this PR but instead in `DataFrameworkMenu` as it was done in #7400. So this PR still needs fixing.

**Comment by cmadjar** [comment]
@laemtl this is in your court. Thanks!

**Comment by laemtl** [comment]
@cmadjar @ridz1208 My plan is to split this PR into smaller ones. See #7535 and #7402.

**Pull request closed without merging**
