### PR TITLE
[issue_tracker] Remove navigation control panel

### PR DESCRIPTION
**Pull request by zaliqarosli**
fixes https://github.com/aces/Loris/issues/4851 and does some cleanup

### CODE REVIEW

**Comment by driusan** [comment]
I tested this and

1. The next and previous buttons are reversed
2. Even though it was there before, I don't really see much point in the sidebar. When is someone going to want to just go through all issues sequentially?

**Comment by zaliqarosli** [comment]
@driusan 
1. the buttons are not actually reversed .. it so happens that the issueIDs descend as you go through the data table
2. i can't answer this question as i have no experience using this module - im only fixing the bug. this may be a design question for projects.

**Comment by zaliqarosli** [comment]
https://github.com/aces/Loris/pull/4890 fixes the order in which the data table is sorted

**Comment by driusan** [comment]
Screen Shot 2562-06-17 at 16 39 52

This is how it loads by default.. when I click on "1" in the first row the url contains Issue ID "1" and the only option is "Previous".

**Comment by zaliqarosli** [comment]
@driusan #4890 fixes this

**Comment by driusan** [comment]
Needs to be retested with latest changes

**Comment by driusan** [comment]
Tested it.. it's not quite as pretty with the form being full page width, but it doesn't look really bad either, so I'll call it passed.

**Pull request merged**
