### PR TITLE
Push v20.3.0 into major

### PR DESCRIPTION
**Pull request by ridz1208**
PUSH code from v20.3.0 to the MAJOR branch

ALOT of conflicts, should be reviewed properly

### CODE REVIEW

**Comment by ridz1208** [comment]
@driusan @johnsaigle I dont get why phan is failing on lines that were not changed in this PR

**Comment by driusan** [comment]
Is this based on the 20.3 branch or the minor branch?

**Comment by ridz1208** [comment]
based on `major` and merged v20.3.0 into it

**Comment by ridz1208** [comment]
```
git checkout aces/major
git checkout -b PUSH_v20.3.0_INTO_MAJOR
git merge v20.3.0
git push origin PUSH_v20.3.0_INTO_MAJOR
```

**Comment by driusan** [comment]
Shouldn't the minor branch (which already has 20.3 merged into it)  be merged into major instead?

**Comment by ridz1208** [comment]
@driusan it doesnt change anythign at this stage they are pretty much equivalent

**Comment by driusan** [comment]
Okay, but in general I think we should be pushing minor into major after a release

**Pull request merged**
