### PR TITLE
[Travis] fix the test error in main branch

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes

- [ ] Have you updated related documentation?

#### Testing instructions (if applicable)

1.

#### Link(s) to related issue(s)

* Resolves #  (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by xlecours** [comment]
@kongtiaowang Do we know why `7 rows` was passing last week and now we need to look for `6` ?

**Comment by kongtiaowang** [comment]
@xlecours The "7 rows " got merged 4 days ago, after that Travis still failed. It didn't pass Travis.  I have tested it on Loris from 21 to main. " 6 rows " is correct. 
Screen Shot 2021-08-30 at 2 04 33 PM

**Comment by driusan** [comment]
do you have a link to the PR that the 7->6 was merged in?

**Comment by AlexandraLivadas** [comment]
@driusan The PR was #7318

**Pull request merged**
