### PR TITLE
Properly namespace php/installer and add to phan

### PR DESCRIPTION
**Pull request by driusan**
Add a real namespace to php/installer and remove it as an
exception from phan.

There is no good reason to pretend that the classes are
the same, so this no longer does so.

### CODE REVIEW

**Comment by driusan** [comment]
@kongtiaowang can you manually test the installdb part of the install process with these changes?

**Comment by maltheism** [comment]
@driusan I'm testing the installdb.php and I'm getting this error:
Fatal error: Uncaught Error: Class 'LORIS\Installer\PDO' not found in /Users/alizee/Development/GitHub/McGill/Loris/php/installer/Installer.class.inc:143 Stack trace: #0 /Users/alizee/Development/GitHub/McGill/Loris/htdocs/installdb.php(68): LORIS\Installer\Installer->checkSystemDependenciesValid() #1 {main} thrown in /Users/alizee/Development/GitHub/McGill/Loris/php/installer/Installer.class.inc on line 143

**Comment by driusan** [comment]
@maltheism thanks! I just fixed two references to PDO that were in the wrong namespace, can you pull the latest changes and try again?

**Comment by maltheism** [comment]
@driusan pulled and now getting this error:
Warning: simplexml_load_file(): I/O warning : failed to load external entity "../project/config.xml" in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Config.class.inc on line 96

Fatal error: Uncaught Exception: Could not load Loris config file ../project/config.xml in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Config.class.inc:99 Stack trace: #0 /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Config.class.inc(70): NDB_Config->load('../project/conf...') #1 /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Factory.class.inc(118): NDB_Config::singleton('../project/conf...') #2 /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/Smarty_hook.class.inc(44): NDB_Factory->config() #3 /Users/alizee/Development/GitHub/McGill/Loris/htdocs/installdb.php(221): Smarty_NeuroDB->__construct() #4 {main} thrown in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_Config.class.inc on line 99

**Comment by maltheism** [comment]
My IDE is reporting that "ext-simplexml is missing in composer.json more..." is missing when looking at line 96 in the libraries/NDB_Config.class.inc
I'll report back after adding the extension and running composer.

**Comment by maltheism** [comment]
@driusan An exception is thrown when there is no config.xml inside the project directory. Used to not be a problem if the file didn't exist.

**Comment by driusan** [comment]
@maltheism That's definitely a problem since installdb should only be used when config.xml doesn't exist.. I think I've fixed it by making the factory return the namespaced version when called from installdb. Can you try one more time?

**Comment by maltheism** [comment]
@driusan Installer.class.inc line 338 needs to be changed to:
$this->_updateConfig($DB, "JWTKey", \User::newPassword(64));

**Comment by driusan** [comment]
@maltheism thanks, done.

**Comment by maltheism** [comment]
@driusan I get an error when I attempt to visit Loris after the installation.

> ( ! ) Warning: PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'awickenheiser_sandbox.examiners' doesn't exist in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/Database.class.inc on line 683
> --
> 1 | 0.0230 | 405032 | {main}( ) | .../index.php:0
> 2 | 0.0306 | 415688 | NDB_Client->initialize( ??? ) | .../index.php:27
> 3 | 14.6866 | 661632 | User::singleton( ??? ) | .../NDB_Client.class.inc:188
> 4 | 14.6866 | 662032 | User::factory( ??? ) | .../User.class.inc:134
> 5 | 14.6893 | 672184 | Database->pselect( ???, ??? ) | .../User.class.inc:96
> 6 | 14.6893 | 673720 | Database->execute( ???, ???, ??? ) | .../Database.class.inc:711
> 7 | 14.6893 | 673720 | execute ( ??? ) | .../Database.class.inc:683
> 
> Fatal error: Uncaught DatabaseException: Table 'awickenheiser_sandbox.examiners' doesn't exist in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/Database.class.inc on line 686
> ( ! ) DatabaseException: Table 'awickenheiser_sandbox.examiners' doesn't exist in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/Database.class.inc on line 686
> Call Stack
> #	Time	Memory	Function	Location
> 1	0.0230	405032	{main}( )	.../index.php:0
> 2	0.0306	415688	NDB_Client->initialize( ??? )	.../index.php:27
> 3	14.6866	661632	User::singleton( ??? )	.../NDB_Client.class.inc:188
> 4	14.6866	662032	User::factory( ??? )	.../User.class.inc:134
> 5	14.6893	672184	Database->pselect( ???, ??? )	.../User.class.inc:96
> 6	14.6893	673720	Database->execute( ???, ???, ??? )	.../Database.class.inc:711

**Comment by driusan** [comment]
Thanks, looks like adding the namespacing is adding more issues than I expected.. I'll investigate

**Comment by maltheism** [comment]
@driusan investigating myself and I think it maybe is because this query is running in the Database.class.inc on line 704.

> SELECT e.full_name,
>                     epr.centerID,
>                     e.radiologist,
>                     epr.active,
>                     epr.pending_approval
>                   FROM examiners e
>                   JOIN examiners_psc_rel epr ON (e.examinerID=epr.examinerID)
>                   WHERE e.full_name=:fn
>                     AND (epr.active='Y'
>                           OR (epr.active='N' AND epr.pending_approval='Y')
>                         )

I'm not sure if this is the case but when looking at users table in the database, it seems like there is no 
"full_name" anymore but instead "Real_name" which I think is the problem.

**Comment by driusan** [comment]
Was the schema properly sourced and the tables are all there properly?

**Comment by maltheism** [comment]
@driusan I installed with an empty database and the installdb.php didn't report any errors. I assume everything was properly sourced and the tables look all created with values in the fields.
database

**Comment by driusan** [comment]
There seems to be a few tables missing (ie. the examiners table isn't in the list of tables on the left hand side of your screenshot, but various other tables from the same file are..) can you manually run the create table statement for the examiners table from 0000-00-00-schema.sql and see if you get any error?

**Comment by maltheism** [comment]
@driusan That fixed it. I'm wondering why the installdb.php didn't successfully execute all the create tables. No error message was reported.

**Comment by maltheism** [comment]
@driusan Yah when manually running the queries it works. I just tried the installdb.php script into a clean database and same errors occurred when clicking the visit Loris link after the installation.

**Comment by driusan** [comment]
Can you source the schema files individually into a clean database and see if there are any errors that scroll by?

**Comment by maltheism** [comment]
@driusan There are no errors when I copy & paste, and run the queries into a clean database.

**Comment by maltheism** [comment]
@driusan I apologize because today I tested the installation and it apparently works when visiting the homepage. I believe my regular mysql user must not have the correct permissions. I tested the installation with the regular mysql user as root (all permissions) and all the queries ran successfully. So I believe my regular user must not be configured correctly.
LGTM

**Comment by johnsaigle** [comment]
Needs another PHPCS

**Pull request merged**
