### PR TITLE
Push v21.0.3 into 22.0

### PR DESCRIPTION
**Pull request by ridz1208**
Conflicts
	both modified:   README.md
	both modified:   modules/statistics/php/stats_mri.class.inc
	both modified:   tools/install.sh

please review carefully the install script, conflicts were not obvious to resolve

### CODE REVIEW

**Comment by driusan** [comment]
Travis isn't happy.

**Comment by ridz1208** [comment]
@driusan fixed it, let's see if it passes

**Comment by driusan** [comment]
The branch is pushing this into 23.0, not 22.0

**Comment by ridz1208** [comment]
@driusan changed base... not sure if travis needs to be rerun though

**Comment by christinerogers** [comment]
@kongtiaowang lets review the install script merges -- there is likely an error somewhere

**Comment by driusan** [comment]
I looked at the install script diff and it incorporates the latest changes that there were PRs for.

**Pull request merged**
