### PR TITLE
[tools] support JSON instruments in fix_candidate_age.php

### LINKED ISSUE #8090: [Tools/ fix_candidate_age] Script offers no support for JSON data intruments
**Describe the bug**
Several checks in `fix_candidate_age.php` make it fail for any instrument that does not save it's data into a MySQL table. These checks should be removed and the script converted to using the instrument class for all data fetching and saving.

### PR DESCRIPTION
**Pull request by CamilleBeau**
## Brief summary of changes

- [x] Have you updated related documentation?

#### Testing instructions (if applicable)

1. Run this script on instruments with and without SQL tables
2. Manually modify a "Date_taken" value in the SQL table and/or flag table
3. Run the script again and make sure that the value is modified correctly
4. Manually modify a "Candidate_Age" value in the SQL table and/or flag table to be null
5. Run the script again and make sure that the value is modified correctly
6. Check the script with both "check" and "confirm" 

#### Link(s) to related issue(s)

* Resolves #8090

### CODE REVIEW

**Comment by ridz1208** [comment]
@driusan this should probably go to 24.1, please confirm

**Comment by driusan** [comment]
@ridz1208 agreed

**Comment by ridz1208** [comment]
@CamilleBeau rebased. just needs testing/review

**Review by AlexandraLivadas — APPROVED** [review]
Tested on both a JSON and non-JSON instrument and with both `check` and `confirm`. Everything is working as expected/specified!

**Pull request merged**
