### PR TITLE
Allow LorisForm date field to use the M-Y format; no day.

### PR DESCRIPTION
**Pull request by tedstrauss**
Reference about 
http://www.htmlgoodies.com/html5/markup/working-with-the-new-html5-month-input-types-attribute-in-your-apps.html#fbid=Cqdkz4dPoix

### CODE REVIEW

**Comment by tedstrauss** [comment]
works with quickform
screenshot from 2016-07-28 10 53 01

**Comment by tedstrauss** [comment]
LorisForm YM widget:

screenshot from 2016-07-28 10 57 23

**Comment by jstirling91** [comment]
I think this should go into 17.0 as people might use this format in certain instruments

**Comment by ridz1208** [comment]
NO WAYYYYYYYYYYY
BARTYYYY

**Pull request merged**
