### PR TITLE
Modularize Imaging Uploader

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
This adds a namespace and Module class to the imaging uploader module.
Like 'Media', the function display() had to be removed.

### CODE REVIEW

**Comment by driusan** [comment]
This has conflicts now.

**Comment by kongtiaowang** [comment]
@MounaSafiHarab It still shows Loading can't show the page.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

I added the Needs Rebase because I have to rebase it on @xlecours PR#3251

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this should load the page now and allow inserting one scan but not through auto launch.
Once #3251 is merged, I will re-base on it and this should allow auto-launch as well.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this should load the page now and allow inserting one scan but not through auto launch.
Once #3251 is merged, I will re-base on it and this should allow auto-launch as well.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this should load the page now and allow inserting one scan but not through auto launch.
Once #3251 is merged, I will re-base on it and this should allow auto-launch as well.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this should load the page now and allow inserting one scan but not through auto launch.
Once #3251 is merged, I will re-base on it and this should allow auto-launch as well.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this should load the page now and allow inserting one scan but not through auto launch.
Once #3251 is merged, I will re-base on it and this should allow auto-launch as well.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 
this should load the page now and allow inserting one scan but not through auto launch.
Once #3251 is merged, I will re-base on it and this should allow auto-launch as well.

**Comment by driusan** [comment]
@MounaSafiHarab This can be rebased now, the SPM is in.

**Pull request merged**
