### PR TITLE
Brainbrowser 2.5.5: More bug fix for HDF5 reader error: Redmine 13333

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
Sequel to #3068 and #3110,
based off of BrainBrowser latest pull request (technical details/description of the changes in the pull request by @rdvincent): https://github.com/aces/brainbrowser/pull/339 
that **will be** released once this PR is merged: https://github.com/aces/brainbrowser/pull/340

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
Added the label 'Blocked' just to wait until 2.5.5 is officially released on aces/brainbrowser

**Comment by MounaSafiHarab** [comment]
@davidblader 
I believe CCNA is the only project experiencing this issue; more specifically with the HMC candidates. Can you test this please? I already did on the HMC as well as all other sites, and all looks fine. We now load everything without any HDF5 error thrown. But you can double check.
Pay attention to both structural modalities and those with time-dimension (resting state for example).

@Jkat @llevitis @sruthymathew123 
Can you please check that your existing scans load with this version of brainbrowser? One scan per site/candidate would be ideal.

**Comment by ridz1208** [comment]
@MounaSafiHarab is this minor or bugfix ??

**Comment by MounaSafiHarab** [comment]
> @MounaSafiHarab is this minor or bugfix ??

bugfix. When I created the branch, I was based off of bugfix. I just forgot to change the default pull request branch from minor. Done now. Thanks!

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

I don't understand why Travis is trying to source a test/RBData.sql and it can not find it. My changes here are clearly unrelated....

**Comment by MounaSafiHarab** [comment]
I will close this and issue a new one.
Travis does not want to update the branch to bugfix when it is doing its tests; it still uses code from the minor branch. So closing and re-issuing properly.

**Pull request closed without merging**
