### PR TITLE
Source the MINC tools path for brainbrowser

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
This gets the MINC tools path from the config.xml file.
CHANGES REQUIRED TO THE CONFIG.XML FILE for existing projects:
Add the following lines (where /opt/minc/ is where the MINC tools are installed in the example below; replace with the appropriate path):
    
    < MINCToolsPath >/opt/minc/< /MINCToolsPath >

Related to Loris-MRI Pull request 125:
https://github.com/aces/Loris-MRI/pull/125

### CODE REVIEW

**Comment by driusan** [comment]
Can you add the MINCToolsPath to the sample config.xml used at install time?

**Comment by MounaSafiHarab** [comment]
@driusan:

I did, and I updated the installation script.

**Comment by driusan** [comment]
I'm a little afraid that the way it's trying to determine the minc path using `which` is too clever and will come back to bite us later, but it looks like it should work. Also, shouldn't it check that the MINC_TOOLKIT_DIR isn't empty and/or check the error code before doing the replace in the config.xml? Otherwise, it'll work unexpectedly if the minc toolkit isn't installed.

Other than that, it looks good to me, but should probably have @Jkat sign off on it too.

**Comment by MounaSafiHarab** [comment]
@driusan @Jkat 
I can check if the minc tools are installed first (we do this in the Loris-MRI installation), but the problem is the assumption that MINC tools are installed at this point which is not true given that we are installing Loris not Loris-MRI.

The other problem is this error by Travis:
"ConfigurationException: Config setting MINCToolsPath does not exist in database in /home/travis/build/aces/Loris/php/libraries/NDB_Config.class.inc on line 288"
I thought we can either put in config.xml OR the database?

**Comment by driusan** [comment]
That's why I suggest checking either the error code returned by your `which` command (which I expect should be non-zero if there's an error), or if the variable is empty (since I'd expect it would have no output to stdout but send an error message to stderr if it's not found.)

**Comment by driusan** [comment]
Travis uses the config.xml in test/config.xml

```
- cp test/config.xml project/config.xml
```

**Comment by MounaSafiHarab** [comment]
@driusan @Jkat 

so now the Loris-MRI pull request (https://github.com/aces/Loris-MRI/pull/125) takes care of checking  the minc tools and whether they are installed and where, and then update the config.xml

**Comment by christinerogers** [comment]
Update:  since Loris-MRI can't assume access to config.xml, an instruction to manually add the config tagset has been added to the Loris-MRI Readme:  see https://github.com/aces/Loris-MRI/pull/123

**Pull request merged**
