### PR TITLE
[API] Make candidate images permission "protected"

### LINKED ISSUE #5341: Fix TypeError in new API code
@xlecours Don't know if this is in the purview of your PR but I get 500 errors on the candidate level for:
- put a new visit label that is not existent yet

Below is the log in the apache log for those errors if that helps:
> [Fri Oct 18 16:40:20.676397 2019] [php7:error] [pid 2425] [client 10.122.60.239:59394] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TimePoint::isValidVisitLabel() must be of the type int, string given, called in /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc on line 256 and defined in /var/www/loris/php/libraries/TimePoint.class.inc:265\nStack trace:\n#0 /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc(256): TimePoint::isValidVisitLabel('300328', 2, 'V3')\n#1 /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc(99): LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit->_handlePUT(Object(Zend\\Diactoros\\ServerRequest))\n#2 /var/www/loris/src/Middleware/ETag.php(73): LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit->handle(Object(Zend\\Diactoros\\ServerRequest))\n#3 /var/www/loris/modules/api/php/endpoint.class.inc(70): LORIS\\Middleware\\ETag->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit))\n#4 /var/www/loris/modules/api/php/endpoints/candidate/candidate.class.inc(119): LORIS\\Api\\Endpoint->process(Object(Zend\\D in /var/www/loris/php/libraries/TimePoint.class.inc on line 265

_Originally posted by @cmadjar in https://github.com/aces/Loris/pull/5326#issuecomment-543933478_

### PR DESCRIPTION
**Pull request by xlecours**
## Brief summary of changes
- Moving Phantoms and Scans filters in src
- Adding filters to the timepoint images provisioner

* force add `modules/api/php/endpoints/project` folder to git tracked files
* force add `modules/api/php/views/project` folder to git tracked files

fixes  #5341

### CODE REVIEW

**Comment by johnsaigle** [comment]
Needs PHPCS: `modules/api/php/endpoints/project/instruments.class.inc`

**Comment by cmadjar** [comment]
@xlecours Don't know if this is in the purview of your PR but I get 500 errors on the candidate level for:
- put a new visit label that is not existent yet
- get the imaging QC information
- put imaging QC information

Below is the log in the apache log for those errors if that helps:
```
[Fri Oct 18 16:35:47.240733 2019] [php7:error] [pid 5806] [client 10.122.60.239:59365] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TimePoint::isValidVisitLabel() must be of the type int, string given, called in /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc on line 256 and defined in /var/www/loris/php/libraries/TimePoint.class.inc:265\nStack trace:\n#0 /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc(256): TimePoint::isValidVisitLabel('300328', 2, 'V3')\n#1 /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc(99): LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit->_handlePUT(Object(Zend\\Diactoros\\ServerRequest))\n#2 /var/www/loris/src/Middleware/ETag.php(73): LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit->handle(Object(Zend\\Diactoros\\ServerRequest))\n#3 /var/www/loris/modules/api/php/endpoint.class.inc(70): LORIS\\Middleware\\ETag->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit))\n#4 /var/www/loris/modules/api/php/endpoints/candidate/candidate.class.inc(119): LORIS\\Api\\Endpoint->process(Object(Zend\\D in /var/www/loris/php/libraries/TimePoint.class.inc on line 265
[Fri Oct 18 16:35:48.191668 2019] [php7:error] [pid 19661] [client 10.122.60.239:59369] PHP Fatal error:  Uncaught Error: Class 'LORIS\\TimePointImagingQC' not found in /var/www/loris/php/libraries/TimePoint.class.inc:1074\nStack trace:\n#0 /var/www/loris/modules/api/php/endpoints/candidate/visit/qc.class.inc(124): TimePoint->getImagingQC()\n#1 /var/www/loris/modules/api/php/endpoints/candidate/visit/qc.class.inc(93): LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc->_handleGET(Object(Zend\\Diactoros\\ServerRequest))\n#2 /var/www/loris/src/Middleware/ETag.php(73): LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc->handle(Object(Zend\\Diactoros\\ServerRequest))\n#3 /var/www/loris/modules/api/php/endpoint.class.inc(70): LORIS\\Middleware\\ETag->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc))\n#4 /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc(140): LORIS\\Api\\Endpoint->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc))\n#5 /var/www/loris/src/Middleware/ETag.php(73): LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit->handle(Object(Zend\\Diactoros\\S in /var/www/loris/php/libraries/TimePoint.class.inc on line 1074
[Fri Oct 18 16:35:48.726286 2019] [php7:error] [pid 20088] [client 10.122.60.239:59371] PHP Fatal error:  Uncaught Error: Class 'LORIS\\TimePointImagingQC' not found in /var/www/loris/php/libraries/TimePoint.class.inc:1074\nStack trace:\n#0 /var/www/loris/modules/api/php/endpoints/candidate/visit/qc.class.inc(124): TimePoint->getImagingQC()\n#1 /var/www/loris/modules/api/php/endpoints/candidate/visit/qc.class.inc(206): LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc->_handleGET(Object(Zend\\Diactoros\\ServerRequest))\n#2 /var/www/loris/src/Middleware/ETag.php(84): LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc->ETag(Object(Zend\\Diactoros\\ServerRequest))\n#3 /var/www/loris/modules/api/php/endpoint.class.inc(70): LORIS\\Middleware\\ETag->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc))\n#4 /var/www/loris/modules/api/php/endpoints/candidate/visit/visit.class.inc(140): LORIS\\Api\\Endpoint->process(Object(Zend\\Diactoros\\ServerRequest), Object(LORIS\\api\\Endpoints\\Candidate\\Visit\\Qc))\n#5 /var/www/loris/src/Middleware/ETag.php(73): LORIS\\api\\Endpoints\\Candidate\\Visit\\Visit->handle(Object(Zend\\Diactoros\\Se in /var/www/loris/php/libraries/TimePoint.class.inc on line 1074
```

**Comment by xlecours** [comment]
@cmadjar good catch :) fixed

**Comment by cmadjar** [comment]
@xlecours oups... Forgot the access all profiles permissions. I would not change the way it works.

I retested the permissions to see the images and all is good! Approving the PR and adding pass manual test. 👍

**Comment by cmadjar** [comment]
@xlecours there is still the "Needs work" label on this PR. My guess is that everything was done but I would prefer that you confirm and remove the label yourself when you get a chance.

Thanks!

**Comment by johnsaigle** [comment]
@cmadjar I added it because of a PHPCS error which has since been fixed, so I'm removing it now.

**Pull request merged**
