### PR TITLE
[RestAPI] - Initial copy of v0.0.2

### PR DESCRIPTION
**Pull request by xlecours**
This PR make a copy of `htdocs/api/v0.0.2` as a starting point for further additions. It will make reviewing easier by allowing for diff in github.

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@xlecours 

if this gets merged, I assume my v0.0.3 pull requests can be rebased on this?
I am just not sure why you renamed the .md file in the docs/ directory.

**Comment by xlecours** [comment]
@mouna You are right. 
And the renaming is because we might keep multiple version concurrently. Should I rename v0.0.2 as well or only keep the latest version?

**Comment by driusan** [comment]
Can you rename it something like "v0.0.3-dev" instead of "v0.0.3" so that there's no ambiguity with the interim version(s) once (some form) of v0.0.3 goes into a release?

I also don't think there's much reason to copy the markdown file instead of just changing the version number in the existing one. Anyone who needs access to an older version already has the documentation that goes with it, and anyone with a newer version shouldn't be using the older one if they can avoid it.

**Comment by xlecours** [comment]
@driusan done

**Comment by driusan** [comment]
@xlecours I'll merge it once it passes Travis since there's no changes to existing code, so that the other PRs can be rebased

**Pull request merged**
