### PR TITLE
Prevent Javascript injection in User Account module

### PR DESCRIPTION
**Pull request by nicolasbrossard**

### CODE REVIEW

**Comment by driusan** [comment]
This is sent to the wrong branch.. please send it to master for 15.10

**Comment by nicolasbrossard** [comment]
Ok. How do I specify the target branch to be the master for 15.10 ?

**Comment by driusan** [comment]
Choose "master" in the dropdown for base branch when sending the pull request..

**Comment by driusan** [comment]
The request to master was merged, this one isn't needed.

**Pull request closed without merging**
