### PR TITLE
[Core] Add Compression middleware

### PR DESCRIPTION
**Pull request by driusan**
This adds support to LORIS for optionally compressing the response to the client if the `Accept-Encoding` header includes support for gzip using a new PSR-15 middleware. In this pull request the middleware is added for any data framework menu which uses the `format=binary` parameter and it used for the new data query tool results.

This can significantly improve the loading time of large datasets. For instance, when combined with PR#9195 on the UK biobank the size of the result downloaded from the candidate_list is reduced from 47.48MB to 7.45MB according to the Firefox dev tools and there are similar reductions in the transferred size for data query results with arbitrary queries.

### CODE REVIEW

**Comment by driusan** [comment]
Sending as a draft because this is not intended to be merged until after the current release.

**Review by maximemulder — APPROVED** [review]
Works on my machine, reduced `candidate_list` request from 60kb to 10kb depending on the `Accept-Encoding` HTTP header.

I would prefer if non-doc type annotations are added to `src/Http/GzipStream` (unless they are automatically inherited, in which case my bad !), before merging but not blocking on that.

I did a quick search to see if there are existing libraries that do that for us but I did not find any, I am kind of baffled we have to handle this kind of details ourselves.

EDIT: Uh, I thought I was only reviewing, why was I assigned ? Assigning back to @driusan unless there's something I overlooked.

**Comment by driusan** [comment]
@maximemulder you were just assigned to review so that it doesn't show up as unassigned.

What do you mean by "I would prefer if non-doc type annotations are added to src/Http/GzipStream"? I can update the docs, but I'm not sure what you mean.

**Comment by maximemulder** [comment]
Oh, I mean writing :
```
function tell(): int
{ ... }
```
instead of
```
/**
 * @return int
 */
function tell()
{ ... }
```
but if you prefer the later that's fine as well.

**Comment by driusan** [comment]
I would also prefer that but the signature needs to match the PSR7 StreamInterface that it implements

**Comment by maximemulder** [comment]
Oh okay, I did not take into account that the library could be untyped. If you're confident about your implementation of `StreamInterface` (since many methods are missing) then consider myself convinced.

**Pull request merged**
