### PR TITLE
fix the XSS attack issue in 23.0-release 

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes
https://mailman.bic.mni.mcgill.ca/pipermail/loris-dev/2024-September/001201.html
test from here http://wangshen-dev.loris.ca/login/request-account/

### CODE REVIEW

**Comment by christinerogers** [comment]
thanks shen! this replaces #9480 which isn't needed anymore, correct @kongtiaowang  ?

**Comment by kongtiaowang** [comment]
@christinerogers yes

**Comment by christinerogers** [comment]
Decision in the Loris meeting Dec 3- will not be merged since v23 is no longer supported, upgrade recommended. 
Cc @driusan @samirdas

**Comment by driusan** [comment]
See comment above. 23 is at least 3 major versions old and not supported, but this change is available as an experimental override for anyone who (unwisely) refuses to upgrade.

**Pull request closed without merging**
