### PR TITLE
[Proposal] Using factory->database across LORIS

### PR DESCRIPTION
**Pull request by xlecours**
This pull change all the calls to Database::singleton to NDB_Factory->databases
It is a step toward testability

### CODE REVIEW

**Comment by ridz1208** [comment]
@xlecours could you explain the difference between this and implementing a factory function in the database class ?

the way I see it is that like this we still need a factory singleton, if we had a factory function in the database class, no singleton is needed.

**Comment by xlecours** [comment]
@ridz1208 NDB_Factory is checking for `$this->Testing` which should be set to true when running tests and will return a MockDatabase object instead of a real one. The factory function is just renaming the singleton; unless you have something else in mind?

**Comment by ridz1208** [comment]
@xlecours I'm looking into similar changes for user->singleton, I'm just not sure if I should use user->factory() or factory->user() ...

**Comment by xlecours** [comment]
@ridz1208 I would recommande NDB_Factory->user($username). But only in the perspective of unit tests where the NDB_Factory can creat MockUser for testing.

**Comment by driusan** [comment]
@ridz1208 what's the difference between a class which is its own factory and a singleton?

**Comment by ridz1208** [comment]
@driusan I'm not proposing that the factory be a multiton, i.e. I'm not saying the factory should check for the existence of an already instantiated object and return it. I'm talking about a base factory that just always generates a new object given a set of parameters

example: `getRoleFromID(int $ID, Database $DB, User $u, ...)`

**Pull request closed without merging**
