### PR TITLE
EEGVisEnabled check issue and webpack cache

### PR DESCRIPTION
**Pull request by laemtl**
- Fix a WebpackMissingModule error with the EEGBrowser when EEGVisEnabled is set to "1" | "0" instead of "true" | "false".
- Turn the webpack cache to off as it contributes to the heap memory issues for users with less than 2GB Ram. In dev mode, all cache is stored in memory. Alternatively, if build speed is impacted, it can also be set to filesystem.

### CODE REVIEW

**Review by kongtiaowang — APPROVED** [review]
LGTM

**Comment by driusan** [comment]
What does "and webpack cache" mean? Why is the `cache: false` flag being set?

**Comment by laemtl** [comment]
Sorry, I forgot to explain that change in the description. Updated.

**Comment by driusan** [comment]
@GeorgeMurad can you test if this branch fixes your memory issue problems when running `npm run compile`?

@laemtl is there any reason *not* to change it to cache to the filesystem instead of disabling it entirely?

**Comment by laemtl** [comment]
> @laemtl is there any reason _not_ to change it to cache to the filesystem instead of disabling it entirely?
No, it might be a good option as well, maybe better.

**Comment by christinerogers** [comment]
resolution of this issue is critical to release for the EEG Browser (signal display breaks if not #9160 )

**Comment by GeorgeMurad** [comment]
> Member

I tested it and still have the same issue

**Comment by ridz1208** [comment]
@laemtl could you make the change for filesystem cache

**Comment by laemtl** [comment]
@ridz1208 Done

**Comment by driusan** [comment]
@laemtl the static tests are failing

**Pull request merged**
