### PR TITLE
[Request Account] Remove unused code, refactor logic, cleanup

### PR DESCRIPTION
**Pull request by johnsaigle**
This pull request tidies up the `request_account` code. 

- [x] Remove references to unused code (from when we had custom verification captchas)

- [x] Refactor logic to be more readable (I feel) and cover more of the request data

- [x] Add error logging for missing settings 

- [x] PHPCS

- [x] Update PHP version in comment 

 

 

 

It also removes the `verificationimage.php` which has been abandoned in favour of Google recaptchas.

### CODE REVIEW

**Comment by johnsaigle** [comment]
**Note**: add `w=1` when reviewing to hide whitespace changes.

**Comment by ridz1208** [comment]
just adding related PRs:

https://github.com/aces/Loris/pull/2856
https://github.com/aces/Loris/pull/2608

**Comment by johnsaigle** [comment]
@ridz1208 done

**Comment by driusan** [comment]
request_account has been moved into the login module as a separate page, this has conflicts and will need to be re-done (if it's still relevant, it may have already been cleaned up by converting to a different page..)

**Pull request closed without merging**
