### PR TITLE
[User account] Can't create user if Radiologist field is not set

### PR DESCRIPTION
**Pull request by kongtiaowang**
https://redmine.cbrain.mcgill.ca/issues/12972
Changing null value to 0.

### CODE REVIEW

**Comment by ridz1208** [comment]
@xlecours @kongtiaowang I'm not able to replicate the error,  was it fixed by this https://github.com/aces/Loris/pull/3015?

**Comment by driusan** [comment]
@ridz1208 @xlecours @kongtiaowang What do we do with this if the original bug can't be replicated? Does it get merged or closed?

**Comment by ridz1208** [comment]
@driusan I think it is reproducible with either strict settings on mariadb or basic settings on Mysql 5.7 I just needed to set up my env for it. I will test today.

**Comment by kongtiaowang** [comment]
@driusan @ridz1208 It is not replicated, https://github.com/aces/Loris/pull/3015 only fix pending_approval.

**Pull request merged**
