### PR TITLE
[Publication] Fixing Filename not displaying Issue

### LINKED ISSUE #6308: [Publications] File upload
Test Plan : 11

File upload goes through but when I try to download the file afterwards, it is not there, there is only an arrow to delete the file

### PR DESCRIPTION
**Pull request by sruthymathew123**
* Resolves #6308 
Filename not displayed even if the file is uploaded.
**Before Fix**
Screen Shot 2020-04-08 at 10 59 55 AM

**After fix**

Screen Shot 2020-04-08 at 11 16 15 AM

### CODE REVIEW

**Comment by maltheism** [comment]
@sruthymathew123 I just manually tested the PR and my File to upload looks different than your screenshot but the filename is there. I'm using chrome as the browser.

**Comment by ridz1208** [comment]
@maltheism can you attach a screenshot ?

**Comment by maltheism** [comment]
@ridz1208 
sn_testing

**Comment by ridz1208** [comment]
@maltheism and after you submit ?

**Comment by maltheism** [comment]
I receive "Submission Successful!" and then the Browse page looks like:
sn2
When I click on the View Project:
sn3

**Comment by driusan** [comment]
@pierre-p-s you reported the issue, can you confirm that it's fixed? The screenshots above all look like they're of different things to me..

**Comment by sruthymathew123** [comment]
@maltheism I think you need edit permissions edit project
Ref:``publication_users_edit_perm_rel`` and see if you permissions on that project.

**Comment by maltheism** [comment]
@sruthymathew123 thanks! I was using my admin account. I'm having an issue accessing user_accounts see here: #6343 and I'm unable to test with that permission until I can resolve this error.

**Comment by pierre-p-s** [comment]
> @pierre-p-s you reported the issue, can you confirm that it's fixed? The screenshots above all look like they're of different things to me..

Yes from the screenshots I think the issue is resolved.

**Pull request merged**
