### PR TITLE
[quality_control] fresh install fixed quality_control frontend errors

### PR DESCRIPTION
**Pull request by maltheism**
### Brief summary of changes

Fixed this problem:
Notice: Undefined variable: projectList2 in 
Loris/modules/quality_control/php/quality_control.class.inc on line 240

Also fixed frontend undefined errors for when no data exists on fresh install of LORIS.

Please comment if the error message displayed to the user when no data exists should be something else.

### To test this change...

- [x] Checkout PR on fresh install of LORIS.

### CODE REVIEW

**Comment by ridz1208** [comment]
@llevitis please review/test

**Comment by kongtiaowang** [comment]
php fatal error. mri_parameter_form' doesn't exist

**Comment by driusan** [comment]
@kongtiaowang there is a sample mri_parameter_form instrument in docs/instruments

**Comment by kongtiaowang** [comment]
@driusan For the fresh install Loris, there is not "mri_parameter_form" table in the schema.
And "mri_parameter_form" is hard coding in this module.

**Comment by kongtiaowang** [comment]
https://github.com/aces/Loris/pull/4800

**Comment by sruthymathew123** [comment]
@driusan QC module loaded fine on IBIS data set without any issues. I tested various redirection links( to dicom archive, imaging browser, MRI PF etc) in QC module as well. If @kongtiaowang pointed out issue is not an issue to concern now, all LGTM.

**Comment by driusan** [comment]
@sruthymathew123 if that's an approval can you mark it as such on GitHub?

**Pull request merged**
