### PR TITLE
[package.json] Upgrade react to version 18

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Upgrades react to version 18 and upgrade to latest rendering of react. See the following:
> ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

#### Testing instructions (if applicable)

1. checkout pr
2. make clean
3. make dev

### CODE REVIEW

**Comment by maltheism** [comment]
Hi @driusan and @laemtl  I tested removing the `{/* @ts-ignore */}` lines in the modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx and make dev completes without error. Should I commit that change in this PR?

**Comment by laemtl** [comment]
> @laemtl should this fix the TS errors/remove the ts-ignore markers?

No, the ts-ignore markers are fixing a package incompatibility with React 18 new types.

**Comment by maltheism** [comment]
Hi @driusan, Laetitia and I are going to test if we can remove the ts-ignore lines tomorrow. Latest commits have some changes concerning it.

**Comment by laemtl** [comment]
@maltheism The PR needs a rebase. Otherwise I tested it and it works, thank you so much for your help on this!

**Comment by maltheism** [comment]
@laemtl ready

**Review by laemtl — APPROVED** [review]

**Review by laemtl — APPROVED** [review]
One occurence left, in modules/imaging_qc/js/qualityControlIndex.js. How is generated this file?

**Pull request merged**
