### PR TITLE
Revert "[document_repository] fix no file under root folder "

### PR DESCRIPTION
**Pull request by kongtiaowang**
Reverts aces/Loris#6384

### CODE REVIEW

**Comment by driusan** [comment]
Why?

**Comment by kongtiaowang** [comment]
I make a mistake. I merge a PR by accident.

**Comment by lingma** [comment]
This PR has been merged, so what will happen now? You need to create a new PR? @kongtiaowang

**Comment by lingma** [comment]
It seems that the `8094dca` doesn't exist in this branch

**Comment by lingma** [comment]
Your revert won't happen since this PR has been closed. @kongtiaowang

**Comment by lingma** [comment]
oh, sorry I am wrong

**Pull request merged**
