### PR TITLE
 Import schedule module from IBIS to Loris 22.0-release

### PR DESCRIPTION
**Pull request by kongtiaowang**
Importing schedule module into Loris 22.0-release from IBIS.

Test: 
test plan

todo: 
sql patch file name

### CODE REVIEW

**Comment by johnsaigle** [comment]
The module also needs help text and it should be added to the CHANGELOG

**Comment by johnsaigle** [comment]
I think this should be based on the `master` branch not `22.0-release`

**Comment by kongtiaowang** [comment]
@johnsaigle This module is required by IBIS team to put it into 22.0-release.
Your comment is very helpful. There is only one thing ajax files need to be removed that I will do it on master branch, not in this PR. The rest of your comments I will fix them all in this PR.

**Comment by driusan** [comment]
@kongtiaowang The 22.0 release has already happened. It's far too late to add a new module to it.

**Comment by kongtiaowang** [comment]
@sruthymathew123 Where should this module go? Loris or IBIS. If you want to use it on 22.0 for IBIS, I will resent this PR to IBIS repo.

**Comment by sruthymathew123** [comment]
@kongtiaowang @driusan The main goal is to make use of this module Loris wide.

**Comment by kongtiaowang** [comment]
@sruthymathew123 @driusan Do I need rebase this? 22.0 or master?

**Comment by johnsaigle** [comment]
I think it should be rebased to master.

**Comment by driusan** [comment]
master, 22.0 is both already the branch it's based on and already released

**Comment by kongtiaowang** [comment]
Close this PR.  New PR should follow the new standard by https://github.com/aces/Loris/pull/6015.

**Comment by driusan** [comment]
There is no new standard in #6015. It's using the standards which have already been in place for a long time and were requested by @johnsaigle above.

**Pull request closed without merging**
