### PR TITLE
Sync package-lock.json with package.json

### LINKED ISSUE #4408: package-lock.json: To commit or not to commit?
This file should either be committed explicitly to the repo or explicitly included in our `.gitignore`. Right now it floats around between branches and causes warnings when switching.

I'm not sure on the best practices here because I'm not really involved with JavaScript, but a decision should be made.

### PR DESCRIPTION
**Pull request by johnsaigle**
Brings `package-lock.json` in sync with `package.json`. At some point the latter was changed without the former being committed to the repo.

Resolves #4408

### CODE REVIEW

**Comment by zaliqarosli** [comment]
not sure why mine and john's git diffs are different :/ could someone else run `make dev` and see what their git diff it?

**Comment by maltheism** [comment]
@zaliqarosli is right. I'm guessing my package-lock.json is similar to hers. @johnsaigle your package-lock.json has updated packages and I'm not sure why.

**Comment by johnsaigle** [comment]
The latest commit makes more sense than my initial one but I can't really comment on the accuracy of all of it

**Comment by driusan** [comment]
I have no idea how to review this. I guess I just assume it's good based on the reviews?

**Pull request merged**
