### PR TITLE
[login/RequestAccount] Add required to form fields

### PR DESCRIPTION
**Pull request by zaliqarosli**
fixes https://github.com/aces/Loris/issues/4512

### CODE REVIEW

**Comment by maltheism** [comment]
Hey @zaliqarosli awesome! 
I just tested this PR and there is one error preventing these changes from working. Basically in the php/libraries/LorisForm.class.inc on line number 790 needs to be changed to $el['required'] and similar for line number 793.

**Comment by maltheism** [comment]
I just searched all of LORIS to see if "requiredMsg" should be replaced anywhere else and just inside the LorisForm.class.inc contains this array key. All the locations besides the two line numbers I already listed above are 850, 1217, 1784, 1849. If these are updated to 'required' nothing should break.

**Comment by zaliqarosli** [comment]
@maltheism the issue is only a php notice for an undefined index so ive added an isset which removes the notice. i dont think any other changes is required

**Comment by kchatpar** [comment]
Looks good to me.

**Pull request merged**
