### PR TITLE
[Instrument Builder] updated module help text

### PR DESCRIPTION
**Pull request by knoll-alex**
New copy for the Instrument Builder module help text

#### Testing instructions

1. Review copy - note that I paired this one down a lot. I felt like the instructions were way too detailed, but I may have taken out too much. Let me know.
2. See screenshot

#### Links to related tickets

* https://github.com/aces/Loris/issues/5576

Screenshot 2019-11-14 15 19 19

### CODE REVIEW

**Comment by driusan** [comment]
This has both the "Needs Work" label and is Approved.. what's the work that needs to be done for this to be merged?

**Comment by christinerogers** [comment]
All of the field type descriptions were gutted. some need restoring.

**Comment by christinerogers** [comment]
@knoll-alex  - I corrected the sense of `Load` -- it doesn't install an instrument (from this module), it just opens an in-progress file.

**Comment by christinerogers** [comment]
Looks like we have 2 approvals. 
@johnsaigle  care to review? 
@driusan care to review, or merge when ready?

**Pull request merged**
