### PR TITLE
[BVL Feedback] CSS adjustments

### PR DESCRIPTION
**Pull request by davidblader**
BVL Feedback threads are unable to close for certain entries, e.g.,
image

I've changed the CSS, which used 500px as the width of the feedback panel, to use up approximately 35% of the screen space for when the panel opens which gives the inner content more breathing room
image

putting under bugfix because CCNA users are complaining about it

### CODE REVIEW

**Comment by zaliqarosli** [comment]
i'm trying to test this but not getting what i'm expecting. i'll make sure that it's not an issue with my front-end cache and report back

**Comment by zaliqarosli** [comment]
the changes seem to be backwards for me. on bugfix, i get no errors (the panel closes and tables all aligned). 
screenshot 2018-07-23 14 27 07

on this PR branch, the tables extend out when the space is too small. 
screenshot 2018-07-23 14 26 04
you might just need to add a horizontal scroll (carousel) on the tables to fix this

**Comment by HenriRabalais** [comment]
Based on @zaliqarosli's test, this PR `needs work`

**Comment by zaliqarosli** [comment]
everything works! but i think the "open thread summary" table should have a carousel on it (because the other tables on that page does and we should keep the UX consistent) and "Feedback Threads" table section should be horizontally scrollable! 

screenshot from 2018-08-13 11-50-31

**Comment by zaliqarosli** [comment]
@driusan this PR was not ready, it didn't passed manual testing. is there a reason it was merged?

**Comment by zaliqarosli** [comment]
ticket to target leftover bugs https://redmine.cbrain.mcgill.ca/issues/15186

**Pull request merged**
