### PR TITLE
Prevent Javascript injection in User Account form

### PR DESCRIPTION
**Pull request by nicolasbrossard**

### CODE REVIEW

**Comment by driusan** [comment]
What about the insert statements in htdocs/request_accounts/process_new_accounts.php?

**Comment by nicolasbrossard** [comment]
As far as Javascript injection is concerned, I think this statement is harmless. When the inserted values are fetched from the DB and used in a webpage they should be properly "escaped" in order to prevent malicious code from being executed though. Am I missing something ?

**Comment by xlecours** [comment]
It work for the first loading of the page. But as soon as I save changes, the "malicious" value isn't escaped anymore.

**Comment by nicolasbrossard** [comment]
Please provide steps to reproduce and I'll investigate

**Pull request merged**
