### PR TITLE
[Core] Notify.class.inc  change time() to date()

### PR DESCRIPTION
**Pull request by kongtiaowang**
This pull request changes time() to date() in Notify.class.inc.
In **notification_spool** table, TimeSpooled column is datetime type.
screen shot 2017-07-11 at 4 04 08 pm

### CODE REVIEW

**Comment by kongtiaowang** [comment]
@MounaSafiHarab could u test it? the save button
screen shot 2017-07-06 at 1 44 18 pm

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

I am curious about what you are asking me to test versus the pull request content? and is this specific to MYSQL5.7?

**Comment by kongtiaowang** [comment]
@MounaSafiHarab  Yes

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

I do indeed have an error on MySQL5.7. But although you pull request is logical, it does not fix the problem; I still get this error below:

mysql5p7

The fix to this is by doing something like:
`alter table files_qcstatus modify Selected enum('','true', 'false') DEFAULT NULL;`
do the same for the other column called `Selected` as well.

However, I want to bring in @driusan on this, and a comment he made a year ago on one of my pull requests (https://github.com/aces/Loris/pull/2136) :)

**Comment by kongtiaowang** [comment]
@MounaSafiHarab We should create another PR to fix the inserting null value into enum type in MySQL 5.7.

**Comment by MounaSafiHarab** [comment]
@kongtiaowang 

so your fix indeed fixes the time spooled problem IF we can get to it (any changes at the image level QC, Selected, and visit level QC status that set these values to blank would currently break the 'save' button).
But if we select anything other than NULL, then we can get to the error you are reporting, and your pull request changes fixes this second error!

**Comment by kongtiaowang** [comment]
@MounaSafiHarab  Could u put Pass Manual Test tag on this one?
The second Issue will be here https://github.com/aces/Loris/pull/2944

**Comment by MounaSafiHarab** [comment]
@driusan  
yes. It was just hard to test the changes by @kongtiaowang because I could not even get to his error, I got to my error which occurred earlier. I had to bypass the error I was getting (by assigning all fields that had NULL in the dropdown to some other option like pass/fail which was part of the enum in the column table in the database), then I got to the error @kongtiaowang is fixing and indeed, his changes fix the error of notification_spool table.

@kongtiaowang
just added it. sorry!

**Pull request merged**
