### PR TITLE
[raisinbread] Update RB with EEG chunks

### PR DESCRIPTION
**Pull request by cmadjar**
## Brief summary of changes

This adds the necessary EEG chunks path to the raisin bread database in order to be able to view the signals.

Note: the signals will be rsynced to the /data directory of raisinbread today.

#### Link(s) to related issue(s)

* This is related to #7387

### CODE REVIEW

**Comment by cmadjar** [comment]
@laemtl I copied the files on the raisin bread file system and you should find them in the /data-raisinbread mount on your sandbox for testing.

**Comment by cmadjar** [comment]
@driusan @ridz1208 @kongtiaowang  I have a feeling the Travis failure is unrelated to my changes but cannot decode the error. Could you take a quick look and let me know? Thank you!

**Comment by driusan** [comment]
@cmadjar it looks like it's passing to me?

**Comment by cmadjar** [comment]
@driusan wonderful!

**Pull request merged**
