### PR TITLE
[SQL] add column 'phone'  into 00-schema

### PR DESCRIPTION
**Pull request by kongtiaowang**
Base on this PR https://github.com/aces/Loris/pull/2503/files.
We should add column 'phone'  into 0000-00-schema.

### CODE REVIEW

**Comment by ridz1208** [comment]
@kongtiaowang I think @driusan usually likes to only add something when it is used in the code...

I will let him comment on this

**Comment by ridz1208** [comment]
ref to similar prev PR https://github.com/aces/Loris/pull/2737

**Comment by driusan** [comment]
I don't see the link between the PR linked in the description and a Phone column?

**Comment by kongtiaowang** [comment]
@driusan  My mistake, it should be this PR "https://github.com/aces/Loris/pull/2503/files".

**Pull request merged**
