### PR TITLE
JSLint-warnings

### PR DESCRIPTION
**Pull request by mohini-tripathi**
# Brief summary of changes

- [x] Have you updated related documentation?
- Removed all the JSLint warnings in the codebase that generates warnings in automated testing procedure.
- Changes are done in the configuration file which would remove function-missing-documentation warnings.
- Manual changes are done in the files having rest-param and no-console warning.
- Maximum Length for line increased from 80 to 250.

#### Testing Instructions
 ```npm run lint:javascript```
#### Link(s) to related issue(s)
Screen Shot 1942-01-14 at 11 39 21 PM

* Resolves # This fixes https://github.com/aces/Loris/issues/4138
#GSOC Aspirant
CC @christinerogers

### CODE REVIEW

**Comment by mohini-tripathi** [comment]
Referring to issue https://github.com/aces/Loris/issues/5973,  I want to ask if the clean up is required to be done in each file such as adding JS docs and cleaning files to not let them cross max-len 80 or changing parameters in the configuration file is supposed to solve the issue https://github.com/aces/Loris/issues/4138 ?

**Comment by PapillonMcGill** [comment]
@mohini-tripathi line length limit should stay at 80 chars.
Silencing the warning is not the solution. At least to the entire code base in one shoot. 
What should be done is fixing the code to clear the warnings 1 file/module at the time until all warning are gone.

@driusan may whish to comment more on that.

**Comment by mohini-tripathi** [comment]
@PapillonMcGill I will revert back the changes done in the configuration file and proceed to fix the code 1 file at a time.

**Comment by laemtl** [comment]
Replaced by #6756, #6761, #6762, #6764, #6769, #6857

**Pull request closed without merging**
