### PR TITLE
[Help Editor] Remove compiled Javascript file

### PR DESCRIPTION
**Pull request by johnsaigle**
This file is leftover from module Reactification and causes problems when switching branches after running `make dev`

### CODE REVIEW

**Comment by HenriRabalais** [comment]
Should the file simply be removed instead of adding it to git ignore?

**Comment by ridz1208** [comment]
@HenriRabalais both are necessary, the file already does not exist on the branch, but adding it to the git ignore prevents git from even tracking it on dev VMs

**Comment by ridz1208** [comment]
@johnsaigle by the same logic shouldn't the media module have a git ignore file  for the entire `js/*` directory ?

**Comment by johnsaigle** [comment]
@ridz1208 Yeah all new Reactified modules shouldn't be tracking the compiled JS files. This file just kept preventing me from switching branches so I was more aware of it.

**Pull request merged**
