### PR TITLE
[Core] New login page UI

### PR DESCRIPTION
**Pull request by alisterdev**
- [x] Redesign **login** page from scatch
- [x] Fully responsive UI
- [x] New version of logo (can be used on dark/blue background)
- [x] Redesign **password reset** page
- [x] Redesign **request account** page
- [x] Redesign **password expiry** page
- [x] Update favicon
- [x] Update lost password with a "thank you" message on succesful submit
- [x] Add ~browser check~ using modernizr (check for WebGL)
- [x] Change `All rights reserved`? to GPL-3.0
- [x] Rename Username references to email 
- [x] Add study name in the header (the bigger, the better)
- [x] [Add Google Captcha](https://github.com/aces/Loris/pull/2582) (separate PR)

---

**Before**  image | **After** 
image
--- | ---

### CODE REVIEW

**Comment by xlecours** [comment]
' © 2017. All rights reserved' is not there anymore. I don't know why it was there at the first place since it is open-souce

**Comment by alisterdev** [comment]
@xlecours I'm not sure if you are saying it should or should **not** be there. 
But, currently it is in the footer (not seen on the screenshot)

**Comment by xlecours** [comment]
Well, my point is that I'm not sure if it should be there. But if it is still there, I guess it is fine.

**Comment by alisterdev** [comment]
@xlecours I don't mind removing it, but for now I just tried to keep all the info that was present on the old login screen

**Comment by jstirling91** [comment]
@alisterdev Does the changes in the background colour affect the main page when you're logged in? If not should we maybe change the background colour in the main page to the one in the login to keep it consistent?

**Comment by jstirling91** [comment]
@alisterdev Does the changes in the background colour affect the main page when you're logged in? If not should we maybe change the background colour in the main page to the one in the login to keep it consistent?

**Comment by alisterdev** [comment]
@jstirling91 The background is slightly darker than white to make the panels stand out. I'm not sure it will fit well for all pages of Loris. I could test it in a separate PR

**Comment by jstirling91** [comment]
@alisterdev That would be good, I think the background css is set for the body element

**Comment by alisterdev** [comment]
Need to rebase of Dave's public module PR https://github.com/aces/Loris/pull/2564

**Comment by sruthymathew123** [comment]
@alisterdev I tested this on my VM. Great, all the features checked seems to be working.
But the things which I need to be clarified are;
1) Wrong version name apperasing in the footer (17.0 insted of 17.1)
2) Broken title for some pages like request account and 
screenshot from 2017-02-10 12 50 39
forgot your password

**Comment by alisterdev** [comment]
@sruthymathew123 
1. The version it uses is the one from VERSION file under root folder. Since this branch is pretty old, it show 17.0, but once we merge it it will show 17.1
2. Great catch, will fix

**Comment by sruthymathew123** [comment]
@alisterdev @driusan Tested on my VM and everything is working and seems to be good.

**Comment by alisterdev** [comment]
@driusan Please review and merge this. Note that most files changed are just new font/images files

**Comment by alisterdev** [comment]
@jstirling91 Can you pass code review for this, since Dave is on vacay?

**Pull request merged**
