### PR TITLE
[Test] Restore test_all_fields instrument for use in testing Instrument Manager

### LINKED ISSUE #5527: Missing .linst file(s) for proper Instrument Manager testing
TestPlan says:
```
4. Take the sample .linst instrument file `test_all_fields.linst` in `docs/instruments` and upload it in Instrument Manager.
```
but this file has since been removed.
Further down the test plan, it asks for another sample instrument file, but the contents should either be more explicit or perhaps the exact contents should be included with the whole raisinbread dataset.

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

This files used to exist in `docs/instruments` but were removed. I'm not sure why. I restored these files under `test/` instead of `docs/` because they seem more appropriate there.

If some of these files are no longer relevant, let me know and I'll selectively remove them. I feel that `test_all_fields` and the `bmi*` files are useful but I'm not sure about the others.

#### Links to related tickets (GitHub, Redmine, ...)

* Resolves #5527

### CODE REVIEW

**Comment by ridz1208** [comment]
@johnsaigle these tests were moved to raisinbread directory
and travis copies them from there to the project/instruments directory
since we decided to use RB ax an example project

**Comment by johnsaigle** [comment]
I think the LINST files are good at least? I can delete the rest. I couldn't find these ones in Raisinbread

**Comment by ridz1208** [comment]
only bmi is in LINST

UPLOAD TEMPLATE and TEMPLATE are in docs/instruments
bmi mri_parameter_form and radiology review are actual instruments so they are in raisinbread

**Comment by johnsaigle** [comment]
I removed everything except test_all_fields and the XIN stuff since everything else seems to be in Raisinbread now.

**Comment by driusan** [comment]
I don't see any way for just adding a sample linst file to break travis with no other changes, so I'm merging this despite travis not having started yet

**Pull request merged**
