### PR TITLE
[Core] UI update to jQuery datepicker

### PR DESCRIPTION
**Pull request by alisterdev**
- [x] Add month/year dropdowns 
- [x] Add placeholder text
- [x] Add datepicker for `<input type="month">` as it is used in some projects

image

### CODE REVIEW

**Comment by driusan** [comment]
Has anyone tested this?

**Comment by kongtiaowang** [comment]
need to fix -- after choosing one date , the date panel still there, it should be disappeared.

**Comment by alisterdev** [comment]
@kongtiaowang @driusan The panel would not disappear because of a JS error that was in the LorisForm code for the long time. Should be fixed now.

**Comment by alisterdev** [comment]
@driusan Shen tested this

**Comment by MounaSafiHarab** [comment]
@alisterdev 

it is fine for me (tested on chrome and firefox)

**Comment by MounaSafiHarab** [comment]
@alisterdev 
Just make sure the branch/milestone are consistent; it is now merged in 17.0-dev so I assume you meant the milestone is 17.0 as well?

**Pull request merged**
