### PR TITLE
[JSX] Adapt Border Thickness of Loader Component based on Size Prop

### PR DESCRIPTION
**Pull request by HenriRabalais**
## Brief summary of changes

This PR updates the border thickness of the Loader component based on the size of the loader.

### CODE REVIEW

**Review by laemtl — APPROVED** [review]

**Comment by laemtl** [comment]
@HenriRabalais Needs rebase.

**Comment by HenriRabalais** [comment]
changes integrated into #9439

**Comment by driusan** [comment]
@HenriRabalais conflicts because your other PR was merged

**Comment by HenriRabalais** [comment]
changes incorporated into #9439

**Pull request closed without merging**
