### PR TITLE
[Core] Added function User::getId()

### PR DESCRIPTION
**Pull request by AnyhowStep**
Just added a simple `getId()` function to class `User`. Surely, it can be useful?

### CODE REVIEW

**Comment by xlecours** [comment]
*YAGNI* Even if this seems legitimate, we try to merged stuff that is used and not the stuff that might be used.

**Comment by AnyhowStep** [comment]
But I am using it for the issue tracker. There's a pull request I want to make but I don't want it bounced because of this change.

**Comment by AnyhowStep** [comment]
Or I could just hack that other branch and use `$user->userInfo["ID"]` before making the pull request.
`User::$userInfo`is documented as `@access private` but it's clearly publicly accessible.

**Comment by johnsaigle** [comment]
Put this in a place where it's used to appease team.

**Pull request merged**
