### PR TITLE
[Sample MRI Parameter Form] Remove line disabling DB tracking

### PR DESCRIPTION
**Pull request by davidblader**
https://redmine.cbrain.mcgill.ca/issues/12648

adding Discussion Required since i think the entire file upload functionality in here is broken or outdated

### CODE REVIEW

**Comment by johnsaigle** [comment]
@davidblader can you provide some more details?

**Comment by davidblader** [comment]
> @davidblader can you provide some more details?

L#305: `$dir = $config->getSetting("UploadDir");`
causes an error, not sure if it's my database setup but i don't have any config setting named 'UploadDir'

there are a bunch of columns that it tries to insert into that are not listed in the instrument itself, namely File_name, File_type, and (x,y,z) vector elements

also generally unsure of how to test this since i'm not sure the file i'm using is compliant with whatever format it's expecting

**Comment by johnsaigle** [comment]
My understanding is that it's not meant to be run as-is. I think the Redmine is meant to just dissuade people from not tracking their changes.

All this to say, I don't think there's a problem here but perhaps @driusan can clarify.

**Comment by driusan** [comment]
You can email @LeighMac to ask for a sample mri parameter form file. I believe the sample MPF instrument comes from her project.

**Pull request merged**
