### PR TITLE
[Instrument builder] Test plan update

### PR DESCRIPTION
**Pull request by xlecours**
This update the test plan to remove the unachievable tests

### CODE REVIEW

**Comment by ridz1208** [comment]
shouldnt this go to the 20.0 branch ?

**Comment by johnsaigle** [comment]
@xlecours @driusan I took the liberty of making a commit to this PR. The markdown now renders correctly

**Comment by driusan** [comment]
thanks @johnsaigle, but it looks like it's still rendering all the sub-lists of point #1 incorrectly? https://github.com/xlecours/Loris/blob/33557ae21fcf5090ccaabfa277c7ab39f7b62430/modules/instrument_builder/test/TestPlan.md

**Comment by driusan** [comment]
We could just rename the file from TestPlan.md to TestPlan.txt, there's not really any necessary markdown formatting that couldn't be handled just as easily by a monospace font and reasonable line lengths.

**Comment by johnsaigle** [comment]
@driusan You're right. That's odd, I swear that it rendered properly at some point. I'll take a look at this when I'm back to work Monday.

I like the Markdown for consistency and readability. 😄

**Comment by PapillonMcGill** [comment]
@xlecours Have you tried to aligning the 1.c.1 label to the first text character of the previous line? 
4.a should be ok do.

Another point, some of the line have ending dots while others don't.

**Pull request closed without merging**
