### PR TITLE
Update PHPCS to latest version and fix detected errors

### PR DESCRIPTION
**Pull request by johnsaigle**
When reviewing files, it'll be helpful to **add `?w=1` to the URL** so that you hide whitespace-only changes. 

It will cut the files added/deleted to about 200 instead of ~5k.

----

## Brief summary of changes

1. Update PHPCS to latest version (composer.json and composer.lock)
2. Fix PHPCS errors detected by latest version
3. Resolve cyclical conflicts detected by new PHPCS version
4. Runs PHPCS on all files in php/, htdocs/, and modules/ at the same time so that `make checkstatic` catches all errors at once (both locally and on Travis).
    * Previously this was done once for php/ and then a second time for modules/. A failure in php/ would short-circuit the static analysis and errors from modules/ would be hidden until all the errors in php/ were resolved.
5. Adds colours to the output of PHPCS
 
As a part of the 3rd point above, I deleted the problematic `ArrayDeclaration` sniff and added the `DoubleArrowNotAligned` sniff, which was the main benefit of having ArrayDeclaration anyway.

I also added the `ArrayIndent` sniff. Together with the above change, this makes it so that array elements will be positioned at the next indent level.

The result is that code like this:

```php
// this scenario happens often... old phpcs rules (ArrayDeclaration sniff) wanted array keys to be 
// near the array() keyword. This results in long, hard-to-read lines that themselves
// can cause PHPCS "this line is too long" errors.
$myLongVariableName = array(
                      'key' => $this->_classVar = $someVeryLongSQLResultKey['level1']['level2'],
                      'key2' => ....
...
```

can now be written like this:

```php
// pretty new phpcs rules
$myLongVariableName = array(
    'key' => $this->_classVar = $someVeryLongSQLResultKey['level1']['level2'],
    'key2' => ....
...
```

This looks nicer and should hopefully resolve a lot of "this line is too long" errors in the future and save us a lot of time.

## Reviewing

As long as Travis works, this should be good to go.

### CODE REVIEW

**Comment by johnsaigle** [comment]
Right now this is succeeding on 7.3 but not on 7.2 and I'm not sure yet why this is happening

**Comment by johnsaigle** [comment]
LORIS PR assignments update: The files changed here are accurate; no rebase is necessary. The large number of files is due to changes in a PHPCS formatting of array declarations (detailed in the original post above). Since there are many files with arrays, many are affected.

I'll address the Travis errors soon.

**Comment by johnsaigle** [comment]
> [debug] Running '/home/travis/.phpenv/versions/7.2.15/bin/php' '-n' '-c' '/tmp/0DFvJn' 'vendor/bin/phan'
PHP Fatal error:  Cannot use the final modifier on an abstract class member in vendor/squizlabs/php_codesniffer/src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc on line 15
Fatal error: Cannot use the final modifier on an abstract class member in vendor/squizlabs/php_codesniffer/src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc on line 15
[debug] Restarted process exited 255
Makefile:26: recipe for target 'checkstatic' failed
make: *** [checkstatic] Error 255
The command "make checkstatic" exited with 2.

I'm not sure how to fix this error. It happens only on the PHP 7.2 branch and seems to be a problem not with our code but with the interaction between phan and phpcs.

Since PHP 7.4 will likely be required for the next major release (because we'll likely want to use typed class variables and because PHP 7.2 will be out of date soon), I'll eventually rebase this to major, or close it, and hopefully the issue will not reappear on 7.4.

**Comment by driusan** [comment]
I don't think PHP 7.4 will be required on the next major release. That's too far of a jump for our existing installs to do in one step.

**Comment by johnsaigle** [comment]
Fair enough, I guess I just assumed we would take advantage of the new features once they were available.

**Comment by johnsaigle** [comment]
This is now going to major since it changes a lot of files. It's mostly to do with spacing but still it's worth having everything be tested thoroughly.

**Comment by johnsaigle** [comment]
@driusan @cmadjar Re: LORIS Monday assignments:

This PR does not need to be rebased, as I posted above. Just wanted to make that clear so that it isn't skipped for more thorough review. Since this PR changes formatting, many files are meant to be affected. Reviewing the files, be sure to append `?w=1` in the address bar to see the non-whitespace changes only.

**Comment by johnsaigle** [comment]
I think this PR is somewhat mangled by rebasing and branch switching. Now that I know why Travis is failing I'm going to reopen a fresh PR.

**Comment by johnsaigle** [comment]
Closing in favour of simplified PR

**Pull request closed without merging**
