### PR TITLE
[data_release] Preventing Duplication of File Names

### LINKED ISSUE #6435: [data_release] uploading duplicate file causes strange behaviour
**Describe the bug**
When uploading a file with the same name of an existing file this happens:
1. a swal pops up saying only "Internal server error"
  ```
  [Mon Apr 27 13:58:46.358202 2020] [php7:error] [pid 25393] [client 127.0.0.1:43050] PHP Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/loris/php/libraries/Database.class.inc:818\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(956): Database->pselectRow('SELECT \\n       ...', Array)\n#1 /var/www/loris/modules/data_release/ajax/FileUpload.php(77)
  ```
2. after refreshing the page, the file uploaded twice shows up twice on the page (it does not get uploaded to the server, the file on the server is still the old one)
3. when downloading the file a network error occurs
   ```
   [Mon Apr 27 14:03:39.976028 2020] [php7:error] [pid 25661] [client 127.0.0.1:43122] PHP Fatal error:  Uncaught DomainException: Attempt to use pselectRow on a query that returns multiple rows in /var/www/loris/php/libraries/Database.class.inc:818\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(956): Database->pselectRow('SELECT ID FROM ...', Array)\n#1 /var/www/loris/modules/data_release/ajax/GetFile.php(40)
   ```

All this should be fixed by simpy displaying a swal sayieng would you like to overwrite the file or cancel

### PR DESCRIPTION
**Pull request by HenriRabalais**
## Brief summary of changes
This PR Prevents the duplication of file_names in the data_release table. If there is an attempt to submit a filename that already exists in the table, the user is given the option of overwriting the previous entry.

#### Testing instructions
Part 1
1. Upload a file to data_release.
2. Upload file with same name but different content.
3. Make sure a swal appears asking whether you want overwrite the file.
4. Overwrite file and make sure of it by downloading the new resource.

Part 2
1. Upload file as user who is not super user.
2. Remove permission to that file for that user.
3. Have that user try to overwrite the file.
4. Receive "Forbidden" error message.
5. Repeat steps 1-4 with super user. They should be able to overwrite the file even if they don't have permission for it.

#### Link(s) to related issue(s)
* Resolves #6435

### CODE REVIEW

**Comment by maltheism** [comment]
@HenriRabalais passed my manual testing.

One thing I noticed that might be worth commenting is if a file with the same name exists but has an older version. The newer version of the file with the same name overwrites and like the PR intends to solve the issue. I guess the only downfall I can predict is when a user still wanted access to the older version of the file. I'm assuming this is okay though. @ridz1208

**Comment by ridz1208** [comment]
@maltheism could you re-review/test please ?

**Comment by maltheism** [comment]
Hi @HenriRabalais, the swal doesn't seem to notify the user anymore when the upload is finished and the swal doesn't go away. The file is updated after refreshing the browser from testing.
henri

**Comment by HenriRabalais** [comment]
@maltheism That's strange. I just tested it on vm again and it's working. Would you be able to provide any more details? In the meantime I'll run some more tests.

**Comment by maltheism** [comment]
@HenriRabalais I just checked out your PR and tested with an existing file.

**Comment by HenriRabalais** [comment]
@maltheism Okay. Did it ask you whether you wanted to overwrite or not? Did you click accept? Did you click Cancel? Are there any messages in the console log or in the error log?

**Comment by maltheism** [comment]
@HenriRabalais I'll try it again.

**Comment by maltheism** [comment]
@HenriRabalais same experience after testing again. I'm first asked by the swal "Are you sure?" and I select "Yes, I am sure!" then it asks me "Are you sure?" about overwriting. I press the button "Yes, I am sure" and I just see the fields for Upload file become empty. My error_log is empty and similar to the console of the browser. The file does get uploaded and the changes are in the table if I quit out of the Upload file view to look.

**Comment by HenriRabalais** [comment]
@maltheism okay thanks for the details. I've removed the redundant second swal that asks if you want to overwrite the file a second time. For me though, once you click "Yes, I am sure" the file uploads, a swal appears saying "Upload Successful!" and then the page refreshes. I'm also using chrome.

**Comment by maltheism** [comment]
@HenriRabalais I'll try refreshing the rasinbread data and report back after testing.

**Comment by maltheism** [comment]
@HenriRabalais latest commit broke make

**Comment by maltheism** [comment]
@HenriRabalais the success swal happens for me when uploading a file that hasn't been uploaded. I don't see the swal when I upload the same file twice. I'm testing on my local development machine and so I'm going to test one more time on my VM.

**Comment by maltheism** [comment]
@HenriRabalais works on my VM. I'm unsure why the success swal doesn't happen on my development machine. In any case this PR solves the issue.

**Pull request merged**
