### PR TITLE
[API] Fix POST /candidates response format

### PR DESCRIPTION
**Pull request by xlecours**
### Brief summary of changes
The documentation of v0.0.3-dev differ from v0.0.2 for POST request sent to /candidates.
A `CandidateObject` should be returned instead of the CandID alone

This adds the CandidateObject to the response.

### This resolves issue...

- [x] Github? #4881 

### To test this change...
Send a POST request to /candidates and see if the response format fits the documentation

### CODE REVIEW

**Comment by driusan** [comment]
@cmadjar can you test this PR since you tested the API pretty thoroughly for the release?

**Comment by xlecours** [comment]
@cmadjar The documentation of v0.0.2 says that the candid will be returned upon creation. The v0.0.3-dev specs where changed but not the outputs

**Comment by cmadjar** [comment]
@xlecours Is it working for you using the API 0.0.2? I get the following returned when using 0.0.2:
```
{"error":"This API version does not support candidate creation by users with multiple site affiliations. This will be implemented in a future release."}
```

**Comment by xlecours** [comment]
@cmadjar Yes it work with a user that only have 1 site

**Comment by cmadjar** [comment]
@xlecours my bad... I should have read the error message better, sorry :S.

**Comment by xlecours** [comment]
@cmadjar No worries. It maid me find a bug :dancer:

**Pull request merged**
