### PR TITLE
[Survey] Fix loading of survey instruments

### LINKED ISSUE #8546: [Survey Accounts]Cannot Access Survey URL
**Describe the bug**
When you click on the Survey URL link, the page is broken with error message **No such module: instruments**

**To Reproduce**
Create a  survey and try to access the survey link form survey accounts
Screen Shot 2023-04-05 at 10 15 29 AM

**Server Environment (if known):**
- LORIS Version: [e.g. 25.0.0]
- Issue Found on https://test-dev-250.loris.ca/

### PR DESCRIPTION
**Pull request by driusan**
The module search path for survey instruments was incorrect. Set to the same search path as in tools/generic_includes.php

Resolves #8546

### CODE REVIEW

**Comment by driusan** [comment]
@sruthymathew123 can you test this since you reported the bug report? Not sure if you reproduced it locally or just on the test VM..

**Comment by sruthymathew123** [comment]
@driusan I found this bug on test VM; I will find sometime today or tomorrow to test this.

**Comment by sruthymathew123** [comment]
@driusan Instrument is loading ; but No Save Option 

Screen Shot 2023-04-19 at 2 02 25 PM

**Comment by driusan** [comment]
I finally got around to trying to fix this and I'm not able to reproduce. It's showing the save button for me! [first page of bmi including save button](https://github.com/aces/Loris/assets/498329/36c1c4e8-31e8-4788-b237-045c0597fe44)

**Comment by sruthymathew123** [comment]
@driusan Tested it gain and looks good now;  I don't know what happened last time. Anyway it is all good now

Screen Shot 2023-06-13 at 2 58 50 PM

**Pull request merged**
