### PR TITLE
[IssueTracker] status filter multiselect

### LINKED ISSUE #6517: [IssueTracker] ActiveIssues tab displays Status filter: Closed
In the Issue Tracker `v23` : The `Active Issues` tab displays `Closed` in the Status filter element because the tab automatically filters for all issues *not Closed* (details below). 

The actual filtering _logic_ works well & as intended, and the data table filters appropriately for only active issues (*not* Closed). So this is a minor bug but still something users shouldn't be seeing. 

* Seems to be introduced during Reactification (#4112) 

Source: Active Issues tab `filterPresets` are defined: `{value: 'closed', opposite: true}}},` in [issueTrackerIndex.js Line 211](https://github.com/aces/Loris/blob/23.0-release/modules/issue_tracker/jsx/issueTrackerIndex.js#L211): 
```php
{label: 'Active Issues', filter: {status: {value: 'closed', opposite: true}}}, 
```

Can you advise on another way to select "all issues except Closed", @HenriRabalais ?

To reproduce: 
* Open the Issue Tracker
* Click `Active` tab. `Closed` appears printed in the Status filter, but the issues in the data table are clearly all except Closed issues (i.e. active)

Tested and reproduced on Firefox and Chrome, Loris 23 on test-loris-dev.loris.ca and sandbox

Originally reported in #6141

### LINKED ISSUE #6527: [IssueTracker] Change the Status filter to be multiselect
In the Issue Tracker v23 : The Active Issues tab displays all issues not Closed.
The actual version displays closed in the status filter once Active Issues is selected, because under the hood, it uses a combo value: closed/opposite: true [see filterPresets](https://github.com/aces/Loris/blob/e8218d14b92bdaf7feb314110956604ae619e3ae/modules/issue_tracker/jsx/issueTrackerIndex.js#L209)

To solve this issue and enhance UI experience we can change status for a multiselect field and automatically select all status except closed.

Seems to be introduced during Reactification (#4112)

To reproduce:
Open the Issue Tracker
Click Active tab. Closed appears printed in the Status filter, but the issues in the data table are clearly all except Closed issues (i.e. active)
Tested and reproduced on Firefox and Chrome, Loris 23 on test-loris-dev.loris.ca and sandbox

Originally reported in #6141
Resolve #6521

### PR DESCRIPTION
**Pull request by laemtl**
In Issue Tracker v23.0
Minor changes to migrate the status filter to a multiselect one. 
status.value in filterPresets now takes an array of status.

* Resolves #6527 
* Resolves #6517

### CODE REVIEW

**Comment by HenriRabalais** [comment]
@laemtl I believe this should be closed in favour of the merged #6529

**Comment by laemtl** [comment]
@HenriRabalais I don't know if it's something related to new permissions, but the close option is not accessible anymore.

**Comment by ridz1208** [comment]
@HenriRabalais @laemtl this was merged 22 hours ago

**Comment by laemtl** [comment]
@ridz1208 thanks, I noticed the PR is closed so all good!

**Comment by HenriRabalais** [comment]
@laemtl @ridz1208 Oh weird, I totally thought I had comment that on #6521

**Pull request merged**
