### PR TITLE
[document_repository] fix no file under root folder 

### PR DESCRIPTION
**Pull request by kongtiaowang**
fix no file under root folder

Testing instructions (if applicable)
load the page, it will show all the files and all categories in the table.
compare with https://demo.loris.ca/document_repository/

Link(s) to related issue(s)
#6405

### CODE REVIEW

**Comment by kongtiaowang** [comment]
@pierre-p-s Could u test it PR?

**Comment by lingma** [comment]
But Dave has merged a similar one a few minutes ago. I am confused. `8094dca25cf4dae0a3d96d7b4f9f113c7eb71766`

**Comment by kongtiaowang** [comment]
@pierre-p-s  igonre that one.

**Comment by kongtiaowang** [comment]
@lingma It is not Dave, It is me.I merged it by accident.

**Comment by kongtiaowang** [comment]
this pr is from wrong repo.I will push it again.

**Pull request closed without merging**
