### PR TITLE
[Data Integrity Flag] Fix Clear Filter button

### PR DESCRIPTION
**Pull request by davidblader**
the Clear Filters button wasn't hooked up to any event listener so the filters did not clear but now they do

### CODE REVIEW

**Comment by intralizee** [comment]
LGTM

**Comment by ridz1208** [comment]
@intralizee please review

**Comment by intralizee** [comment]
@ridz1208 @davidblader I manual tested and LGTM.

**Comment by ridz1208** [comment]
@davidblader this one was continuously failing travis, I rebased and recompiled to try and solve the issue

**Comment by zaliqarosli** [comment]
^ should probably get retested since rebase

**Comment by HenriRabalais** [comment]
Passed Manual Test!

**Pull request merged**
