### PR TITLE
[create_timepoint] First visit in list automatically selected

### LINKED ISSUE #7728: [create_timepoint] First visit in list automatically selected
**Describe the bug**
When creating a new timepoint, as soon as a subproject is selected, the first visit in the list of visits is automatically chosen in the drop down. This is very error prone behaviour. the user must explicitly select a visit instead and not risk relying on the preselected value.

@CamilleBeau have you noticed this behaviour in your testing ??

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Solves issue: https://github.com/aces/Loris/issues/7728

#### Testing instructions (if applicable)

1. Visit create_timepoint module
2. Test for the bug

#### Link(s) to related issue(s)

* Resolves #7728

### CODE REVIEW

**Review by ridz1208 — DISMISSED** [review]

**Comment by ridz1208** [comment]
@maltheism what needs change on this one ?

**Comment by maltheism** [comment]
Hi @ridz1208, I believe you asked me to add code that has the select component automatically default to the first element if only one element exists.

**Comment by ridz1208** [comment]
oh yes, please thanks

**Comment by driusan** [comment]
Don't we already have that?

https://github.com/aces/Loris/blob/main/jsx/Form.js#L478-L480

**Comment by maltheism** [comment]
@ridz1208 the suggestion from @driusan will work.

**Comment by maltheism** [comment]
@ridz1208 ready

**Review by ridz1208 — APPROVED** [review]

**Pull request merged**
