### PR TITLE
[instrument_list] Add battery active check

### PR DESCRIPTION
**Pull request by lingma**
## Brief summary of changes

This PR add a test_battery active or not check.

#### Link(s) to related issue(s)

Request in the PR #6365 by @nicolasbrossard

### CODE REVIEW

**Comment by driusan** [comment]
Why are you trying to add this? The test battery shouldn't affect what's hows up in the instrument list. Instruments added to the flag table manually with the fix_timepoint_date_problems script should still appear in the list of that candidate's instruments.

**Comment by lingma** [comment]
I don't see the necessity, neither would this PR cause problem so I add the check.

**Comment by johnsaigle** [comment]
@ridz1208 This seems like an enhancement and potentially shouldn't be included in the release (since it's frozen)

**Comment by nicolasbrossard** [comment]
@driusan Maybe I am missing something but why are inactive instruments part of the list of that candidate's instruments? If they are, what's the point of inactivating an instrument in the test_battery table then?

**Comment by lingma** [comment]
I believe the test_battery Active status will only apply to the subsequent instruments, not previous ones.

**Comment by driusan** [comment]
The Active flag in the test battery is used to select which standard instruments get added to the candidate's instrument when the instrument is started. Instruments that are added to that candidate outside of the battery are still instruments that were administered.

**Comment by driusan** [comment]
This introduces a bug where some of some candidate's instruments would be inaccessible but doesn't fix anything.

**Pull request closed without merging**
