### PR TITLE
[Meta] Add PHP 8.1 and remove PHP 7.4 from GitHub actions

### PR DESCRIPTION
**Pull request by driusan**
PHP 8.1 is set to be released in a week. We should have our tests run with it.

### CODE REVIEW

**Comment by driusan** [comment]
Seems to be failing because of a bug with phpcs and php 8.1 (it's failing on a rule that's excluded by our ruleset) but I don't have php 8.1 locally to test with yet and it's not reproducing on 8.0 for me. Will wait and test after the official release..

**Comment by maltheism** [comment]
php 8.1 is released today

**Comment by maltheism** [comment]
@driusan I'm unable to view the modules of Loris on php 8.1 after fixing some of the fatal errors in PR: https://github.com/aces/Loris/pull/7889

Here's a screenshot of Loris loading on php 8.1 but without modules displaying:
Screen Shot 2021-12-07 at 12 13 56 PM

**Comment by driusan** [comment]
Sending a new PR, this was accidentally overridden with a force push.

**Pull request closed without merging**
