### PR TITLE
Fixed the 'no-warning-comments' ESLint warnings

### PR DESCRIPTION
**Pull request by AlexandraLivadas**
### Brief summary of changes
I made changes to some of the .js files so that when running "npm run lint:javascript" there would be less warning from eslint. 

### This resolves issue...

- [ ] Github? #4138 

### To test this change...

- [ ] Run "npm run lint:javascript"

### CODE REVIEW

**Comment by AlexandraLivadas** [comment]
@johnsaigle So far, I have only resolved the "no-warning-comment" warnings. I was unsure about our coding standards when it comes to line length and some of the issues were asking for jsdoc comments and I did not know enough about the code to write good comments.

@zaliqarosli @alisterdev @llevitisI @HenriRabalais @davidblader @cmadjar @xlecours @leothomas @jacobpenny @driusan : I made comment changes to some files that you authored. Please let me know if this is okay or if I should rollback some of the changes!

**Comment by davidblader** [comment]
lgtm

**Comment by zaliqarosli** [comment]
the 'TODO', 'FIXME' are important because they tell us that these are things we need to do / lines of code we need to fix. 'XXX' is also a way to highlight todo/fix. removing them will remove the context of these comments. these comments are here mostly for developers and less so actual documentation for the functions. i would maybe turn off 'no-warning-comments' than removing the comments? @johnsaigle i am curious what you think

**Comment by maltheism** [comment]
I think it would be best to leave the comments and even the warnings in regard to TODO, FIXME, XXX because it helps developers in remembering where to go for cleanup and fixes. That's kind of useful warnings compared to the countless warnings for function comments that haven't been generated when running npm run compile. 

One of these days I would like to go through the javascript files and make a comment with the necessary params to get rid of all those warnings for function comments. Then we will get one or two warnings that are actual reminders that we need to write a comment for a function and quickly do it instead of just ignoring the hundreds of warnings in front of us.

Anyway that's my opinion but I'm in favour of whatever people agree with.

**Comment by johnsaigle** [comment]
Yeah I agree with the others. I like the TODO/FIXMEs. They even have special syntax highlighting in certain dev environments so that they'll jump out to the author.

In terms of line length our ideal is 80 characters or less; this is strictly enforced in PHP via `phpcs` though only marked as a warning in `eslint`. 

Also, a few of the people you tagged don't work here anymore just as an FYI :) (Alex/alisterdev, davidblader, jacobpenny, and leothomas).

**Comment by johnsaigle** [comment]
And yes I agree with @zaliqarosli that `no-warning-comments` should be disabled instead.

**Comment by AlexandraLivadas** [comment]
I looked at the package.json file and it looks like we are using the Google configuration. I took a look at their latest configuration online and it seems like they do not allow these "warning comments". I think that in order for us to get rid of those warnings, we would need to write our own ESLint configuration.

Otherwise, for now, I can undo my changes on the comments and get started on the line length warnings!

**Comment by driusan** [comment]
I agree with the others that it's better to leave the TODO/FIXME/XXX part of the comments for context.

You're right that the javascript eslint config was based on the Google coding standards when it was setup, but I don't think there's any reason we can't set up our own config and diverge from them.

**Comment by johnsaigle** [comment]
Hey @AlexandraLivadas I'm going to close this PR just to keep things tidy. I definitely think it would be helpful to make the changes to the eslint file or adjust line lengths though! If you have time to do that, that would be great. No worries if you're focusing on test stuff instead.

**Pull request closed without merging**
