### PR TITLE
Brainbrowser 404 fix

### LINKED ISSUE #8016: [Brainbrowser] Constantly loading when accessing image
**Describe the bug**
When navigating to view 3D model from imaging_browser's viewSession, a new window launches but the page never fully loads. See attached screen shot:
Screen Shot 2022-02-23 at 2 14 43 PM

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create new user and assign all Imaging Browser permissions
2. Login as new user
3. Navigate to imaging browser
4. Select `all types` for a given candidate
5. For one of the images, click the checkbox in the top left corner of the image panel
6. Click `3D Only` on the left panel of the page

**What did you expect to happen?**
A new browser page to open and the scan to load.

**Browser Environment (please complete the following information):**
- OS: Mac
- Browser [e.g. chrome, firefox] Chrome
- Version

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: 24
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**

### PR DESCRIPTION
**Pull request by laemtl**
- Add the brainbrowser js files to the list of files parsed by eslint
- Remove the bracket notation for the minc_id param: brainbrowser/?minc_id=[32,33] -> brainbrowser/?minc_id=32,33
- Display an error when the loader fails instead of LOADING...

Fixes #8016, #7681

### CODE REVIEW

**Comment by driusan** [comment]
Why is the brackets removed? That seems like an arbitrary breaking change if there's not a reason for it.

**Comment by laemtl** [comment]
> Why is the brackets removed? That seems like an arbitrary breaking change if there's not a reason for it.
The url params bracket notation is not valid and requires extra parsing. Since those extra brackets aren't necessary, I switched to the native comma separated notation that can do the same job. I carefully covered all the cases so I don't believe it will introduce any breaking changes.  I can also revert the changes if you find it safer.

**Comment by laemtl** [comment]
> I don't think we should risk breaking existing links and the code to strip the `[` and `]` is already there. It's safer and keeping them makes the empty case cleaner.

Ok, I will revert the change then :)

**Comment by laemtl** [comment]
@driusan Reverted

**Pull request merged**
