### PR TITLE
[mri_violations] update testing data for 17.1

### PR DESCRIPTION
**Pull request by kongtiaowang**
These tests failed on MYSQL 5.7. So, base on the 17.1's SQL schema, changing test data.
Adding function to test breadcrumb.

### CODE REVIEW

**Comment by kongtiaowang** [comment]
This PR passed Travis_CI.

**Comment by driusan** [comment]
It still needs to be reviewed by the usual review process.

**Comment by jacobpenny** [comment]
I ran these tests (without your modifications) on MySQL 5.7 and the latest 17.1-dev and they passed, so I don't understand why these changes are needed. Can you explain?

The new test looks good though.

**Comment by kongtiaowang** [comment]
@jacobpenny 
In the 'psc' table  "`Alias` char(3) NOT NULL" ,
When I rebuild the docker, I got errors in MYSQL 5.7. 
'Alias'     => 'test' is more than three charactors.

**Comment by jacobpenny** [comment]
Yeah I ran the tests on `unbreak-docker-tests` and they all pass... I made sure to rebuild the containers too.

```

➜  loris git:(unbreak-docker-tests) ✗ npm run tests:integration -- --filter MriViolationsTestIntegrationTest

> loris@1.0.0 tests:integration /var/www/loris
> ./test/dockerized-integration-tests.sh "--filter" "MriViolationsTestIntegrationTest"

Creating network "loris_default" with the default driver
Creating loris_selenium_1
Creating loris_db_1
Creating loris_web_1
Waiting for mysqld...
mysqld is alive
Waiting for Selenium...
Selenium is alive
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /app/test/phpunit.xml



Time: 23 ms, Memory: 4.00MB

No tests executed!
Waiting for mysqld...
mysqld is alive
Waiting for Selenium...
Selenium is alive
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /app/test/phpunit.xml

.........S

Time: 1.66 minutes, Memory: 6.00MB

There was 1 skipped test:

1) MriViolationsTestIntegrationTest::testNotResolvedSaveButton
Skipping tests until Travis and React get along better

/app/modules/mri_violations/test/mri_violationsTest.php:511
```

**Comment by jacobpenny** [comment]
But what you are saying makes sense. It doesn't fit the schema and should throw an error.

**Comment by kongtiaowang** [comment]
@jacobpenny 
screen shot 2017-06-01 at 11 20 18 am

**Comment by kongtiaowang** [comment]
@jacobpenny 
screen shot 2017-06-09 at 3 41 54 pm

**Pull request merged**
