### PR TITLE
Reupload of an MRI fails despite the reupload being valid.

### PR DESCRIPTION
**Pull request by nicolasbrossard**
With the 'ImagingUploader auto launch' set to yes, and when re-uploading a scan that was not processed successfully by the MRI pipeline, the pipeline exits with an error code of 2 and complains that no profile file was passed on the command line. The error lies in the imaging uploader, which did not set the ID of the uploaded file on a re-upload (it was only set for an *initial* upload). This is a fix for 
 [https://redmine.cbrain.mcgill.ca/issues/14093](url)

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@nicolasbrossard 
I think the test that failed Travis is the one @driusan removes in a recent pull request,
although am not sure which branch this was merged to.

**Comment by MounaSafiHarab** [comment]
@nicolasbrossard 

I now get error code 4 not 2, being on the MRI minor branch (with the new exit codes)! (after I comment out the `@db` section in my `prod` file)
beforeafternickchange

Also the error_log command added shows an upload_id with your fix, and none before your fix:
beforeaftererrorlog

**Comment by MounaSafiHarab** [comment]
@nicolasbrossard 

I would suggest to add this to the test plan (i.e. re-upload to override an existing file, with auto launch on), if it is not already there.

**Comment by nicolasbrossard** [comment]
Good idea. I modified the test plan as requested.

**Pull request merged**
