### PR TITLE
Fix phan mismatched property errors

### PR DESCRIPTION
**Pull request by driusan**
This fixes all the errors identified by phan where a property
was being assigned to an incompatible type. Most of these were
caused by assigning null to a non-nullable property, which was
fixed by declaring the property nullable.

### CODE REVIEW

**Comment by driusan** [comment]
@nicolasbrossard Do you think you'd be able to look at this? The server_process_manager had the most significant changes and are where I'm most likely to have made a mistake..

**Comment by driusan** [comment]
@laemtl since you were highlighting some type errors in another PR and @nicolasbrossard hasn't responded maybe you can look at this?

(Note that this only catches type errors for properties, function arguments is a different (much bigger..) phan error type..)

**Comment by laemtl** [comment]
No pb!

**Comment by nicolasbrossard** [comment]
@laemtl @driusan Ooopss...Sorry I didn't respond...I can take care of this since I wrote the SPM module.

**Review by nicolasbrossard — APPROVED** [review]
Build is successful and code looks good. Approving.

**Comment by driusan** [comment]
Thanks @nicolasbrossard .. had to rebase because of a conflict, I'll merge after it passes again..

**Comment by nicolasbrossard** [comment]
@driusan Will re-review once the build is finished.

**Comment by driusan** [comment]
Looks like rebasing found new things.. I'll tag you when they're fixed.

**Comment by driusan** [comment]
@nicolasbrossard it's passing now after the rebase.. the changes are basically 57e100b7c638c17f497d94888fdb35ad1a0c2e46 plus phpcs and a couple typos.

Phan was getting confused by some tests because it didn't realize that mocks should be considered *both* a mock type and the type of object being mocked. I had to explicitly tell it to treat the objects as the type being mocked instead of as a MockObject type after calling the mock related methods. In a couple cases it was easier to just not assign to a property and leave them as variables because the tests weren't doing anything that depended on it being a class property..

**Review by nicolasbrossard — APPROVED** [review]
Code still looks good after rebase and build successful. Approving.

**Pull request merged**
