### PR TITLE
Imaging Browser: Display tarchiveID information for phantoms as well: Redmine 12650

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
Phantoms did not have their Tarchive information linkable. This pull request fixes this.

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
I am not sure my changes are standard across projects. I don't even know whether the entity_type was purposely left out from the candidateInfo array for a specific/valid reason? But the way the code is currently written, it will break for all projects.

**Comment by driusan** [comment]
What do you mean the entity type was left in the candidate info array? Isn't there a line just above the one that you changed using it?

**Comment by MounaSafiHarab** [comment]
> What do you mean the entity type was left in the candidate info array? Isn't there a line just above the one that you changed using it?

Yes, but we were never entering this `if ($EntityType == 'Scanner') {` specifically because the entity_type is not part of the candidateInfo array.

**Comment by driusan** [comment]
I don't think there's any specific reason for that, it was just a bug.

**Comment by MounaSafiHarab** [comment]
@leothomas 
Assigned this to you as well so you make sure it brings back the Dicom Archive link in Imaging Browser for phantoms (the way we tested it quickly together!).

**Comment by leothomas** [comment]
Confirming that the DICOM archive link is present and queries/populates fields on this branch in the case of non-phantom (tested several dcc and PHI candidates) and phantom users, using a copy of the IBIS database (timestamp = approx 2 weeks old)

**Comment by davidblader** [comment]
@MounaSafiHarab looks good, moved to NSDRASDSMIEIFSTNFS (Needs Senior Developer Review And Senior Developer Should Merge If Everything Is Fine So There's No Further States)

**Comment by driusan** [comment]
@davidblader That's almost as memorable as IDSPISPOPD!

**Pull request merged**
