### PR TITLE
[DQT] Fix data not loading

### PR DESCRIPTION
**Pull request by xlecours**
### Brief summary of changes

1. runQuery javascript function was called with the expected parameters.
2. Content-Lenght header value now fit the content-length of the data sent.

### This resolves issue...

- [ ] Github? #4864 

### To test this change...
Go to DQT, select fields, run query... does results appear? For some reason, the tab shows the info tab content instead of results... the tester need to switch tabs. 
See:  https://github.com/aces/Loris/issues/4905

# If this sentence shows up it means I didn't read the instructions! .... Not

### CODE REVIEW

**Comment by driusan** [comment]
@suzanne-lee can you test that this fixes #4864?

**Comment by ridz1208** [comment]
@xlecours when i run query instead of displaying the results. it displays the info tab...

**Comment by xlecours** [comment]
@ridz1208 yes, as mentioned in the PR description, I created an issue about that :)

**Comment by suzanne-lee** [comment]
tested, LGTM!

**Pull request merged**
