### PR TITLE
[Reliability] RIP

### PR DESCRIPTION
**Pull request by driusan**
I don't think anyone other than IBIS is currently able to use this.

### CODE REVIEW

**Comment by ridz1208** [comment]
@MounaSafiHarab nop.... noot att alll

**Comment by ridz1208** [comment]
@driusan should this be closed untill it is ready ?? seems to be collecting conflicts

**Comment by ridz1208** [comment]
@driusan 
- why is it discussion required ??
- this is not removing the relibility-related sections in other classes. should it be ?
   - config.xml
   - statistics
   - NDB_Caller
   - NDB_reliability
   - ...

**Comment by driusan** [comment]
@ridz1208 

1. because I had to bring it up in the LORIS meeting and forgot to remove the tag after.
2. Yes. Can you request changes so that I don't forget about them?

**Comment by ridz1208** [comment]
@driusan changes requested

once changes are done, please discuss with @sruthymathew123 how to keep using the module on IBIS only after all the changes.

**Comment by sruthymathew123** [comment]
@driusan @ridz1208 @LeighMac  Anyway, currently I am working on broken reliability instruments on IBIS with Loris 19.0 and doing works to maintain it only for IBIS. I can update the changes later on.

**Comment by driusan** [comment]
This should probably wait until 21, so that existing projects can convert it into a "real" module after the PSR15 handler stuff goes in. Doing it before then leaves projects who are using it with no upgrade path, since this removes the code from NDB_Caller and removes the NDB_Reliability class.

Will close after this passes Travis, and then will have to rebase and re-open after the PSR15 handler is done.

**Comment by driusan** [comment]
See above comment.. needs a transition plan for existing projects before we can remove this.

**Pull request closed without merging**
