### PR TITLE
[Data Integrity Flag] Documentation improvements

### PR DESCRIPTION
**Pull request by johnsaigle**

### CODE REVIEW

**Comment by driusan** [comment]
I believe the plan is to remove this module so it might not be worth merging this even if it is a slight improvement.. @ridz1208 @mohadesz are we removing it for this release or the one after?

**Comment by mohadesz** [comment]
@davidblader Let's wait till the next release..

**Comment by johnsaigle** [comment]
@mohadesz I think you mean @driusan

**Comment by mohadesz** [comment]
oops. @johnsaigle, Thank you for catching this.

**Comment by johnsaigle** [comment]
This module has been removed by #5824

**Pull request closed without merging**
