### PR TITLE
[RB_data] duplicate sessionid in mri-upload table

### PR DESCRIPTION
**Pull request by kongtiaowang**
to solve : https://github.com/aces/Loris/issues/4709

### CODE REVIEW

**Comment by driusan** [comment]
@kongtiaowang conflicts

**Comment by cmadjar** [comment]
Since the MRI data has been completed reloaded from scratch, I believe this PR should be closed.

@driusan Do you agree?. If so, this resolves another issue.

**Comment by driusan** [comment]
@cmadjar it depends.. does the recreated data have this duplicate session id problem?

**Comment by cmadjar** [comment]
Closing this PR since new imaging data have been imported in Raisin Bread and the issue reported is not an issue anymore.

**Comment by cmadjar** [comment]
@driusan No because I deleted everything and reinserted from scratch using the imaging pipeline.

**Pull request closed without merging**
