### PR TITLE
Move populate_examiners_psc_rel script to single_use directory

### LINKED ISSUE #8065: [tools] Unknown column error in populate_examiners_psc_rel.php
**Describe the bug**
The script is using the deprecated function `getAllInstruments`, and also yields an SQL error for unknown column:

image

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

### PR DESCRIPTION
**Pull request by sruthymathew123**
#### Link(s) to related issue(s)

* Resolves  #8065

### CODE REVIEW

**Review by ridz1208 — CHANGES_REQUESTED** [review]
@sruthymathew123 the REQUIRE ONCE line needs to be changed

**Comment by ridz1208** [comment]
@driusan I ended up making the changes myself but I obv cant also review it

**Comment by ridz1208** [comment]
@sruthymathew123 no problem its a very small change

**Comment by sruthymathew123** [comment]
@driusan Fixed the conflicts and ready to merge once testing gets passed.

**Pull request merged**
