### PR TITLE
[Version] Version

### PR DESCRIPTION
**Pull request by ridz1208**
This fixes version number

### CODE REVIEW

**Comment by driusan** [comment]
why was this closed?

**Comment by ridz1208** [comment]
see linked PR
the change has been done there

**Comment by MounaSafiHarab** [comment]
> see linked PR
> the change has been done there

what linked PR? the one I refer to is on the MRI side as I was tagging @christinerogers and @cmadjar for an MRI discussion!

**Comment by ridz1208** [comment]
ooops

**Comment by ridz1208** [comment]
@driusan

**Comment by driusan** [comment]
@ridz1208 I didn't merge it because it's an RC, not the final release.

**Comment by driusan** [comment]
This is really stupid, but.. can you rebase this so it passes Travis?

**Pull request merged**
