### PR TITLE
[Tools] Instrument Installer utility script

### PR DESCRIPTION
**Pull request by johnsaigle**
_I gave a demo of this tool a few months ago and people generally seemed to find it helpful. Not exactly sure if 17.1 is the right branch for this, so we can move it if people prefer._

# This is a bash script which automates [the process](https://github.com/aces/Loris/wiki/Behavioural-Database#1-instrument-builder) of instrument installation.
example usage

## Features
- Devs are able to create patch files using `generate_tables_and_sql_and_testnames.php`

- Patches can be applied to the database from within the tool (with the option of first echoing the patch to the terminal for review)

- Existing instruments can be cleanly uninstalled

### CODE REVIEW

**Comment by jstirling91** [comment]
@johnsaigle Can you get someone to test this to get a second look data flow

**Comment by davidblader** [comment]
Going through `[1] Create new patch file using generate_tables_sql_and_testnames.php`
    - I enter an instrument number, but the script just takes me back to the original menu. No error message and I can't seem to find the generated SQL files

Going through `[2] Run a MySQL patch`
    - Minor thing is that I think that when the user enters `Y/n` should be case insensitive

Going through `[3] Uninstall an instrument`
    - If there is an error at any point, the script will still output `[$instrument_name] is now uninstalled. Patch will be deleted.`

**Comment by johnsaigle** [comment]
Cool, thanks for the feedback! I'll fix these when I get a chance next week.

**Comment by davidblader** [comment]
@johnsaigle yeah, it prints the list but looking through your script it looks like it's only handling the case where it's a .linst file? CCNA only uses .class.inc file extensions so maybe that's why :thinking:

**Comment by johnsaigle** [comment]
@davidblader Ah you're right... I've never used .class.inc. I'll review the Installation wiki and see what needs to be done. Thanks again for reviewing!

**Comment by johnsaigle** [comment]
Moved milestones as I will not have time to work on this and it isn't crucial for 17.1

**Comment by ridz1208** [comment]
@davidblader In light of an eventual refactoring of instruments, do you think this is something that needs to be further explored ??

**Comment by ridz1208** [comment]
Despite the need for something like this, it seems that this only does it for linst files (which apparently could already be done through the instrument manager) and might not be as user-friendly as it should for a structure that complex.

closing for now in the hopes that instruments will get a full complete re-vamp

**Pull request closed without merging**
