### PR TITLE
createVisit/Project/Cohort imaging config

### PR DESCRIPTION
**Pull request by laemtl**
New imaging config to set:
- createVisit
- a default project used if createVisit or createCandidate is set to true, or for phantom scans
- a default cohort used if createVisit is set to true

### CODE REVIEW

**Review by ridz1208 — CHANGES_REQUESTED** [review]
Please replace all `subproject` references with `cohort`

**Comment by laemtl** [comment]
Oh that's true :) Thanks!

**Review by cmadjar — COMMENTED** [review]
@laemtl @ridz1208 The new configs makes sense to me but was not able to test the configs on the MRI side as the code related to this PR on the MRI side has not yet been implemented. Will approve only once final testing on MRI side is complete.

**Review by cmadjar — APPROVED** [review]
LGTM

**Comment by cmadjar** [comment]
Added the Blocking label as this is blocking the merge of https://github.com/aces/Loris-MRI/pull/809 on the MRI side.

**Comment by cmadjar** [comment]
@driusan I believe this is ready for your final review. Thanks!

**Pull request merged**
