### PR TITLE
Rename quatUser & quatPassword to something more descriptive

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

The quatUser is now dbUser and the quatPassword is now dbPassword.

#### Links to related tickets (GitHub, Redmine, ...)

* Resolves https://github.com/aces/Loris/issues/5782

### CODE REVIEW

**Comment by johnsaigle** [comment]
The other username and password are also for the database so I don't know if this name is much better. nothing better is coming to mind right now though.

**Comment by johnsaigle** [comment]
Also I think this should probably go to `major` instead of the release branch

**Comment by johnsaigle** [comment]
Looks good, thanks for the cleanup!

**Comment by maltheism** [comment]
@driusan @johnsaigle I rebased to major.

**Comment by driusan** [comment]
Adding tags because projects will need to update existing settings

**Pull request merged**
