### PR TITLE
create timepoint bug fix

### PR DESCRIPTION
**Pull request by kongtiaowang**

### CODE REVIEW

**Comment by kongtiaowang** [comment]
screen shot 2016-08-17 at 10 33 03 am
before 
screen shot 2016-08-17 at 10 33 56 am
fix
screen shot 2016-08-17 at 10 33 12 am

**Comment by driusan** [comment]
Would you have a chance to test/review this?

**Comment by alisterdev** [comment]
@kongtiaowang @driusan So, aside from the error message being excesively large and red, I think that all these changes can be replaced with one line.        
```php
$this->addRule('subprojectID', 'A Subproject ID is required', 'required');
``` 
right after the select is added in PHP on line 77. (i.e after this line`$this->addSelect('subprojectID', 'Subproject', $sp_labelOptions, $attributes);`)

Note that the same approach is used to validate the visit label dropdown in the same piece of code.

**Comment by kongtiaowang** [comment]
@alisterdev  
Thanks. I will close this pull request and pull a new request.

**Pull request closed without merging**
