### PR TITLE
Brainbrowser 2.5.5: More bug fix for HDF5 reader error: Redmine 13333

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
Sequel to #3068 and #3110,
based off of BrainBrowser latest pull request (technical details/description of the changes in the pull request by @rdvincent): aces/brainbrowser#339
that will be released once this PR is merged: aces/brainbrowser#340

### CODE REVIEW

**Comment by davidblader** [comment]
all good on my end 👍

**Comment by MounaSafiHarab** [comment]
version of brainbrowser officially released (https://github.com/aces/brainbrowser/releases/tag/v2.5.5), so removing the 'Blocked' tag

**Comment by MounaSafiHarab** [comment]
> all good on my end

can you please pass manual test then?

**Comment by Jkat** [comment]
Looks good on my end too! 👍

**Comment by MounaSafiHarab** [comment]
> Looks good on my end too!

thanks for confirming!

**Pull request merged**
