### PR TITLE
[Conflict Resolver] updated module help text

### PR DESCRIPTION
**Pull request by knoll-alex**
## Brief summary of changes

New copy for Conflict Resolver help text

#### Testing instructions (if applicable)

1. Edit copy if necessary
2. Check out screenshot of rendering below

#### Links to related tickets (GitHub, Redmine, ...)

*https://github.com/aces/Loris/issues/5576

Screenshot 2019-11-11 18 03 05

### CODE REVIEW

**Comment by johnsaigle** [comment]
Adding Needs Rebase due to the branch conflicts.

**Comment by christinerogers** [comment]
merge conflicts @driusan  can you help?

**Comment by johnsaigle** [comment]
@christinerogers It's probably easier to create a new pull request if rebasing is not possible. One of the other PRs may have been merged with conflict resolver changes.

**Comment by christinerogers** [comment]
makes sense @johnsaigle

**Comment by knoll-alex** [comment]
i've created new PRs for the two that included the conflictresolver.md file - #5690 and #5688 - so the original two with the extra file - #5621 and #5622 - can simply be closed. In this case, can we keep this PR as is or must I still issue a new PR for conflict resolver? @johnsaigle

**Comment by johnsaigle** [comment]
I think you'll still need to issue a new one.

From my understanding, the conflict resolver file was modified on the repository at some point around the same time as when this PR was issued. 

As a result, git thinks that two different, conflicting changes are being made on the file at about the same time. Therefore doesn't really know which file is "newer" and requires a human to sort it out.

It's possible some other PR (besides those two) modified the file and got merged, creating the error  but I'm not sure. 

In any case you'll probably have to close this PR and open another one if rebasing isn't possible.

**Comment by johnsaigle** [comment]
I still think you'll have to make a new one, unfortunately.

**Comment by johnsaigle** [comment]
It looks like the help file got deleted recently and that's causing the issue.

**Comment by knoll-alex** [comment]
Thanks! I'll issue a new one now, no prob.

**Comment by johnsaigle** [comment]
Closing in favour of new PR

**Pull request closed without merging**
