### PR TITLE
[candidate_list] fix react table url with undefined param

### PR DESCRIPTION
**Pull request by kongtiaowang**
Click the PSCID URL link gets 500 error.

Test: click the PSCID link in the react table to test.
PSCIDLINK

### CODE REVIEW

**Comment by driusan** [comment]
This should be fixed by #5381 instead

**Comment by kongtiaowang** [comment]
Not the same issue. It hadn't been fixed by #5381.

**Comment by driusan** [comment]
I just tried this on the branch for #5381 and it fixed the issue for me. Did you clear your cache and run make before testing?

**Comment by kongtiaowang** [comment]
@driusan You are right, I thought 5381 was merged. I will close this one.

**Pull request closed without merging**
