### PR TITLE
[docs] SchemaSpy: Add navigable Schema diagrams

### LINKED ISSUE #5391: SchemaSpy: Add navigable Schema diagrams at each release
Based on example presented from CNBP by @dyt811
https://cnbp.github.io/LORIS_MySQLStructure/

Should be set up as an automatic process to execute on the schema and be committed as release is issued. 
Web front-end accessibility of this documentation should be tested as part of the release process.

### PR DESCRIPTION
**Pull request by haoweiqiu**
## Brief summary of changes

- [x] Have you updated related documentation?

To run SchemaSpy, java openjdk 8 and graphviz are required.
Meanwhile, [mysql jdbc connector](https://dev.mysql.com/downloads/connector/j/8.0.html), and [schemaspy](http://schemaspy.org/) need to be installed. 

Specific installation and configuration guide for SchemaSpy can be found [here](https://schemaspy.readthedocs.io/en/latest/installation.html).

The diagram can be found in /sqlschema directory.

#### Link(s) to related issue(s)

* Resolves #5391  (Reference the issue this fixes, if any.)

image

### CODE REVIEW

**Comment by christinerogers** [comment]
Hi Haowei, thanks for starting this draft PR. 
Could you add several more sentences/paragraphs to the description at the top of this PR, to let the team know what this addition does and does not do, how and when it's supposed to work / be run, how and where users/readers are supposed to find and navigate the schema representation, and why adding so many files/dependencies is necessary?  Please also include a screenshot of the result - the db schema itself, so we have an easy sense of what you're adding here. thanks

**Comment by haoweiqiu** [comment]
Hi @christinerogers, most of the files are automatically generated by SchemaSpy.

**Comment by christinerogers** [comment]
The main fail we really want is the diagram shown in : 
https://htmlpreview.github.io/?https://raw.githubusercontent.com/aces/Loris/76df290ca99e702ba0647ab75951bea211613aae/sqlschema/relationships.html

i think it's called singlefilerelationships.html
it's all we really need. 

Can you find a way to configure SchemaSpy so that when it runs it will generate a minimum of files -- even just that one diagram if possible ?

**Comment by haoweiqiu** [comment]
Hi @christinerogers, the remaining files (previously in /sqlschema/diagrams/summary) are the minimized files of the SQL schema diagram.

**Review by christinerogers — APPROVED** [review]

**Comment by christinerogers** [comment]
This is research done by Haowei but I'm not sure it's ready for merging as a solution for a LORIS schema diagram. 

The original issue was to determine if a schema diagram can be generated as an `automatic process to execute on the schema ` as opposed to a separate software installation that needs to be re-run at every release.  

This diagram is also out of date on the `main` branch and would need to be re-generated before the 24 release. Closing for now.

**Pull request closed without merging**
