### PR TITLE
[issue_tracker] Fix loading of page without superuser permission

### LINKED ISSUE #7799: [Issue tracker] Can not access module
**Describe the bug**

The module loads normally with admin user or a user with super permissions. However, if I attempt to access the module from a user that has both issue tracker permissions and no other permissions, I get "An error occured while loading the page" as well as the following in my error log:

`[Mon Nov 08 11:20:12.936860 2021] [php7:error] [pid 4627] [client ::1:44026] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to User::hasCenter() must be an instance of CenterID, int given, called in /var/www/loris/src/Data/Filters/UserSiteMatch.php on line 48 and defined in /var/www/loris/php/libraries/User.class.inc:433\nStack trace:\n#0 /var/www/loris/src/Data/Filters/UserSiteMatch.php(48): User->hasCenter()\n#1 /var/www/loris/src/Data/ProvisionerInstance.php(129): LORIS\\Data\\Filters\\UserSiteMatch->filter()\n#2 [internal function]: LORIS\\Data\\ProvisionerInstance->LORIS\\Data\\{closure}()\n#3 [internal function]: CallbackFilterIterator->accept()\n#4 [internal function]: FilterIterator->rewind()\n#5 /var/www/loris/src/Data/Table.php(83): IteratorIterator->rewind()\n#6 /var/www/loris/src/Data/Table.php(98): LORIS\\Data\\Table->toArray()\n#7 /var/www/loris/modules/issue_tracker/php/issue_tracker.class.inc(203): LORIS\\Data\\Table->toJSON()\n#8 /var/www/loris/php/libraries/NDB_Menu_Filter.class.inc(648): LORIS\\issue_tracker\\Issue_Tracker->toJSON()\n#9 /var/www/loris/php/libraries/NDB_Page.class.inc(753): NDB_Menu in /var/www/loris/php/libraries/User.class.inc on line 433, referer: http://localhost:8080/issue_tracker/
`

image

I found this bug while manually testing a PR and then noticed it is also a bug on main branch. Tested on my VM with raisinbread data as well as on test-loris-dev.loris.ca

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Create a user with only the issue tracker permissions
2. Log in with that user
3. Navigate to issue tracker module

### PR DESCRIPTION
**Pull request by driusan**
Fix issue tracker to load the correct type, as required by the
MultiSiteHaver interface that it declares itself to implement.

phan was not able to track down the type incompatibilities because
the docblock was using the less specific "array" and not the typed
"\CenterID[]" array.

Resolves #7799

### CODE REVIEW

**Comment by driusan** [comment]
Blocked by #7814 because it uses the method in LorisInstance introduced there.

**Comment by driusan** [comment]
@CamilleBeau since you reported it can you test/review the issue tracker parts of this?

**Comment by CamilleBeau** [comment]
I can now load the module successfully from a non-super user, but loading the `new issue` page is giving me the "An error occurred while loading the page." message. I can load the `new issue` successfully from the admin user. The following is in the error_log:

```
[Fri Nov 12 10:12:53.898509 2021] [php7:warn] [pid 3729] [client ::1:38202] PHP Warning:  PDOStatement::execute(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':CenterID) OR (upr.CenterID=:DCC)\n             AND Active='N'' at line 3 in /var/www/loris/php/libraries/Database.class.inc on line 723, referer: http://localhost:8080/issue_tracker/issue/new
[Fri Nov 12 10:12:53.902031 2021] [php7:notice] [pid 3729] [client ::1:38202] Could not execute SELECT DISTINCT u.Real_name, u.UserID FROM users u\n             LEFT JOIN user_psc_rel upr ON (upr.UserID=u.ID)\n             WHERE FIND_IN_SET(upr.CenterID,:CenterID) OR (upr.CenterID=:DCC)\n             AND Active='N'. Stack trace#0 /var/www/loris/php/libraries/Database.class.inc(760): Database->execute()\n#1 /var/www/loris/modules/issue_tracker/ajax/EditIssue.php(648): Database->pselect()\n#2 /var/www/loris/modules/issue_tracker/ajax/EditIssue.php(36): getIssueFields()\n#3 /var/www/loris/htdocs/AjaxHelper.php(112): require('/var/www/loris/...')\n#4 {main}, referer: http://localhost:8080/issue_tracker/issue/new
[Fri Nov 12 10:12:53.903906 2021] [php7:error] [pid 3729] [client ::1:38202] PHP Fatal error:  Uncaught DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':CenterID) OR (upr.CenterID=:DCC)\n             AND Active='N'' at line 3 in /var/www/loris/php/libraries/Database.class.inc:726\nStack trace:\n#0 /var/www/loris/php/libraries/Database.class.inc(760): Database->execute()\n#1 /var/www/loris/modules/issue_tracker/ajax/EditIssue.php(648): Database->pselect()\n#2 /var/www/loris/modules/issue_tracker/ajax/EditIssue.php(36): getIssueFields()\n#3 /var/www/loris/htdocs/AjaxHelper.php(112): require('/var/www/loris/...')\n#4 {main}\n  thrown in /var/www/loris/php/libraries/Database.class.inc on line 726, referer: http://localhost:8080/issue_tracker/issue/new
```

**Comment by driusan** [comment]
@CamilleBeau I think that's caused by https://github.com/aces/Loris/pull/7698/files#r747817355

I don't want conflicts with that PR, so can you make the equivalent changes to ajax/EditIssue.php to test? Around line 648, you should be able to just copy the parameters for the query from the query on the line above it. If that fixes it, it's unrelated to this PR.

**Comment by CamilleBeau** [comment]
> I don't want conflicts with that PR, so can you make the equivalent changes to ajax/EditIssue.php to test? Around line 648, you should be able to just copy the parameters for the query from the query on the line above it. If that fixes it, it's unrelated to this PR.

Works well with the following changes made to ajax/EditIssue
image

**Review by CamilleBeau — APPROVED** [review]

**Pull request merged**
