### PR TITLE
[Core] Reset password not working

### PR DESCRIPTION
**Pull request by ZainVirani**
Fixes bug described [here](https://redmine.cbrain.mcgill.ca/issues/12872#change-50753).

`lost_password` calls `User::singleton(username)` to retrieve user information, which is blocked because `NDB_Client` calls `User::singleton` first (using the unix username). This is because the line `$client->makeCommandLine()` forces NDB_Client to act as if the user is not using a web client.

### CODE REVIEW

**Comment by ridz1208** [comment]
@kongtiaowang please test and see if issue is resolved

**Comment by kongtiaowang** [comment]
@ZainVirani 
It works well. Good job!
Could u fix the front-end? It shows that user should input an email. Actually, it only needs an user name.

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/pull/2989

**Comment by ridz1208** [comment]
@kongtiaowang please put passed manual test flag

**Pull request merged**
