### PR TITLE
[PHPCS] Make type hinting mandatory

### LINKED ISSUE #4271: add return types to data_release
Related to: https://github.com/aces/Loris/pull/4270/files/101d2d13b26d2e7f4787325692d240242ae9781f#diff-0b0d599fe0612ffeea1aa7ce6185c9c3

This class has return types on some functions and not others, should be made consistent

### LINKED ISSUE #4282: Module function isPublicModule() should return a bool
The function signature in the Module class for `isPublicModule` should include a boolean return type (`public function isPublicModule() : bool`), which wasn't done in #4234.

It should be fairly easy to update it, but updating it will require changing every Module subclass in each `modules/$modulaname/php` directory.

### LINKED ISSUE #4284: Add return types to Database class "pselect*" functions
#3878 did not add return types to `pselect*` functions because they can return array, null, and sometimes false (I believe). Wrapper functions in other classes and modules that call `pselect` functions are unable to have return types for the same reason.

It would be good to standardize and document the types that these functions can return and eventually to add appropriate return types.

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

PHPCS now makes type hinting mandatory for function parameters and return types. You can add them automatically based on PHPDocs using `phpcbf`. `mixed` annotations don't result in any changes.

#### Links to related tickets (GitHub, Redmine, ...)

* This is a revamp of #4064 
* Resolves #4282 
* Resolves #4271 
* Resolves #4284

### CODE REVIEW

**Comment by johnsaigle** [comment]
Adding needs work because this is unlikely to pass Travis for another few rounds.

**Comment by johnsaigle** [comment]
This will be rebased to the "Dev" branch once our new branching system takes effect.

**Comment by johnsaigle** [comment]
This is now incorporating changes from 22 but there are many phan errors related to this to fix.

**Comment by ridz1208** [comment]
@johnsaigle wouldn't it be easier to tackle this in smaller chunks ?

**Comment by johnsaigle** [comment]
@ridz1208 Maybe but not after I've put all this time into it 🤣 

I think PRs adding PHPCS and Phan rules are always pretty big but we can sort it out. We're not releasing anytime soon so even if there are some type errors we can get them fixed.

**Comment by ridz1208** [comment]
@johnsaigle I'm more concerned about travis

**Comment by johnsaigle** [comment]
Let me handle Travis 😈

**Pull request closed without merging**
