### PR TITLE
Adding more scripts travis' PHPCS

### PR DESCRIPTION
**Pull request by Jkat**
Ran PHPCS on:

* generic_includes.php
* CouchDB_Import_MRI.php

### CODE REVIEW

**Comment by driusan** [comment]
This is failing PHP CS..

**Comment by Jkat** [comment]
Seems like I have a different version of phpcs probably.

**Comment by driusan** [comment]
You can run the version in vendor/bin directly by copy/pasting the command from the travis.yml to be sure you have the same version

**Comment by Jkat** [comment]
I'm still on Precise Pangolin and therefore I still issue the --no-dev option for composer otherwise it fails on facebook webdriver. So my vendor/bin is empty at the moment. I guess I could take out that requirement and run composer but still not ideal as I won't have a complete set of tools.

**Comment by karolinamara** [comment]
Which version of PHP do you have? I upgraded to PHP 5.4 and it resolved my issue with facebook webdriver.

**Comment by Jkat** [comment]
Precise Pangolin offers up to 5.3.10 officially. I know I need 5.3.19 at least but for now I'm trying to stay in line with my production configuration. I plan to do upgrades when I get enough things off my plate.

**Pull request merged**
