### PR TITLE
[JSX] Refactor Modal Component to Improve UX and Code Maintainability

### PR DESCRIPTION
**Pull request by HenriRabalais**
### Summary

This PR refactors the Modal.js React component to enhance its usability, simplify state management through hooks, and improve the user experience. The updates streamline interactions with loading states and successful submission feedback, while also updating the modal’s style and structure for better flexibility.

### Key Changes

1.	Functional Component Refactor: Converted Modal from a class-based to a functional component, utilizing React hooks (useState) for managing loading and success states.
2.	Loading and Success Feedback:
- Integrated a Loader component to display a loading indicator during form submission.
- Added a success message on form completion, which displays briefly before automatically closing the modal.
3.	Styling and Layout Improvements:
- Enhanced the modal’s layout, including more visually distinct header, footer, and content sections.
- Adjusted styles dynamically based on state (loading and success) to improve feedback clarity.
- Upated background overlay and animations for smoother transitions.
4.	Improved Form Handling:
- Added a delay function (wait) for smooth feedback timing, allowing users to visually confirm the success state.
5.	Warnings and Prompts:
- Preserved the throwWarning functionality, utilizing Swal for confirmation prompts before closing unsaved forms.
	
### Additional Notes
- Backward Compatibility: While these updates significantly refactor the modal, they maintain backward compatibility with existing props (onClose, onSubmit, throwWarning, etc.).
- Test Recommendations: Test form submissions under various states (loading, success, with/without throwWarning) to confirm smooth transitions and proper modal closure.
- Since I had to convert Loader.js to Loader.tsx to properly import it in the Modal, I went ahead and intergrated the changes from #9400 into this PR (it's just styling to change the boarder width based on the size of the loader)

This refactor optimizes the Modal component, making it more efficient and user-friendly while enhancing readability and maintainability.

Screenshot 2024-11-01 at 14 38 38
Screenshot 2024-11-01 at 14 38 55
Screenshot 2024-11-01 at 14 38 57

### CODE REVIEW

**Comment by maximemulder** [comment]
Please ping me when you're done, I love code quality changes and I'll be sure to review it promptly. If you're rewriting the `Modal` component, could you also make it a `.tsx` and get rid of prop types ?

**Comment by HenriRabalais** [comment]
@kongtiaowang would you be able to help me figure out why this isn't passing?

@maximemulder It's ready to review!

**Comment by laemtl** [comment]
@HenriRabalais Can you fix the failed test?

**Comment by maximemulder** [comment]
@HenriRabalais The integration test is failing because the HTML selector it used in the previous modal is no longer valid with the new modal. The selector can be found [here](https://github.com/aces/Loris/blob/38266d4ac7a63d320e00358f8c099a4da6c23311/modules/battery_manager/test/BatteryManagerTest.php#L172).

The current selector are quite fragile, please update them so that the tests pass.

For this test in particular (but there may be others), instead of this selector:
```
#lorisworkspace > div>div:nth-child(2)>div>div:nth-child(2)>form> div > div:nth-child(2) > div > div > select > option:nth-child(2)
```
I would use something like this one:
```
#lorisworkspace > select[name="testName"] > option:nth-child(2)
```

Thought I can also see a benefit in more precise selectors like the first one, but it comes at a price of maintainability.

**Review by maximemulder — APPROVED** [review]
Works on my machine. Mergeable once the tests pass I guess (and one small non-blocking Nit).

**Pull request merged**
