### PR TITLE
Update Electrophysiology Browser README.md

### PR DESCRIPTION
**Pull request by regisoc**
Added Troubleshooting point for recent Protobuf version install in README.

### CODE REVIEW

**Comment by regisoc** [comment]
It seems Protocol Buffer has changed the way they are numbering their versions.
It happened between the [`v3.20.1` (2022-04-21)](https://github.com/protocolbuffers/protobuf/blob/main/CHANGES.txt#L322) and the new [`v21.x` (2022-05-10)](https://github.com/protocolbuffers/protobuf/blob/main/CHANGES.txt#L257).
Starting with `v21.x`, it is [their new way of numbering each individual language projects](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning). The `v21.x` seems to refer to `v3.21.x`.
The only thing is, it is pretty confusing on the release download page: 
image

**Comment by laemtl** [comment]
> It seems Protocol Buffer has changed the way they are numbering their versions. It happened between the [`v3.20.1` (2022-04-21)](https://github.com/protocolbuffers/protobuf/blob/main/CHANGES.txt#L322) and the new [`v21.x` (2022-05-10)](https://github.com/protocolbuffers/protobuf/blob/main/CHANGES.txt#L257). Starting with `v21.x`, it is [their new way of numbering each individual language projects](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning). The `v21.x` seems to refer to `v3.21.x`. The only thing is, it is pretty confusing on the release download page: image

Oh.. I guess my suggestion then becomes 
The visualization component requires Protocol Buffers v3.0.0 or higher (v3.20.x recommended).

**Comment by regisoc** [comment]
I can validate that the `v21.x` is actually the `v3.21.x`. 
I installed the [`v21.8`](https://github.com/protocolbuffers/protobuf/releases/tag/v21.8) and the compiled `protoc` version is mentioned as `v3.21.8`.

```bash
$ protoc --version
libprotoc 3.21.8
```

We should describe this, just to track and understand the change for future use: 
"
The visualization component requires Protocol Buffers `v3.x.y` or higher (`v3` recommended). 

> Note: from 2022-05, [Protobuf numbering scheme change to `v21.x`](https://developers.google.com/protocol-buffers/docs/news/2022-05-06#versioning), meaning `v3.21.x` depending on each maintained language.

"

**Comment by ridz1208** [comment]
@regisoc @laemtl this was automatically closed because the branch was issued from aces

make sure to only issue PRs from you fork of LORIS

you can still move the contents of this branch to your fork and re-issue the PR if necessary (you should still have the branch locally)

**Comment by laemtl** [comment]
Thanks Rida, we will fix that.

**Pull request closed without merging**
