### PR TITLE
[Imaging Uploader] Move upload exception handling code from success callback to error callback

### PR DESCRIPTION
**Pull request by davidblader**
Originally exceptions that were not 403 or 404 defaulted to 200, so error handling was done in success callback.
Now on 19.0, they are defaulted to 500, so the error callback should now be responsible for displaying the thrown exception.

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
I tested 2 errors (namely that the Visit label must exist in the database and that the file must have the extension of .tar, .zip etc...)
both error messages now do show up in the front end, as opposed to being embedded in the html page contents in the console of the browser (with a 500 server error)!

**Comment by MounaSafiHarab** [comment]
@nicolasbrossard 

could you please also test from your end as well?

**Comment by nicolasbrossard** [comment]
I pulled the fix on my VM and it works fine. I executed the same tests that @MounaSafiHarab ran.

**Comment by MounaSafiHarab** [comment]
users on CCNA are already emailing me asking me why they are no longer getting any feedback from Imaging Uploader!
so thanks for merging fast!

**Pull request merged**
