### PR TITLE
Add PHPCS to core integration tests

### PR DESCRIPTION
**Pull request by johnsaigle**
## Brief summary of changes

Adds PHPCS to files in `test/integrationtests/`

### CODE REVIEW

**Comment by maltheism** [comment]
The comments look good to me. I'm not sure why travis didn't run. @johnsaigle

**Comment by driusan** [comment]
@maltheism I'm not sure what you're talking about, Travis did run..?

**Comment by maltheism** [comment]
@driusan I'm not sure why but the `Show all checks` usually isn't needed for me to toggle. That's the reason I was confused because I wasn't seeing the small green checkmark for travis.

**Comment by laemtl** [comment]
Replaced by #6800

**Pull request closed without merging**
