### PR TITLE
[Schema] - Adding menu uniqueness

### PR DESCRIPTION
**Pull request by xlecours**
Make sure that:

- [x] Menu items are unique in the LorisMenu table.
- [x] A menu item exists for each record in the LorisMenuPermissions table
- [x] A permission exists for each record in the LorisMenuPermissions table
- [x] (MenuID, PermID) tuples are unique in the LorisMenuPermissions table

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@xlecours 
- release patch needs to be updated if this goes into 17.0 
- and the path is wrong for one of the patches (Archive/17.1...)

**Comment by kongtiaowang** [comment]
@xlecours 
0000-00-02-Menus.sql works well for me.
But Archive/17.1/20161110-LorisMenu_uniqueness.sql doesn't work for me.
 lorisadmin@wangshen:/var/www/loris/SQL$ mysql -h ace-db-1.cbrain.mcgill.ca -u wangshen -p wangshen_test < /var/www/loris/SQL/Archive/17.1/20161110-LorisMenu_uniqueness.sql
Enter password: 
ERROR 1142 (42000) at line 6: ALTER command denied to user 'wangshen'@'132.206.37.46' for table 'LorisMenuPermissions'

**Comment by ridz1208** [comment]
@xlecours I got the same error as @kongtiaowang, thne i realized that its because of the the `LORIS` concatenation so i removed that !

I ran into
```
SQL Error [1452] [23000]: Cannot add or update a child row: a foreign key constraint fails (`LorisMenuPermissions`, CONSTRAINT `fk_LorisMenuPermissions_1` FOREIGN KEY (`MenuID`) REFERENCES `LorisMenu` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE)
```
when trying again

**Comment by ridz1208** [comment]
@xlecours  Tried several combinations of cases. 

- On a normal menu (no duplicates) tests pass, no possibility of future duplications.
- On DB with duplications. the duplicates are eliminated -> tests pass
- if there are more than 2 copies of the same menu entry (i.e. 3 times issue tracker or more) the patch throws an error saying there is a duplicate entry and fails at removing them (only removes one).

That said... I will still put passed manual test since this a very far fetched case for production env

**Pull request closed without merging**
