### PR TITLE
[datadict] Test plan improved readability and fixed script location

### PR DESCRIPTION
**Pull request by ridz1208**
## Brief summary of changes
https://github.com/aces/Loris/issues/5551

mostly white space changes except the path in item 11

### CODE REVIEW

**Comment by ridz1208** [comment]
@johnsaigle I wouldnt because we should still test everything that is automated anyways
automated tests often dont cover edge cases, dont change permissions, dont use sing sites vs multiple sites, single projects vs multi projects, tests could be corrupted if they were merged without proper review....

this is our chance to not only test the code but also make sure to test the tests

**Comment by johnsaigle** [comment]
> dont change permissions

I think almost all of them do this actually. But I see your point.

**Comment by ridz1208** [comment]
https://github.com/aces/Loris/issues/5560

thats a good example...

**Comment by johnsaigle** [comment]
Thanks for the example. I guess I had assumed that when there was an automated test for something then we could assume that that part is covered. And that was why some thing were marked manual and other things as automated in the test plan.

Is the example in that issue marked as automated?

**Comment by ridz1208** [comment]
in that case nothing is marked. but examples like media where there is a test with no permissions and one with only `media_read` permission but non with `media_write` permission come to mind.

**Comment by HenriRabalais** [comment]
I was making the same assumption as @johnsaigle

**Pull request merged**
