### PR TITLE
[API] fix error in adding new visit via api

### PR DESCRIPTION
**Pull request by jstirling91**
Creating a new visit wasn't working

### CODE REVIEW

**Comment by driusan** [comment]
@kongtiaowang This looks fine to me, can you test it?

**Comment by driusan** [comment]
@jstirling91 @kongtiaowang This also seems to be failing Travis because the Travis script isn't calling resetpassword correctly.. is Travis working on 17.0-dev?

**Comment by kongtiaowang** [comment]
@jstirling91 Yes. It runs on 17.0-dev

**Comment by kongtiaowang** [comment]
@jstirling91 
when I test this PR. I got this "
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log."

**Comment by kongtiaowang** [comment]
screen shot 2017-06-01 at 11 59 58 am
It works!

**Comment by driusan** [comment]
@kongtiaowang Your screenshot says "Type: no auth". Doesn't that mean it should have responded with a permission denied error?

But even if there is a reason that it shouldn't have (like you were separately logged in to LORIS), can you check why this is failing Travis before I merge it?

**Comment by driusan** [comment]
(I added the "Needs Work" tag because it's failing Travis)

**Comment by kongtiaowang** [comment]
@driusan The Authorization Tab is a default option. I have put the Authorization in the Header parameter with key and value. No worry about it.
screen shot 2017-06-02 at 10 33 44 am

**Comment by jstirling91** [comment]
@driusan removing from project since its been merged

**Pull request merged**
