### PR TITLE
DICOM Archive Data Framework

### PR DESCRIPTION
**Pull request by driusan**
This updates the DICOM Archive module to use the new DICOM Archive framework as a first use case. It removes the custom generated NDB_Menu_Filter SQL and converts it to a DBRowProvisioner.

Note that I'm not entirely happy with the amount of serializing and deserializing from JSON required to modify/annotate responses at various parts (because of the fact that the interface only has toJSON and no array equivalent, while the pre-interface class had both toArray and toJSON, so it could delay the serialization until the last minute).

(Note: benchmarks were very flawed because I had accidentally changed the query between versions, so I removed them.)

### CODE REVIEW

**Comment by driusan** [comment]
@kongtiaowang I manually tested this and there's not exactly a lot of functionality to test, but if you could give it a manual test too before merging that would be useful..

**Comment by driusan** [comment]
Blocked by #3521

**Comment by kongtiaowang** [comment]
@driusan I am working on it, try to figure out why test cases failed.

**Comment by kongtiaowang** [comment]
@driusan  Can't load dicom_archive page.
screen shot 2018-03-01 at 12 34 08 pm

**Comment by driusan** [comment]
@kongtiaowang sorry, I forgot to git add a file. I just added it..

**Comment by PapillonMcGill** [comment]
Code look clean, haven't spotted anything by looking at it.

**Comment by driusan** [comment]
@PapillonMcGill your review was autodismissed from the changes to fix travis, can you review again?

**Pull request merged**
