### PR TITLE
[User Accounts] Form improvements

### LINKED ISSUE #5218: Create user UI not showing mandatory fields.
Hi Loris team,

This is a minor issue I think could be quickly solved as it is properly addressed in other modules.

**Description:**
When creating a new user the mandatory fields are not explicitly highlighted. Please see the image attached. I do notice that in other modules (create candidate for example) this was already addressed. It will be very nice if this 'feature' could be included on this module also.

Thanks and congrats for the nice job.

cretateUser_notShowingMandatoryFields

cretateCandidate_showingMandatoryFields

### PR DESCRIPTION
**Pull request by laemtl**
Improvements for the Add/Edit user form:

* add a red asterisk next to the required fields
* toggle `Generate new password`:
   - clear the new/confirm password fields if on
   - enable/disable the new/confirm password fields 
   - toggle the required marker on the new/confirm password fields
   - toggle Send email to user 
* toggle `Make user name match email address` :
   - clear the User name field if on
   - enable/disable the User name field
   - toggle the required marker on the User name field

Solved warnings/fatal errors due to type errors in `edit_user.class.inc` (seems to happen in test mode only).

### CODE REVIEW

**Comment by johnsaigle** [comment]
The asterisks are appearing 👍 

There is one complication though: When the "generate new password" box is selected, both the Password and Confirm Password fields should be empty because the system generates a password automatically. If they are not empty and the box is checked, the user will get an error.

In this case I'm not sure whether the asterisk should be there because it's actually not required in that case. 

The best way would be to disabled both of those text inputs when the box is checked but I'm not sure if that's easy/possible given the front-end code in the module.

**Comment by laemtl** [comment]
I understand what's happening... my bad. I can implement your suggestion too.

**Comment by christinerogers** [comment]
LGTM. this is on master so I'll wait bump anyone else for re-review

**Comment by johnsaigle** [comment]
My VM is experiencing technical issues that the sysadmins are working on right now, so I'm unable to test atm.

**Comment by laemtl** [comment]
@johnsaigle If you have time to approve your change request that would be great!

**Comment by christinerogers** [comment]
Waiting on @johnsaigle to approve / or another tester. 

@h-karim would you have a few minutes to test this?

**Comment by laemtl** [comment]
Thanks @h-karim, very good suggestion. It's implemented.

**Comment by johnsaigle** [comment]
It looks like the integration tests need to be updated.

**Comment by laemtl** [comment]
1) UserAccountsIntegrationTest::testAddNewUser

Facebook\WebDriver\Exception\NoSuchElementException: Unable to locate element: *[name='First_name']

For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'

System info: host: '5e2693d9f2e3', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1028-gcp', java.version: '1.8.0_151'

Driver info: org.openqa.selenium.firefox.FirefoxDriver

Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 57.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 16148, moz:profile: /tmp/rust_mozprofile.uNwNAH..., moz:webdriverClick: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1028-gcp, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}

Session ID: 80430c08-a3ea-44b9-a0c1-aad624f79609

*** Element info: {Using=name, value=First_name}

/app/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:163

/app/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:376

/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:590

/app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:214

/app/vendor/php-webdriver/webdriver/lib/WebDriverExpectedCondition.php:176

/app/vendor/php-webdriver/webdriver/lib/WebDriverWait.php:54

/app/test/integrationtests/LorisIntegrationTest.class.inc:511

/app/modules/user_accounts/test/user_accountsTest.php:283

**Pull request merged**
