### PR TITLE
[tools] fix instance of CenterID and ProjectID passed as strings

### LINKED ISSUE #8062: [tools] Use CandID instance in generate_candidate_externalids.php
**Describe the bug**
The script is failing because a string is passed as CandID instead of a CandID instance in Site::singleton

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Site::singleton() must be an instance of CenterID, string given, called in /var/www/loris/tools/generate_candidate_externalids.php on line 81 and defined in /var/www/loris/php/libraries/Site.class.inc:21
Stack trace:
#0 /var/www/loris/tools/generate_candidate_externalids.php(81): Site::singleton()
#1 {main}
  thrown in /var/www/loris/php/libraries/Site.class.inc on line 21
`

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Run script as intended
2. See error

### PR DESCRIPTION
**Pull request by shonibare**
fixes #8062

### CODE REVIEW

**Comment by driusan** [comment]
This doesn't look right to me. The constructor for CenterID/ProjectID takes a string, while this is casting to an int.

**Comment by shonibare** [comment]
changes updated!

**Comment by ridz1208** [comment]
@driusan should probably go to 24.1

**Comment by driusan** [comment]
This is still not going to work. The singleton and getProjectFromID methods take a Center/ProjectID.

**Pull request closed without merging**
