### PR TITLE
sweetalert update

### LINKED ISSUE #6114: Remove SWAL from htdocs/vendor
We currently have 2 versions of swal used in LORIS: sweetalert2, managed by npm, and sweetalert, which is placed in the htdocs/vendor/js/sweetalert directory. We should migrate all usage to be the sweetalert2 version and remove the old vendored code.

### PR DESCRIPTION
**Pull request by haoweiqiu**
## Brief summary of changes
This updates sweetalert to sweetalert2 in most javascript files. However, the only file that does not change is NDB_Page.class.inc, since there is some error in Travis. This Pull Request contains commits of my another Pull Request (#6192).

Haowei Qiu, GSOC Applicant
CC @christinerogers 

#### Link(s) to related issue(s)

* Partially Resolves #6114   (Reference the issue this fixes, if any.)

### CODE REVIEW

**Comment by christinerogers** [comment]
Hi @haoweiqiu please note in this PR description that you are applying for **GSOC** - thanks

**Comment by haoweiqiu** [comment]
@driusan I have rebased to master branch in my local repository. May I created another pull request from my master branch to resolve this issue?

**Comment by driusan** [comment]
@haoweiqiu if you've rebased on master on your local repository you should just need to run `git rebase --force-with-lease` in order to update it on github.

**Comment by haoweiqiu** [comment]
@driusan Sorry for the confusion. I just realized that while I was merging conflicts during git rebase, I directly merged this branch to my master branch..

**Comment by haoweiqiu** [comment]
@driusan The merge conflict issue is finally resolved.

**Pull request merged**
