### PR TITLE
Define spec for LORIS Logic Parser

### PR DESCRIPTION
**Pull request by ZainVirani**
The LLP can be used to create formulas to be evaluated on the fly. This is useful for scoring, instrument rules, element display rules, and other on the fly calculations. The original purpose of the LLP was to handle formulas in REDCap instruments imported to CAP, but it quickly ended up covering all the XIN rules use cases + more, and was easier to use. Things like require, and display if can easily be handled, as well as range validation (provided the element stores range properties).

See #3355 

Main functions:

- able to access context variables from a defined scope and evaluate them in equations (such as Candidate DOB, Visit start date, anything you supply to the scope)
- easy to use
- human readable syntax
- functions can easily be added without recompilation
- end users (psychologists, researchers, non-devs) can easily add rules via a front end equation builder in the instrument builder

Other Fun features:

- infinitely nested variable access
- fraction factorials
- variance and standard deviation
- basic logic
- Euler's number
- date calculations

Possible extensions:

- [ ] Lookup tables (values can be referred to through nested context access)
- [ ] Statistics (ANOVA, t-tests, other tests)
- [ ] DQT (creating derived variables in a query)

### CODE REVIEW

**Comment by ZainVirani** [comment]
@driusan should I close this and make a PR for the parser itself?

**Comment by driusan** [comment]
@ZainVirani No, this should be done first.. but #3355 needs to be finished before this one.

**Comment by HenriRabalais** [comment]
Blocked by #3355

**Comment by johnsaigle** [comment]
This PR needs a new maintainer @ridz1208

**Comment by zaliqarosli** [comment]
i'll be taking over this PR

**Pull request closed without merging**
