### PR TITLE
Test next stage

### PR DESCRIPTION
**Pull request by jstirling91**

### CODE REVIEW

**Comment by Jkat** [comment]
Hey Jordan, do we have instruments yet/does this populate a list of test instruments?

**Comment by jstirling91** [comment]
@Jkat No I don't all the specific test battery stuff is tested by the unit tests, I'm merely checking to see if the basic rules are enforced and that the battery is created

**Comment by driusan** [comment]
I think he's referring to this test: https://github.com/aces/Loris/blob/16.04-dev/test/integrationtests/BatteryLookup_Test.php

**Comment by samirdas** [comment]
Use safeGet function and rebase

**Comment by driusan** [comment]
Removed "PassedCodeReview" because it's failing Travis..

**Pull request merged**
