### PR TITLE
Redmine 6710 - Automated Test for Candidate List 

### PR DESCRIPTION
**Pull request by stellarxo**
see PR#1194 for commits

### CODE REVIEW

**Comment by driusan** [comment]
Can you add a change to this to trigger Travis? It seems to be working on new changes again.

**Comment by stellarxo** [comment]
@driusan Hi Dave, I fixed the PHPCS stuff, but I can't figure out the rest of the errors. I tried re-running Travis twice... Any suggestions?

**Comment by stellarxo** [comment]
Realized that the CSS selectors I used are probably not valid.. Gonna fix this

**Comment by stellarxo** [comment]
@karolinamara (NOT URGENT) I keep getting the following error: Use of undefined constant CONFIG_XML - assumed 'CONFIG_XML'

**Pull request closed without merging**
