### PR TITLE
[integration test]check react page load

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes
Make sure react pages load well.
It will find the page has error.
截屏2022-11-02 上午11 13 01
#### Testing instructions 
Automation test will pass gitactions test.

### CODE REVIEW

**Comment by cmadjar** [comment]
@shonibare could you review/test please? Thanks!

**Comment by cmadjar** [comment]
@kongtiaowang can you look into that? Thanks!

**Comment by shonibare** [comment]
@cmadjar I have reviewed again and it works

**Review by xlecours — COMMENTED** [review]
This will only work for as long as the error messages don't change.
We would need to add a test to find the exact error message for when they are legitimate. 
Instead, I think the test should check for a distinctive element in the DOM or count a number of elements (e.g.: input fields).
Bonus if the test error contains the bodytext so we can see what the html page was when the error occured.

**Pull request merged**
