### PR TITLE
Removed obsolete table feedback_bvl_types_site.

### PR DESCRIPTION
**Pull request by nicolasbrossard**
Removed obsolete table feedback_bvl_types_site.

### CODE REVIEW

**Comment by driusan** [comment]
I don't see what the caveat is or why this would go in release notes.

**Comment by nicolasbrossard** [comment]
I thought we always indicated somewhere the list of tables from previous versions of LORIS that get deleted in the current version (caveat). Anyway, I'll remove both tags.

**Comment by driusan** [comment]
I don't think we've ever done that, but I might be misremembering..

**Comment by christinerogers** [comment]
Looks fine to me.  Drop command works.  Can't verify the rest of database is unaffected but it really shouldn't be. Could also be tested on Demo and Test. 
Dropping tables should get a caveat, just for courtesy to existing projects who may have used the feature, though Loris-trunk doesn't.

**Pull request merged**
