### PR TITLE
[Multiple] Add missing getCSSDependencies() 

### PR DESCRIPTION
**Pull request by alisterdev**
- [x] Added getCSSDependencies() to all remaining modules that has CSS but were not implementing the function.
- [x] Removed unused CSS files

### CODE REVIEW

**Comment by driusan** [comment]
Is this required for 17.0 or can it be done in the 17.1 release?

**Comment by alisterdev** [comment]
@driusan I guess it's not required, since missing CSS is so minimal, that it went unnoticed during testing, but the changes in this PR are pretty minimal as well

**Comment by driusan** [comment]
If it's broken it should be fixed, I just wasn't sure if it was a bug or a cleanup..

**Comment by alisterdev** [comment]
Well.. I don't know if its considered broken if some very minor things are not displayed the way someone (who added that css long time ago) intended them to display.

Otherwise it's more of a cleanup

**Comment by alisterdev** [comment]
Actually, this fixes a couple of spacing issues in `config` module and makes clickable table rows in `data team helper change` cursor style. Everything else is cleanup

**Pull request merged**
