### PR TITLE
Remove VERSION file and replace with a build step

### PR DESCRIPTION
**Pull request by driusan**
This removes the VERSION file and instead adds a build step to LORIS to autogenerate it.

The build step currently runs npm compile, composer install, and generates the VERSION file.

Ideally the currently committed compiled javascript files would be removed too, but something about our webpack config breaks if the files aren't already present, so that will need to be investigated separately.

### CODE REVIEW

**Comment by ridz1208** [comment]
@driusan either we need to keep a placeholder version file if the front end is still looking for one, or we need to remove it from the front end

**Comment by ridz1208** [comment]
related:
https://github.com/aces/Loris/pull/3249
https://github.com/aces/Loris/pull/3037

**Comment by driusan** [comment]
The make step generates the "placeholder"

**Comment by ridz1208** [comment]
but rnt we gonna get errors on the development branches if the file doesnt exist ? thus Travis failing.. ?

**Comment by johnsaigle** [comment]
@ridz1208 I could be wrong but if you checkout Dave's branch and run `make dev` it should create the VERSION file

**Comment by driusan** [comment]
`make` or `make dev` both generate the version file.. I just forgot travis needs the dev option for composer, and it's not finding `vendor/bin/phpcs` right now.

**Comment by driusan** [comment]
@ridz1208 I don't think it needs to evolve other than passing Travis and updating the docs.. I rebased it to see where it's at with Travis now, since it's such an old PR..

**Comment by ridz1208** [comment]
@driusan tried resolving the conflicts so it can be reviewed/ tested

**Comment by zaliqarosli** [comment]
@johnsaigle LORIS thinks you are a good person to look at this

**Comment by driusan** [comment]
@johnsaigle Can you re-test? I had to rebase it.

**Comment by driusan** [comment]
@johnsaigle ?

**Pull request merged**
