### PR TITLE
[email] Modified the lost_password template slightly to make it clearer

### PR DESCRIPTION
**Pull request by ridz1208**
This PR changes the formulation used in the email template `lost_password.tpl` to make it clearer to the user

### CODE REVIEW

**Comment by driusan** [comment]
Assuming this is intended to address redmine ticket #8525, I don't think this does it. The more important part of the ticket isn't the subject email, it's that you can lock someone out of their account by requesting a new password for them.

The study should also remain in the subject, I think. (The ticket suggests doing it systematically in the Email wrapper, while this still does it on an ad-hoc per template basis.)

**Comment by ridz1208** [comment]
@driusan 
- missed the first part of the ticket oops
- I don't think we should have the full study name in the subject as it will make the subject completely useless. I think either only "loris" or "%study_acronym% Loris" is more than sufficient. The full study name should be a header of the email if we ever decide to move to html emails to keep up with times (the 1990's that is) and implementing the default addition is not worth the time it will take

**Comment by driusan** [comment]
But this change doesn't include ""%study_acronym%", and just "LORIS" doesn't let you know where the email is coming from (ie staging, demo, prod, another study that you're on, etc).

I think if study_acronym was added to the subject it would be an improvement (even if there's still the more urgent locking users out issue), but as is this is just shuffling things around.

**Comment by driusan** [comment]
actually that's not true, this is a slight improvement because at least now you know it's a LORIS related email.. but can we add the study_acronym?

**Comment by ridz1208** [comment]
is study acronym saved anywhere in the database ??

**Comment by driusan** [comment]
not that I'm aware of, but I'm not opposed to adding it. There's multiple places where it would be useful (the menu, here, probably places in the dashboard or other random module templates, etc)

**Comment by ridz1208** [comment]
@driusan on it

**Pull request closed without merging**
