### PR TITLE
[survey_accounts] Remove all traces of emails from the database

### PR DESCRIPTION
**Pull request by ridz1208**
## Brief summary of changes

Removing all traces of stored emails in the database without affecting emailing functionality.

### CODE REVIEW

**Comment by ridz1208** [comment]
@zaliqarosli @jesscall can one of you test this on 21 ??

**Review by zaliqarosli — APPROVED** [review]
works perfectly!

**Comment by ridz1208** [comment]
@CamilleBeau did you find the source of your issues ? if not, we can have a call about it tomorrow

**Comment by CamilleBeau** [comment]
> @CamilleBeau did you find the source of your issues ? if not, we can have a call about it tomorrow

No I didn't yet. I'll slack you

**Review by CamilleBeau — APPROVED** [review]

**Comment by CamilleBeau** [comment]
Everything looks good on CCNA

**Pull request merged**
