### PR TITLE
[document_repository] Uploading file too large not reporting correctly #9158 - fix

### PR DESCRIPTION
**Pull request by kongtiaowang**
## Brief summary of changes

[document_repository] Uploading file too large not reporting correctly #9158

#### Testing instructions (if applicable)

upload a large file more than 1 GB, it will popup a error message "file too large"
截屏2024-03-27 上午10 36 00

### CODE REVIEW

**Review by regisoc — COMMENTED** [review]
Hi Shen, thanks for this PR.

I cannot see the "File too large" window appearing.
When trying to send a 5+GB file, I still have this error log:
```
[Thu Apr 04 10:45:44.134866 2024] [php:warn] [pid 17999] [client ::1:56220] PHP Warning:  POST Content-Length of 5214864626 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer: http://localhost:8080/document_repository/
```
JS console log:
image

**Comment by driusan** [comment]
There are 2 related `php.ini` settings that affect the maximum size (I can't remember the settings off the top of my head, but they should be in the documentation.) It's possible that the code is checking one but not the other.

**Comment by regisoc** [comment]
https://acesloris.readthedocs.io/en/latest/docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/02_Website_Configuration/Handling_Large_File_Uploads.html#handling-large-file-uploads

**Comment by regisoc** [comment]
Still having the same error after applying these config.

**Comment by kongtiaowang** [comment]
@regis Could you try to upload a 2GB file to test the popup window? It seems like you got the network issue when you upload a 5 GB file.

**Comment by regisoc** [comment]
@kongtiaowang I will try that.

**Comment by regisoc** [comment]
Same error on Firefox with ~1.9GB archive file.
Log: 
```
[Tue Apr 09 10:09:41.989971 2024] [php:warn] [pid 1402] [client ::1:47224] PHP Warning:  POST Content-Length of 2093357522 bytes exceeds the limit of 1073741824 bytes in Unknown on line 0, referer: http://localhost:8080/document_repository/
```

image

**Comment by regisoc** [comment]
Tested with the same file on 26.0 vm with firefox. Looks ok on it.
image

**Review by regisoc — APPROVED** [review]
Shen and I tested this on 2 VMs.
I had some issues with my config because of the SSH tunnel, it seems.
Using my VM through SSH tunnel raise the error, but using it with the VPN does not.

**Pull request merged**
