### PR TITLE
[DICOM Archive] Remove unused method

### PR DESCRIPTION
**Pull request by alisterdev**
- [x] Remove unused method (since data table is now rendered in React)

### CODE REVIEW

**Comment by driusan** [comment]
Is there any way for a user to construct a URL such that this would fall back on the default NDB_Menu_Filter and display non-anonymized data?

**Comment by alisterdev** [comment]
@driusan Not sure if this comment is meant to be here

**Comment by driusan** [comment]
I mean the code you removed is the code that did the anonymization before the table was converted to react. If the code isn't there, and a hacker finds a way to call the function, the base class function will be called instead, which just directly returns the table data without doing any anonymization.

Are we sure there isn't some way to construct a URL such that _setDataTable will be called and dump the data?

**Comment by alisterdev** [comment]
@driusan I was just told by @xlecours that we can remove it. Was not aware of any potential security risks.

**Pull request merged**
