### PR TITLE
[data_release] Fix access for admin

### PR DESCRIPTION
**Pull request by ridz1208**
### Brief summary of changes
The data_release test plan mentions that `2. Make sure that only the 'superuser' can ... as well as the list of already uploaded files` which makes sens but is not currently the case. this PR changes the query slightly to make sure the Admin user can see all the files and only regular users have a limited subsection.

### to test
- [ ] as a regular user make sure you can only see the files you have access to.
- [ ] as an admin make sure you can see all the files

### CODE REVIEW

**Comment by ridz1208** [comment]
@HenriRabalais the data_release lets you upload whatever filetypes you want if you would like to test just upload to your dev a couple files from your computer

@xlecours I think you are right.

@zaliqarosli The query has 3 joined tables, I separated the first 2 from the 3rd but I could/should have separated the first from the 2 others because the second table is not necessary unless you are looking for a specific user !!

**Comment by driusan** [comment]
Has anyone tested this?

**Comment by ridz1208** [comment]
@sruthymathew123 easy one to test when you have a chance.

test it as superuser and as regular user

**Comment by PapillonMcGill** [comment]
@ridz1208 Effectively, if the user is superadmin, permissions are irrelevant, the first JOIN could also be moved to the IF block

**Comment by ridz1208** [comment]
@PapillonMcGill @xlecours already requested these changes

**Comment by PapillonMcGill** [comment]
@ridz1208 That is why I added the "Effectively" at the beginning of my comments and didn't request change but just made a comment.

**Comment by driusan** [comment]
English semantics aside.. has anyone tested this?

**Comment by sruthymathew123** [comment]
@ridz1208 Let me know when it is ready to test.

**Comment by ridz1208** [comment]
@xlecours made changes

@sruthymathew123 ready to test

**Comment by sruthymathew123** [comment]
@ridz1208 Test conditions satisfied!

**Comment by ridz1208** [comment]
@PapillonMcGill I'll deal with Travis... we have chemistry. He tells me what to do and I do it !!

**Pull request merged**
