### PR TITLE
[dqt] Update import of pagination for PR #7419

### PR DESCRIPTION
**Pull request by maltheism**
## Brief summary of changes

Updates the import of PaginationLinks in the DQT for PR #7419

### CODE REVIEW

**Comment by driusan** [comment]
Could you merge #7419 into this to ensure the tests pass? #7419 is failing.

**Comment by maltheism** [comment]
Hi @driusan build is failing but these errors are happening in the main branch as well.

**Comment by driusan** [comment]
@maltheism the build on the main branch is fixed, can you rebase?

**Comment by driusan** [comment]
@kongtiaowang can you help @maltheism with the tests on this?

**Comment by kongtiaowang** [comment]
@maltheism [it seems like most of the filter can't work. ]
Screen Shot 2022-12-13 at 10 47 46 PM

**Comment by driusan** [comment]
The referenced PR for PaginationLinks is closed, so I don't think this is relevant anymore and can be closed.

**Pull request closed without merging**
